window.CADRO_TR_ar = {
    meta_title_index: 'CADRO | منصة الموارد البشرية من الجيل القادم',
    meta_desc_index: 'يجمع CADRO التوظيف والملف الإلكتروني والحضور والإجازات والشراء وسير العمل الداخلي في منصة واحدة.',
    meta_title_pay: 'CADRO | دفع آمن',
    home_quicklinks_eyebrow: 'وصول سريع',
    home_quicklinks_title: 'اكتشف وحدات CADRO حسب حاجة العمل',
    home_quicklinks_text: 'انتقل بسرعة أكبر من الصفحة الرئيسية إلى صفحات المنتج الأساسية وراجع كل وحدة ضمن سياق أوضح.',
    home_quicklink_1_title: 'نظام تتبع المتقدمين',
    home_quicklink_1_text: 'أدر مسار المرشحين والإعلانات الوظيفية وسير التوظيف في هيكل واحد.',
    home_quicklink_1_cta: 'استكشف صفحة ATS',
    home_quicklink_2_title: 'الملف الوظيفي الرقمي والإجازات',
    home_quicklink_2_text: 'ركز مستندات الموظفين وموافقات الإجازات وملفات شؤون الموظفين.',
    home_quicklink_2_cta: 'استكشف صفحة الملف والإجازات',
    home_quicklink_3_title: 'الحضور والورديات',
    home_quicklink_3_text: 'حوّل الحضور والعمل الإضافي وتخطيط الورديات إلى عملية جاهزة للرواتب.',
    home_quicklink_3_cta: 'استكشف صفحة الحضور',
    home_quicklink_4_title: 'الأداء و OKR',
    home_quicklink_4_text: 'أدر الأهداف والتغذية الراجعة وتتبع الأداء بوضوح استراتيجي أكبر.',
    home_quicklink_4_cta: 'استكشف صفحة الأداء',
    home_quicklink_5_title: 'المصروفات والمشتريات',
    home_quicklink_5_text: 'أدر المصروفات والمشتريات ومسارات الموافقة بانضباط مالي أعلى.',
    home_quicklink_5_cta: 'استكشف صفحة العمليات المالية',
    home_quicklink_6_title: 'قاعدة المعرفة والتهيئة',
    home_quicklink_6_text: 'نظّم المعرفة المؤسسية وإدارة السياسات ومسارات التهيئة.',
    home_quicklink_6_cta: 'استكشف صفحة قاعدة المعرفة',
    meta_desc_pay: 'صفحة CADRO الآمنة للدفع والاشتراك.',
    meta_title_security: 'أمان بيانات الموارد البشرية والوصول | CADRO',
    meta_desc_security: 'احمِ بيانات الموارد البشرية عبر صلاحيات حسب الدور، وأمن كلمات المرور والجلسات، وسجلات التدقيق، والحوكمة الإدارية.',
    meta_title_architecture: 'CADRO | البنية',
    meta_desc_architecture: 'بنية سحابية قابلة للتوسع وأداء موثوق.',
    meta_title_compliance: 'إدارة الامتثال وعمليات KVKK للموارد البشرية | CADRO',
    meta_desc_compliance: 'أدِر جاهزية وثائق الموظفين وإقرارات السياسات ورؤية الملف الوظيفي الرقمي ضمن مسار امتثال واحد.',
    meta_title_privacy: 'CADRO | سياسة الخصوصية',
    meta_title_terms: 'CADRO | شروط الاستخدام',
    meta_title_refund: 'CADRO | سياسة الاسترداد',
    'meta_title_ats-ise-alim-yazilimi': 'نظام تتبع المرشحين (ATS) وبرنامج التوظيف | CADRO نظام إدارة الموارد البشرية',
    'meta_desc_ats-ise-alim-yazilimi': 'أدر المتقدمين في مسار واحد، وابنِ قاعدة مرشحين، وسرّع المقابلات باستخدام نظام ATS من CADRO.',
    meta_title_blog: 'مدونة CADRO | الموارد البشرية والذكاء الاصطناعي والقيادة',
    meta_title_faq: 'الأسئلة الشائعة | CADRO',
    meta_desc_faq: 'إجابات حول الأسعار والوحدات والأمان والدعم والتكاملات في CADRO.',
    'meta_title_vaka-calismalari': 'دراسات الحالة | CADRO',
    'meta_desc_vaka-calismalari': 'استعرض نتائج تشغيلية واقعية وقصص نجاح العملاء عبر قطاعات مختلفة.',
    meta_desc_privacy: 'معلومات أساسية حول مبادئ الخصوصية ومعالجة البيانات في CADRO.',
    meta_desc_terms: 'الإطار التعاقدي الأساسي للوصول إلى خدمات CADRO واستخدامها.',
    meta_desc_refund: 'سياسة إلغاء الاشتراك والاسترداد ومراجعة الفواتير.',
    meta_desc_blog: 'أحدث اتجاهات الإدارة واستراتيجيات الذكاء الاصطناعي ومقالات قيادة الفرق لمديري الموارد البشرية.',
    'meta_title_dijital-ozluk-ve-izin': 'الملف الوظيفي الرقمي وإدارة الإجازات | CADRO',
    'meta_desc_dijital-ozluk-ve-izin': 'أدر ملفات الموظفين الرقمية وامتثال المستندات وسير موافقات الإجازات ضمن منصة موارد بشرية واحدة.',
    'meta_title_excel-vs-cadro': 'Excel مقابل CADRO في الموارد البشرية | لماذا لا تكفي الجداول',
    'meta_desc_excel-vs-cadro': 'ما مخاطر Excel في إدارة الموارد البشرية؟ وفّر الوقت والتكلفة مع أتمتة CADRO.',
    'meta_title_ik-sozlugu': 'قاموس مصطلحات الموارد البشرية | CADRO',
    'meta_desc_ik-sozlugu': 'تعريفات واضحة ومحدثة لمفاهيم مثل الحضور وOKR وTurnover وeNPS وغيرها.',
    'meta_title_ik-yazilimi': 'ما هو برنامج الموارد البشرية؟ | CADRO',
    'meta_desc_ik-yazilimi': 'تعرف على مكونات برامج HR وأدر التوظيف والملف والإجازات والأداء والرواتب من منصة واحدة.',
    'meta_title_kurumsal-bilgi-bankasi-ve-onboarding': 'برنامج قاعدة المعرفة والتهيئة | CADRO',
    'meta_desc_kurumsal-bilgi-bankasi-ve-onboarding': 'أدِر السياسات وSOP وإقرارات القراءة ومهام التهيئة من مسار معرفة مركزي واحد.',
    'meta_title_masraf-ve-satin-alma': 'إدارة المصاريف وطلبات الشراء | CADRO',
    'meta_desc_masraf-ve-satin-alma': 'أوقف الإنفاق غير المنضبط مع مسارات موافقة رقمية وشراء شفاف.',
    'meta_title_performans-degerlendirme-okr': 'إدارة الأداء وOKR وتقييم 360 | CADRO',
    'meta_desc_performans-degerlendirme-okr': 'أدر تقييم الأداء وملاحظات 360 وتتبع OKR في منصة واحدة تدعم الأهداف والتطوير.',
    'meta_title_puantaj-ve-vardiya-yazilimi': 'الحضور الذكي والدوام وإدارة الورديات | CADRO',
    'meta_desc_puantaj-ve-vardiya-yazilimi': 'قلل تسرب الرواتب والمخاطر القانونية مع حضور دقيق وخطط ورديات ديناميكية.',
    'meta_title_ucretsiz-sablonlar': 'قوالب موارد بشرية مجانية وExcel | CADRO',
    'meta_desc_ucretsiz-sablonlar': 'حمّل قوالب التهيئة ونماذج الأداء وجداول Excel لتسريع عمليات HR.',
    'meta_title_makale-yapay-zeka-genai': 'توفير 15 ساعة أسبوعياً في عمليات HR بالذكاء الاصطناعي التوليدي | مدونة CADRO',
    'meta_desc_makale-yapay-zeka-genai': 'كيف توفر 15 ساعة أسبوعياً في التوظيف وتقييم الأداء والتهيئة باستخدام الذكاء الاصطناعي التوليدي.',
    'meta_title_makale-prediktif-ik': 'الموارد البشرية التنبؤية: من سيستقيل مبكراً؟ | CADRO',
    'meta_desc_makale-prediktif-ik': 'استخدم التحليلات التنبؤية لاكتشاف مخاطر الاستقالة مبكراً.',
    'meta_title_makale-ise-alimda-ai-etik': 'الذكاء الاصطناعي في التوظيف: تقليل التحيز أم تعميقه؟ | CADRO',
    'meta_desc_makale-ise-alimda-ai-etik': 'المخاطر الأخلاقية والتحيز والاستخدام المسؤول في التوظيف.',
    'meta_title_makale-ai-ve-kvkk-uyumu': 'الذكاء الاصطناعي وKVKK: إدارة المخاطر القانونية | CADRO',
    'meta_desc_makale-ai-ve-kvkk-uyumu': 'كيف تحافظ على الامتثال عند استخدام بيانات الموظفين.',
    'meta_title_makale-sessiz-istifa-maliyeti': 'ما تكلفة الاستقالة الصامتة على شركتك؟ | CADRO',
    'meta_desc_makale-sessiz-istifa-maliyeti': 'التأثير الخفي لانخفاض الارتباط على التكاليف.',
    'meta_title_makale-ik-dijital-donusum-2026': 'دليل التحول الرقمي للموارد البشرية 2026 | CADRO',
    'meta_desc_makale-ik-dijital-donusum-2026': 'توقعات العائد والأولويات وخارطة الطريق.',
    'meta_title_makale-turnover-dusurme-yollari': '5 طرق قائمة على البيانات لخفض دوران الموظفين | CADRO',
    'meta_desc_makale-turnover-dusurme-yollari': 'خطوات عملية لخفض معدل الاستقالات.',
    'meta_title_makale-yillik-performans-degerlendirme': 'هل انتهى عصر تقييم الأداء السنوي؟ | CADRO',
    'meta_desc_makale-yillik-performans-degerlendirme': 'لماذا لا تكفي التقييمات السنوية وما البدائل.',
    'meta_title_makale-dijital-ozluk-ve-kvkk': 'الملف الرقمي وتدقيقات KVKK | CADRO',
    'meta_desc_makale-dijital-ozluk-ve-kvkk': 'الامتثال والصلاحية القانونية للأرشفة الإلكترونية.',
    'meta_title_makale-excel-bordro-sizintilari': 'تسرب الرواتب: تكلفة الجداول في Excel | CADRO',
    'meta_desc_makale-excel-bordro-sizintilari': 'كيف تؤدي جداول الدوام اليدوية إلى التسرب والمخاطر.',
    nav_modules: 'الوحدات',
    nav_platform: 'المنصة',
    nav_pricing: 'الأسعار',
    nav_demo: 'جولة المنتج',
    nav_trust: 'الأمان',
    nav_contact: 'التواصل',
    nav_case_studies: 'دراسات الحالة',
    nav_software: 'برنامج الموارد البشرية',
    nav_solutions: 'الحلول',
    nav_compare: 'لماذا كادرو؟',
    nav_resources: 'الموارد',
    cta_ats_module: 'عرض وحدة ATS →',
    cta_performance_module: 'عرض وحدة الأداء →',
    cta_dossier_module: 'عرض وحدة الملف والإجازات →',
    cta_timekeeping_module: 'عرض حل الدوام →',
    cta_excel_compare: 'قراءة المقارنة كاملة →',
    cta_hr_glossary: 'عرض قاموس الموارد البشرية →',
    cta_free_templates: 'تنزيل القوالب →',
    cta_blog: 'قراءة المدونة →',
    cta_case_studies: 'عرض دراسات الحالة →',
    resources_eyebrow: 'موارد مجانية',
    resources_title: 'مركز معرفة لقادة الموارد البشرية',
    resources_text: 'لا نقدّم برمجيات فقط، بل نساعدك على تشغيل الموارد البشرية بشكل أفضل.',
    resource_1_title: 'قاموس الموارد البشرية',
    resource_1_text: 'تعريفات واضحة لمصطلحات الموارد البشرية من الدوام إلى eNPS و OKR.',
    resource_2_title: 'قوالب مجانية',
    resource_2_text: 'قوائم تهيئة، أسئلة مقابلات، ونماذج اتفاقيات.',
    resource_3_title: 'مدونة أكاديمية كادرو',
    resource_3_text: 'أحدث اتجاهات الموارد البشرية والمقالات وآراء الخبراء.',
    resource_4_title: 'دراسات الحالة',
    resource_4_text: 'تعرّف على كيف غيّرت شركات حقيقية عمليات الموارد البشرية وما النتائج التي حققتها.',
    nav_home: 'الرئيسية',
    nav_all_features: 'كل الميزات',
    nav_blog: 'المدونة',
    btn_login: 'تسجيل الدخول',
    btn_payment_page: 'الدفع',
    btn_start_selling: 'ابدأ الآن',
    btn_view_plans: 'عرض الخطط',
    btn_back_home: 'العودة للرئيسية',
    sticky_plan_start: 'Basic',
    sticky_plan_growth: 'Pro',
    sticky_plan_scale: 'Enterprise',
    sticky_plan_start_meta: '$99 / شهرياً',
    sticky_plan_growth_meta: '$249 / شهرياً',
    sticky_plan_scale_meta: '$699 / شهرياً',
    sticky_plan_cta: 'عرض الخطط',
    hero_eyebrow: '',
    hero_title: 'برنامج موارد بشرية سحابي',
    hero_text: 'أدر التوظيف والأداء والإجازات والحضور عبر منصة سحابية موحّدة.',
    hero_subtext: 'يجمع CADRO جميع عمليات الموارد البشرية في منصة برنامج موارد بشرية سحابية واحدة.',
    btn_start_subscription: 'ابدأ الاشتراك',
    btn_view_demo: 'شاهد المنتج',
    point_multi_tenant: 'بنية سحابية',
    point_role_based: 'صلاحيات متقدمة',
    point_kvkk: 'امتثال كامل للبيانات',
    video_eyebrow: 'فيلم المنتج',
    video_title: 'شاهد CADRO خلال 90 ثانية',
    video_text: 'شاهد فيلماً قصيراً يوضح كيف يربط CADRO الإدارة والعمليات وتجربة الموظف في منصة واحدة.',
    video_point_1_title: 'مركز تحكم واحد',
    video_point_1_text: 'راقب مسارات الموارد البشرية والعمليات والمالية من عرض واحد.',
    video_point_2_title: 'مسارات عمل حقيقية',
    video_point_2_text: 'تابع ATS والحضور والملف الوظيفي والموافقات ضمن قصة واحدة مترابطة.',
    video_point_3_title: 'نظرة سريعة قبل العرض',
    video_point_3_text: 'افهم إيقاع المنتج ونطاقه قبل استعراض الخطط.',
    metric_modules_label: 'الوحدات النشطة',
    metric_modules_text: 'النواة، ATS، الحضور، الملف الإلكتروني، الأداء',
    metric_ops_label: 'القوة التشغيلية',
    metric_ops_value: 'مرن وديناميكي',
    metric_ops_text: 'لوحات مخصصة للموظفين والمديرين والإدارة',
    metric_ready_label: 'إعداد سريع',
    metric_ready_value: 'تفعيل فوري',
    metric_ready_text: 'قم بإعداد هيكل شركتك وابدأ الاستخدام في دقائق',
    metric_ui_label: 'تجربة المستخدم',
    metric_ui_value: 'نظيف وحديث',
    metric_ui_text: 'لا يتطلب تدريب، يعمل بسلاسة على أي جهاز',
    strip_product_label: 'الكل في واحد',
    strip_product_text: 'نظام إدارة الموارد البشرية + ATS + بوابة الموظف + مسارات العمل',
    strip_who_label: 'لمن هذا المنتج؟',
    strip_who_text: 'للفرق الحديثة التي تتطلع لرقمنة عملياتها',
    strip_delivery_label: 'نموذج الخدمة',
    strip_delivery_text: 'SaaS من الجيل القادم على بنية سحابية آمنة',
    proof_title: 'لماذا تختار CADRO؟',
    compare_eyebrow: 'لماذا CADRO؟',
    compare_title: 'أليس الوقت مناسباً لترك الجداول اليدوية؟',
    compare_1_title: 'توفير الوقت',
    compare_1_text: 'ما يستغرق وقتاً طويلاً في Excel يصبح أسرع وأكثر قابلية للتحكم مع أتمتة CADRO.',
    compare_2_title: 'دقة أعلى',
    compare_2_text: 'تحديثات تلقائية بين الأقسام دون إدخال مكرر.',
    compare_3_title: 'أمان البيانات',
    compare_3_text: 'وصول قائم على الأدوار وأرشفة سحابية آمنة تمنح فريقك نموذج تشغيل أكثر ضبطاً.',
    proof_line_1: 'يتم جمع كافة بياناتك في مركز آمن واحد.',
    proof_line_2: 'يوفر عمليات شفافة مع وصول قائم على الأدوار.',
    proof_line_3: 'يعمل بمنطق ذكي يمنع تكرار البيانات.',
    proof_metric_1_label: 'إدارة مركزية',
    proof_metric_1_text: 'الملف والحضور والمستندات متكاملة تماماً.',
    proof_metric_2_label: 'تدفق مستمر',
    proof_metric_2_text: 'تترك العمليات بصمة رقمية واضحة.',
    proof_metric_3_label: 'تجربة حديثة',
    proof_metric_3_text: 'تصميم نظيف يحب الموظفون استخدامه.',
    modules_eyebrow: 'الحلول',
    modules_title: 'وحدات تقوي عملياتك.',
    modules_text: 'جميع أدوات الموارد البشرية التي تحتاجها في متناول يدك ومتكاملة.',
    module_1_title: 'التوظيف و ATS',
    module_1_text: 'إدارة الوظائف والمرشحين والمقابلات باحترافية.',
    module_2_title: 'الملف الإلكتروني',
    module_2_text: 'تخزين آمن ومتابعة تلقائية للمستندات الناقصة.',
    module_3_title: 'الحضور الذكي',
    module_3_text: 'تجهيز الورديات والغياب لرواتب خالية من الأخطاء.',
    module_4_title: 'الإجازات والعمل المرن',
    module_4_text: 'إدارة سهلة لأنواع الإجازات ومسارات الموافقة.',
    module_5_title: 'المصاريف والمشتريات',
    module_5_text: 'ربط نفقات الموظفين بموافقات رقمية.',
    module_6_title: 'قاعدة المعرفة',
    module_6_text: 'نشر السياسات ومراقبة معدلات القراءة.',
    module_7_title: 'الانضمام والمغادرة',
    module_7_text: 'تصميم تجربة خالية من العيوب للموظفين الجدد.',
    module_8_title: 'الأداء والأهداف',
    module_8_text: 'قياس أداء الموظفين وتتبع المؤشرات.',
    showcase_title: 'أعد تعريف الكفاءة',
    showcase_text: 'نحن نؤتمت العمليات لتركز على أهم مواردك: موظفيك.',
    showcase_1_eyebrow: 'سجل واحد، تكامل كامل',
    showcase_1_title: 'لا مزيد من البيانات المشتتة.',
    showcase_1_text: 'اجمع الطلبات في لوحة واحدة؛ بمجرد رفع السيرة الذاتية يُقيّمها الذكاء الاصطناعي في 4 محاور: التواصل والتقنية والتوافق الثقافي والتحفيز. أتمّ المقابلة وخطاب العرض والتعيين من شاشة واحدة.',
    showcase_1_ph: 'مساحة فارغة للصور',
    showcase_2_eyebrow: 'موافقات ذكية',
    showcase_2_title: 'إنهاء المصاريف والطلبات فوراً.',
    showcase_2_text: 'حدّد أهداف OKR على مستوى الشركة والفريق والفرد، وتابع التقدم طوال الفترة. اجمع تغذية راجعة 360° من المدراء والزملاء والتقييم الذاتي. تحليل المواهب بالذكاء الاصطناعي يُعزّز قراراتك.',
    showcase_2_ph: 'مساحة فارغة لمسار الطلب',
    showcase_3_eyebrow: 'تنبيهات تلقائية',
    showcase_3_title: 'لا تفوت أي مستند أو عقد منتهي.',
    showcase_3_text: 'ملف وظيفي رقمي شامل: هوية وبيانات مصرفية وتصريح عمل وNDA — كل شيء في مكان واحد. أدر إجازات سنوية ومرضية واعتذارية وأمومة مع فحص التعارض؛ مسارات الموافقة والإشعارات الفورية تعمل تلقائياً.',
    showcase_3_ph: 'مساحة فارغة للامتثال',
    how_it_works_label: 'كيف يعمل',
    showcase_1_step_1: 'أنشئ إعلاناً وظيفياً وانشره في صفحة وظائفك',
    showcase_1_step_2: 'تُجمَع الطلبات تلقائياً ويتشكّل تجمّع المرشحين',
    showcase_1_step_3: 'تابع المرشحين عبر مراحل لوحة كانبان',
    showcase_1_step_4: 'بنقرة واحدة يتحوّل المرشح المقبول إلى بطاقة موظف',
    showcase_2_step_1: 'حدّد أهداف OKR على مستوى الشركة والفريق والفرد',
    showcase_2_step_2: 'يُحدّث الموظفون تقدّمهم طوال فترة التقييم',
    showcase_2_step_3: 'تُنجَز تقييمات 360 درجة وتحليل المواهب بالذكاء الاصطناعي',
    showcase_2_step_4: 'تُرفَع التقارير وتُبنى خطط المسار المهني',
    showcase_3_step_1: 'يُنشأ ملف رقمي لكل موظف',
    showcase_3_step_2: 'تُرفَع الوثائق والنقص يُطلق تنبيهات تلقائية',
    showcase_3_step_3: 'يُقدّم الموظف طلب إجازة من هاتفه ويتلقّى المدير إشعاراً فورياً',
    showcase_3_step_4: 'يُحدَّث رصيد الإجازة تلقائياً ويتزامن مع الرواتب',
    screen_dashboard_badge_1: 'لوحة ذكية',
    screen_dashboard_badge_2: 'تحليلات مفصلة',
    screen_dossier_badge_1: 'أرشيف سحابي',
    screen_dossier_badge_2: 'تنبيهات المستندات',
    screen_request_badge_1: 'نماذج ديناميكية',
    screen_request_badge_2: 'موافقات شفافة',
    screen_knowledge_badge_1: 'التحكم في الإصدار',
    screen_knowledge_badge_2: 'تتبع القراءة',
    results_eyebrow: 'الفوائد',
    results_title: 'ما الذي يقدمه CADRO لشركتك؟',
    results_1_title: 'توفير الوقت',
    results_1_text: 'استبدال الجداول اليدوية بأنظمة آلية.',
    results_2_title: 'عمليات خالية من الأخطاء',
    results_2_text: 'انخفاض أخطاء حسابات الحضور إلى الصفر.',
    results_3_title: 'رضا الموظفين',
    results_3_text: 'وصول شفاف ومباشر للبيانات.',
    testimonial_eyebrow: 'تجارب العملاء',
    testimonial_title: 'شاهد كيف تسرع الفرق عملياتها.',
    testimonial_1_quote: '"بفضل CADRO، اختفت الفوضى تماماً. الواجهة مذهلة."',
    testimonial_1_name: 'مدير موارد بشرية',
    testimonial_2_quote: '"إدارة كافة الموافقات من شاشة واحدة وفرت لنا وقتاً هائلاً."',
    testimonial_2_name: 'مدير عمليات',
    testimonial_3_quote: '"يعمل النظام المبني على الأدوار بشكل لا تشوبه شائبة."',
    testimonial_3_name: 'مؤسس شركة',
    faq_eyebrow: 'الأسئلة الشائعة',
    faq_title: 'أسئلة متكررة حول النظام',
    faq_q1: 'ما هي العمليات التي يغطيها CADRO؟',
    faq_a1: 'منصة شاملة تغطي الملفات، الحضور، الإجازات، المصاريف، الأداء والمزيد.',
    faq_q2: 'كيف أستورد بياناتي الحالية؟',
    faq_a2: 'بفضل أدوات الاستيراد المتقدمة، يمكنك نقل بياناتك في دقائق.',
    faq_q3: 'كيف تعمل المدفوعات؟',
    faq_a3: 'تتم المدفوعات عبر مزودنا العالمي Paddle بفواتير تلقائية.',
    faq_q4: 'هل نحتاج تدريباً فنياً؟',
    faq_a4: 'لا، الواجهة حديثة وسهلة الاستخدام فوراً.',
    faq_q5: 'هل بياناتنا آمنة؟',
    faq_a5: 'بالتأكيد. مشفرة ومحفوظة على خوادم عالمية آمنة.',
    final_cta_title: 'ابدأ في تحويل عمليات الموارد البشرية الخاصة بك اليوم.',
    final_cta_text: 'قم بإعداد حسابك في ثوانٍ، وادعُ موظفيك، وابدأ فوراً.',
    platform_eyebrow: 'بنية المنصة',
    platform_title: 'بنية تحتية قوية لتجربة سلسة.',
    flow_1_title: 'إدارة الهوية',
    flow_1_text: 'إدارة الهيكل التنظيمي والصلاحيات بمرونة.',
    flow_2_title: 'مسارات ديناميكية',
    flow_2_text: 'موافقات متعددة المستويات قابلة للتخصيص.',
    flow_3_title: 'محرك تنبيهات استباقي',
    flow_3_text: 'تنبيهات مبكرة للعقود والمستندات.',
    flow_4_title: 'تحليلات شاملة',
    flow_4_text: 'تحويل البيانات لتقارير ذات معنى.',
    pricing_eyebrow: 'الأسعار',
    pricing_title: 'خطط تناسب احتياجاتك بدون تكاليف مفاجئة.',
    pricing_text: 'اعمل براحة وبدون قيود مع باقاتنا ذات السعر الثابت.',
    billing_monthly: 'شهري',
    billing_yearly: 'سنوي',
    billing_discount_badge: 'وفر 20% سنوياً',
    pricing_toggle_note: 'يتم تسعير الخطة السنوية على أساس 10 أشهر بدلاً من 12.',
    plan_start_title: 'مثالي للفرق التي تبدأ الرقمنة.',
    plan_start_desc: 'يبني الأساس. بيانات الموظفين والإجازات في مكان واحد.',
    plan_start_price_monthly: '$99<span>/شهرياً</span>',
    plan_start_price_yearly: '$950<span>/سنوياً</span>',
    plan_start_note_monthly: 'سعر ثابت لجميع الميزات الأساسية',
    plan_start_note_yearly: 'المتوسط $79 / شهرياً',
    plan_start_li1: 'إدارة الموظفين والأقسام',
    plan_start_li2: 'إدارة الإجازات',
    plan_start_li3: 'الملف الإلكتروني',
    plan_start_li4: 'تقارير الحضور',
    plan_start_btn: 'ابدأ مع Basic',
    plan_growth_title: 'للشركات التي ترغب في تنظيم عملياتها.',
    plan_growth_desc: 'الطلبات، الموافقات، وقاعدة المعرفة في مكان واحد.',
    plan_growth_popular: 'الأكثر شيوعاً',
    plan_growth_price_monthly: '$249<span>/شهرياً</span>',
    plan_growth_price_yearly: '$2.390<span>/سنوياً</span>',
    plan_growth_note_monthly: 'سعر ثابت، جميع الميزات متضمنة',
    plan_growth_note_yearly: 'المتوسط $199 / شهرياً',
    plan_growth_li1: 'كل شيء في Basic',
    plan_growth_li2: 'طلبات المصاريف والشراء',
    plan_growth_li3: 'التوظيف والتهيئة',
    plan_growth_li4: 'قاعدة المعرفة',
    plan_growth_btn: 'ابدأ مع Pro',
    plan_scale_title: 'للمؤسسات التي تبحث عن حوكمة متقدمة.',
    plan_scale_desc: 'حزمة كاملة للفرق الأكبر بدون قيود.',
    plan_scale_price_monthly: '$699<span>/شهرياً</span>',
    plan_scale_price_yearly: '$6.799<span>/سنوياً</span>',
    plan_scale_note_monthly: 'سعر ثابت بدون قيود',
    plan_scale_note_yearly: 'المتوسط $566 / شهرياً',
    plan_scale_li1: 'كل شيء في Pro',
    plan_scale_li2: 'إدارة الأداء',
    plan_scale_li3: 'مقاييس تفصيلية',
    plan_scale_li4: 'دعم ذو أولوية',
    plan_scale_btn: 'ابدأ مع Enterprise',
    demo_eyebrow: 'جولة المنتج',
    demo_title: 'شاهد CADRO أثناء العمل',
    demo_text: 'اكتشف كيف تبسط واجهتنا عملياتك من خلال جولة سريعة.',
    video_placeholder_title: 'واجهة النظام',
    video_placeholder_text: 'شاهد الفيديو أدناه لمعرفة تفاصيل CADRO.',
    video_note_1_title: 'إعداد سريع',
    video_note_1_text: 'قم بتكييف النظام مع هيكل شركتك في دقائق.',
    video_note_2_title: 'سهل الاستخدام',
    video_note_2_text: 'واجهة حديثة سيحب فريقك استخدامها.',
    video_note_3_title: 'بنية آمنة',
    video_note_3_text: 'يتم تشفير بياناتك وحفظها بأعلى المعايير.',
    trust_eyebrow: 'الموثوقية والشفافية',
    trust_title: 'بنية تحتية بمعايير دولية',
    trust_1_title: 'برمجيات سحابية (SaaS)',
    trust_1_text: 'لا يتطلب تكاليف تثبيت أو أجهزة.',
    trust_2_title: 'خدمة مستمرة',
    trust_2_text: 'نظامنا يضمن وقت تشغيل 99.9%.',
    trust_3_title: 'دعم فني 24/7',
    trust_3_text: 'تواصل مع فريقنا لأي استفسار: ',
    trust_4_title: 'تسعير شفاف',
    trust_4_text: 'أسعار ثابتة بدون تكاليف خفية.',
    trust_5_title: 'أمان البيانات',
    legal_terms_link: 'شروط الاستخدام',
    legal_privacy_link: 'سياسة الخصوصية',
    legal_refund_link: 'سياسة الاسترداد',
    contact_eyebrow: 'التواصل',
    contact_title: 'نحن هنا لتحسين عملياتك.',
    contact_text: 'اتصل بنا فوراً للحصول على حلول مخصصة أو استفسارات.',
    btn_request_demo: 'طلب عرض حي',
    btn_request_info: 'تواصل مع المبيعات',
    cf_title: 'تواصل معنا',
    cf_desc: 'املأ النموذج أدناه وسنعود إليك في أقرب وقت.',
    cf_name: 'الاسم الكامل',
    cf_email: 'البريد الإلكتروني',
    cf_phone: 'رقم الهاتف',
    cf_company: 'اسم الشركة',
    cf_message: 'رسالتك',
    cf_submit: 'إرسال',
    cf_sending: 'جارٍ الإرسال…',
    cf_success_title: 'تم إرسال الرسالة!',
    cf_success_text: 'سنتواصل معك في أقرب وقت ممكن.',
    cf_error: 'حدث خطأ أثناء الإرسال. يرجى المحاولة مرة أخرى.',
    footer_tagline: 'برنامج الموارد البشرية السحابي المحلي من تركيا.',
    footer_product_title: 'المنتج',
    footer_product_link: 'برنامج الموارد البشرية',
    footer_pricing_link: 'الأسعار',
    footer_company_title: 'الشركة',
    footer_blog_link: 'المدونة',
    footer_cases_link: 'دراسات الحالة',
    footer_faq_link: 'الأسئلة الشائعة',
    footer_legal_title: 'قانوني',
    footer_privacy_link: 'سياسة الخصوصية',
    footer_terms_link: 'شروط الاستخدام',
    footer_refund_link: 'سياسة الاسترداد',
    footer_text: 'المنصة السحابية الحديثة لتسريع عمليات الموارد البشرية.',
    footer_copy: '© 2026 CADRO. جميع الحقوق محفوظة.',
    footer_phone: '+90 542 884 21 06',
    footer_address: 'أنقرة، تركيا',
    metric_rating: 'تقييم G2 / Capterra',
    metric_customers: 'شركة نشطة',
    metric_time_saved: 'توفير وقت الرواتب',
    metric_uptime: 'وقت التشغيل',
    footer_review_label: 'قيّمنا:',
    footer_yerli: '🇹🇷 صُنع في تركيا',
    meta_title_pricing: 'أسعار CADRO | باقات Basic وPro وEnterprise',
    meta_desc_pricing: 'قارن بين باقات CADRO Basic وPro وEnterprise وراجع تسعير عمليات الموارد البشرية في صفحة واحدة.',
    lightbox_close: 'إغلاق',
    pay_eyebrow: 'خطوة الدفع',
    pay_title: 'ابدأ اشتراكك',
    pay_text: 'انضم إلى عالم CADRO عبر الدفع الآمن.',
    pay_plan_1_title: 'Basic Plan',
    pay_plan_1_text: 'للفرق التي ترغب في تأسيس ورقمنة الموارد البشرية.',
    pay_plan_2_title: 'Pro Plan',
    pay_plan_2_text: 'لإدارة الموافقات وقاعدة المعرفة بسلاسة.',
    pay_plan_3_title: 'Enterprise Plan',
    pay_plan_3_text: 'للمؤسسات الكبيرة التي تحتاج إلى حوكمة متقدمة.',
    pay_billing_note: 'يتم تطبيق دورة الفوترة المحددة تلقائياً.',
    pay_status_success_eyebrow: 'عملية ناجحة',
    pay_status_success_title: 'أهلاً بك معنا!',
    pay_status_success_text: 'بدأ اشتراكك بنجاح. سيتم إرسال التفاصيل قريباً.',
    pay_status_cancel_eyebrow: 'تم الإلغاء',
    pay_status_cancel_title: 'لم يكتمل الدفع.',
    pay_status_cancel_text: 'يمكنك اختيار خطتك والمحاولة مرة أخرى.',
    pay_status_error_eyebrow: 'تنبيه النظام',
    pay_status_error_title: 'نظام الدفع غير متاح.',
    pay_status_error_text: 'حدثت مشكلة اتصال مؤقتة. يرجى المحاولة لاحقاً.',
    pay_cta_start: 'ابدأ مع Basic',
    pay_cta_growth: 'ابدأ مع Pro',
    pay_cta_scale: 'ابدأ مع Enterprise',
    pay_checkout_ready_eyebrow: 'دفع آمن',
    pay_checkout_ready_title: 'أكمل معاملتك بأمان',
    pay_checkout_ready_text: 'أكمل معاملتك بأمان عبر مزود الدفع العالمي الخاص بنا.',
    pay_note_eyebrow: 'مدفوعاتك آمنة',
    pay_note_title: 'تشفير آمن 256 بت',
    pay_note_text: 'تتم حماية كافة معاملاتك عبر مزود الدفع العالمي Paddle.',
    legal_eyebrow: 'المستندات القانونية',
    privacy_title: 'سياسة الخصوصية',
    privacy_intro: 'تشرح هذه السياسة كيفية حماية بياناتك.',
    privacy_p1: 'نحن نعالج فقط البيانات الضرورية لتقديم الخدمة بأمان تام.',
    privacy_p2: 'تتم معالجة الفواتير عبر شريكنا المعتمد Paddle.',
    privacy_p3: 'لطلبات الدعم والبيانات الشخصية، تواصل معنا عبر info@cadro.io.',
    privacy_p4: 'مزود الخدمة: Turgay Bozkus.',
    terms_title: 'شروط الاستخدام',
    terms_intro: 'الشروط العامة التي تخضع لها أثناء استخدامك للخدمة.',
    terms_p1: 'CADRO هي خدمة برمجيات سحابية (SaaS).',
    terms_p2: 'تخضع التغييرات والفوترة للأسعار الحالية المعلنة.',
    terms_p3: 'الاستخدام الآمن والمستمر للخدمة أمر أساسي.',
    terms_p4: 'للاستفسارات، تواصل مع مالك الخدمة Turgay Bozkus.',
    refund_title: 'سياسة الاسترداد',
    refund_intro: 'سياساتنا المتعلقة بإلغاء الاشتراكات والاسترداد.',
    refund_p1: 'يظل حسابك نشطاً حتى نهاية دورة الفوترة الحالية بعد الإلغاء.',
    refund_p2: 'لا توجد استردادات جزئية إلا في حالات الأخطاء التقنية.',
    refund_p3: 'لطلبات الاسترداد، يرجى التواصل مع فريق الدعم.',
    refund_p4: 'رضاكم هو أولويتنا.',
    nav_menu: 'القائمة',
    security_eyebrow: 'نهج الأمان',
    security_title: 'بنية آمنة لبيانات الشركات',
    security_text: 'CADRO يضع الأمان في قلب المنتج عبر التحكم بالوصول والتشفير وسجلات التدقيق.',
    security_point_1_title: 'صلاحيات قائمة على الأدوار',
    security_point_1_text: 'كل مستخدم يرى الوحدات والسجلات المصرّح له بها فقط.',
    security_point_2_title: 'تشفير ونسخ احتياطي',
    security_point_2_text: 'يتم تشفير البيانات مع نسخ احتياطي منتظم.',
    security_point_3_title: 'سجلات تدقيق',
    security_point_3_text: 'يتم تسجيل جميع العمليات الحرجة وتتبعها.',
    security_cta_eyebrow: 'مستندات الأمان',
    security_cta_title: 'دعنا نشارك تفاصيل الأمان.',
    security_cta_contact: 'طلب مستندات الأمان',
    architecture_eyebrow: 'البنية',
    architecture_title: 'بنية سحابية قابلة للتوسع',
    architecture_text: 'CADRO مبني بخدمات معيارية وبنية مرنة للفرق المتنامية.',
    architecture_point_1_title: 'خدمات معيارية',
    architecture_point_1_text: 'كل وحدة تعمل بشكل مستقل وتتكامل بأمان.',
    architecture_point_2_title: 'أداء عالٍ',
    architecture_point_2_text: 'تجربة سريعة ومستقرة حتى مع الضغط العالي.',
    architecture_point_3_title: 'الاستقرار والمراقبة',
    architecture_point_3_text: 'تتم مراقبة صحة الخدمات والأخطاء والاستخدام باستمرار.',
    architecture_cta_eyebrow: 'مراجعة تقنية',
    architecture_cta_title: 'لنراجع البنية معاً.',
    architecture_cta_contact: 'طلب إحاطة تقنية',
    compliance_eyebrow: 'الامتثال',
    compliance_title: 'عمليات متوافقة مع KVKK وGDPR',
    compliance_text: 'نعتمد تقليل البيانات وفترات الاحتفاظ وضوابط الوصول بوضوح.',
    compliance_point_1_title: 'مبادئ معالجة البيانات',
    compliance_point_1_text: 'نقوم بمعالجة البيانات الضرورية فقط وفق الغرض المحدد.',
    compliance_point_2_title: 'الشفافية والإشعارات',
    compliance_point_2_text: 'تُقدّم إشعارات واضحة للموظفين عن العمليات.',
    compliance_point_3_title: 'الحذف وإخفاء الهوية',
    compliance_point_3_text: 'نوفّر مسارات الحذف وإخفاء الهوية عند الطلب.',
    compliance_cta_eyebrow: 'دعم الامتثال',
    compliance_cta_title: 'سرّع رحلة الامتثال KVKK/GDPR لديك.',
    compliance_cta_contact: 'طلب دعم الامتثال',
    security_diagram_eyebrow: 'مخطط تقني',
    security_diagram_title: 'كيف تعمل طبقات الأمان',
    security_diagram_text: 'التحكم بالوصول والتشفير وسجلات التدقيق تعمل معاً.',
    security_diagram_node_1: 'الهوية والوصول',
    security_diagram_node_2: 'طبقة التشفير',
    security_diagram_node_3: 'سجلات التدقيق',
    security_standards_eyebrow: 'المعايير',
    security_standards_title: 'ممارسات الأمان',
    security_standards_item_1: 'عمليات متوافقة مع ISO 27001',
    security_standards_item_2: 'إدارة مفاتيح التشفير والسياسات',
    security_standards_item_3: 'اختبارات اختراق دورية',
    security_integrations_eyebrow: 'التكامل',
    security_integrations_title: 'جاهز لهوية المؤسسات',
    security_integrations_item_1: 'SSO',
    security_integrations_item_2: 'SAML',
    security_integrations_item_3: 'SCIM',
    security_integrations_text: 'ربط سريع وآمن مع مزود الهوية المؤسسي.',
    architecture_diagram_eyebrow: 'مخطط البنية',
    architecture_diagram_title: 'نظرة بسيطة على بنية CADRO',
    architecture_diagram_text: 'خدمات معيارية وطبقة بيانات ومراقبة لضمان الاستقرار.',
    architecture_diagram_node_1: 'طبقة التجربة',
    architecture_diagram_node_2: 'طبقة الخدمات',
    architecture_diagram_node_3: 'البيانات والتخزين',
    architecture_standards_eyebrow: 'التشغيل',
    architecture_standards_title: 'موثوقية التشغيل',
    architecture_standards_item_1: 'تصميم عالي التوفر',
    architecture_standards_item_2: 'بنية احتياطية',
    architecture_standards_item_3: 'مراقبة مستمرة',
    architecture_integrations_eyebrow: 'التكامل',
    architecture_integrations_title: 'تكامل الهوية',
    architecture_integrations_item_1: 'SSO',
    architecture_integrations_item_2: 'SAML',
    architecture_integrations_item_3: 'SCIM',
    architecture_integrations_text: 'متوافق مع مزودي الهوية المؤسسية.',
    compliance_diagram_eyebrow: 'مسار الامتثال',
    compliance_diagram_title: 'من جمع البيانات إلى الحذف',
    compliance_diagram_text: 'نُدير البيانات بتوثيق واحتفاظ وحذف واضح.',
    compliance_diagram_node_1: 'جرد البيانات',
    compliance_diagram_node_2: 'سياسات الاحتفاظ',
    compliance_diagram_node_3: 'طلبات الحذف',
    compliance_standards_eyebrow: 'المعايير',
    compliance_standards_title: 'ضمانات الامتثال',
    compliance_standards_item_1: 'إشعارات KVKK/GDPR',
    compliance_standards_item_2: 'سجلات المعالجة',
    compliance_standards_item_3: 'الحذف وإخفاء الهوية',
    compliance_integrations_eyebrow: 'التكامل',
    compliance_integrations_title: 'وصول آمن',
    compliance_integrations_item_1: 'SSO',
    compliance_integrations_item_2: 'SAML',
    compliance_integrations_item_3: 'SCIM',
    compliance_integrations_text: 'تحكم بالوصول عبر نظام الهوية الحالي.',

    // Blog page translations
    page_blog_main: 'مدونة CADRO | الموارد البشرية والذكاء الاصطناعي والقيادة',
    blog_hero_title: 'أكاديمية كادرو',
    blog_hero_subtitle: 'اكتشف مستقبل الموارد البشرية اليوم',
    blog_hero_text: 'محتوى استراتيجي للمديرين التنفيذيين حول ثورة الذكاء الاصطناعي واتخاذ القرارات المبنية على البيانات وبناء ثقافة الشركة.',
    blog_read_more: 'اقرأ المقال ←',

    // Blog article translations
    blog_title_onboarding: 'كيفية رقمنة عملية التهيئة؟ دليل 2026',
    blog_desc_onboarding: 'قلل تكلفة التهيئة بنسبة 60% مع العقود الرقمية والتوجيه الإلكتروني وأتمتة المهام والملف الوظيفي المتوافق مع KVKK.',
    blog_meta_onboarding: '12 مايو 2026 • التهيئة والتوظيف',

    blog_title_esnek_calisma: 'ساعات العمل المرنة 2026: الدليل القانوني للموارد البشرية',
    blog_desc_esnek_calisma: 'فترة المعادلة وتشريعات العمل عن بعد وإخطار SGK وتكامل برنامج الموارد البشرية: دليل شامل مع تحديثات قانون العمل 2026.',
    blog_meta_esnek_calisma: '05 مايو 2026 • قانون العمل وإدارة الموارد البشرية',

    blog_title_genai: 'توفير 15 ساعة أسبوعياً في عمليات الموارد البشرية بالذكاء الاصطناعي التوليدي',
    blog_desc_genai: 'كتابة إعلانات الوظائف وإعداد أسئلة المقابلات وتجميع نصوص الأداء... كيف تستخدم الذكاء الاصطناعي كمساعد للموارد البشرية لتصفير العبء التشغيلي؟',
    blog_meta_genai: '05 أبريل 2026 • الموارد البشرية والذكاء الاصطناعي',

    blog_title_prediktif: 'خوارزميات تتنبأ بالاستقالة مسبقاً: الموارد البشرية التنبؤية',
    blog_desc_prediktif: 'باستخدام التحليلات التنبؤية يمكنك اكتشاف الموظفين الرئيسيين المعرضين لخطر المغادرة قبل أشهر واتخاذ الإجراءات الوقائية.',
    blog_meta_prediktif: '02 أبريل 2026 • الموارد البشرية والذكاء الاصطناعي',

    blog_title_ai_etik: 'الذكاء الاصطناعي في التوظيف: تقليل التحيز أم تعميقه؟',
    blog_desc_ai_etik: 'مزايا استخدام الذكاء الاصطناعي في فحص السير الذاتية ومعايير التصفية الخوارزمية الأخلاقية التي يجب على المدراء التنفيذيين الانتباه لها.',
    blog_meta_ai_etik: '28 مارس 2026 • الموارد البشرية والذكاء الاصطناعي',

    blog_title_ai_kvkk: 'معضلة الذكاء الاصطناعي وKVKK: إدارة المخاطر القانونية عند معالجة بيانات الموظفين',
    blog_desc_ai_kvkk: 'كيف تبقى متوافقاً تماماً مع قانون حماية البيانات عند تغذية خوارزميات الذكاء الاصطناعي ببيانات موظفيك؟ ما يجب أن يعرفه قسمك القانوني.',
    blog_meta_ai_kvkk: '25 مارس 2026 • الموارد البشرية والذكاء الاصطناعي',

    blog_title_sessiz_istifa: 'كم تكلفك الاستقالة الصامتة في شركتك؟',
    blog_desc_sessiz_istifa: 'هل موظفوك موجودون جسدياً في المكتب لكنهم غادروا روحياً؟ نحسب التكاليف التشغيلية الخفية لانخفاض الارتباط ونقدم الحلول.',
    blog_meta_sessiz_istifa: '18 مارس 2026 • ثقافة الشركة',

    blog_title_dijital_donusum: 'دليل التحول الرقمي للموارد البشرية 2026',
    blog_desc_dijital_donusum: 'جداول Excel لم تعد أداة إدارية بل خطراً أمنياً. توقعات المدراء الماليين من استثمارات الموارد البشرية وقواعد الرقمنة.',
    blog_meta_dijital_donusum: '10 مارس 2026 • أتمتة الموارد البشرية',

    blog_title_turnover: '5 طرق قائمة على البيانات لخفض معدل الدوران المرتفع',
    blog_desc_turnover: 'لماذا يستقيل المواهب اللامعة في أول 3 أشهر؟ بيانات بحثية صادمة عن الأضرار القانونية والمالية لتجربة التهيئة السيئة.',
    blog_meta_turnover: '28 فبراير 2026 • إدارة المواهب',

    blog_title_performans: 'هل انتهى عصر تقييمات الأداء السنوية؟',
    blog_desc_performans: '70% من الموظفين يعتقدون أن تقييمات الأداء السنوية غير عادلة. مزايا الانتقال إلى ثقافة التغذية الراجعة الفورية 360 درجة.',
    blog_meta_performans: '10 فبراير 2026 • الأداء',

    blog_title_dijital_ozluk: 'الملف الوظيفي الرقمي وتدقيقات KVKK',
    blog_desc_dijital_ozluk: 'ما تحتاج معرفته لتجنب الغرق في الملفات عندما يطرق مفتشو العمل بابك. الصلاحية القانونية للأرشفة الإلكترونية.',
    blog_meta_dijital_ozluk: '22 يناير 2026 • الامتثال القانوني',

    blog_title_bordro_sizinti: 'تسرب الرواتب: التكلفة المؤلمة لاستخدام Excel في تتبع الدوام',
    blog_desc_bordro_sizinti: 'كيف تؤدي حسابات العمل الإضافي الخاطئة وانحرافات مضاعفات الورديات الليلية إلى تآكل ميزانية الرواتب الشهرية؟',
    blog_meta_bordro_sizinti: '05 يناير 2026 • الرواتب والمالية',

    blog_title_asgari_ucret: 'حساب صافي الحد الأدنى للأجور 2026: التفصيل خطوة بخطوة',
    blog_desc_asgari_ucret: 'كيف يُحسب صافي الأجر في حساب الحد الأدنى للأجور 2026؟ تفصيل خطوة بخطوة وأمثلة.',
    blog_meta_asgari_ucret: '27 أبريل 2026 • الرواتب والمالية',

    blog_title_sgk_tavan: 'الحد الأعلى والأدنى للضمان الاجتماعي 2026: الجدول المحدث والحساب',
    blog_desc_sgk_tavan: 'جدول الحد الأعلى لأقساط وأجور SGK 2026. نقاط يجب مراعاتها في أقساط صاحب العمل والموظف.',
    blog_meta_sgk_tavan: '27 أبريل 2026 • الرواتب والمالية',

    blog_title_bordro_secim: 'كيف تختار برنامج الرواتب؟ دليل المشتري 2026',
    blog_desc_bordro_secim: 'ما الذي يجب الانتباه إليه عند اختيار برنامج الرواتب المناسب في 2026؟ دليل شامل ومعايير.',
    blog_meta_bordro_secim: '27 أبريل 2026 • برامج الرواتب',

    blog_title_ik_karsilastirma: 'مقارنة برامج الموارد البشرية 2026: أفضل المنصات في تركيا',
    blog_desc_ik_karsilastirma: 'مقارنة أفضل برامج الموارد البشرية في السوق التركية والميزات ونماذج التسعير.',
    blog_meta_ik_karsilastirma: '27 أبريل 2026 • برامج الموارد البشرية',

    blog_title_ik_secim: 'دليل اختيار برنامج الموارد البشرية 2026: 12 معياراً حاسماً',
    blog_desc_ik_secim: '12 معياراً حاسماً وطريقة تقييم يجب مراعاتها عند اختيار برنامج الموارد البشرية.',
    blog_meta_ik_secim: '26 مايو 2026 • برامج الموارد البشرية',

    blog_title_personel_takip: 'ما هو برنامج تتبع الموظفين؟ خطة الانتقال من Excel',
    blog_desc_personel_takip: 'ما هو برنامج تتبع الموظفين (PDKS) وما هي ميزاته؟ خارطة طريق خطوة بخطوة للانتقال من Excel إلى PDKS السحابي وتحليل التكلفة والعائد.',
    blog_meta_personel_takip: '27 مايو 2026 • مقال الموارد البشرية',

    blog_title_ats_kontrol: 'قائمة مراجعة برنامج التوظيف (ATS)',
    blog_desc_ats_kontrol: 'قائمة مراجعة مفصلة يمكن استخدامها في عملية اختيار برنامج التوظيف (ATS).',
    blog_meta_ats_kontrol: '28 مايو 2026 • التوظيف وATS',

    blog_title_ik_kpi: '12 مؤشر أداء رئيسي لتحليلات الموارد البشرية يجب تتبعها',
    blog_desc_ik_kpi: '12 مؤشر أداء رئيسي أساسي لتحليلات الموارد البشرية وكيفية حسابها.',
    blog_meta_ik_kpi: '29 مايو 2026 • تحليلات الموارد البشرية',

    blog_title_ik_roi: 'صيغة حساب عائد استثمار الموارد البشرية: قياس عائد الاستثمار',
    blog_desc_ik_roi: 'منهجية حساب عوائد الاستثمارات في برامج وأنظمة الموارد البشرية.',
    blog_meta_ik_roi: '30 مايو 2026 • استثمارات الموارد البشرية',

    blog_title_pdks_secim: 'ما يجب مراعاته عند اختيار برنامج PDKS',
    blog_desc_pdks_secim: 'ما الذي يجب الانتباه إليه عند اختيار برنامج PDKS؟',
    blog_meta_pdks_secim: '31 مايو 2026 • إدارة الأداء',

    blog_title_bordro_entegrasyon: 'قائمة تكامل برنامج الرواتب: المحاسبة + الموارد البشرية',
    blog_desc_bordro_entegrasyon: 'ما التكاملات التي يمكن إجراؤها بين برنامج الرواتب والمحاسبة والأنظمة الأخرى؟',
    blog_meta_bordro_entegrasyon: '01 يونيو 2026 • برامج الرواتب',

    blog_title_ucret_degerlendirme: 'كيفية هيكلة عملية تقييم الرواتب؟',
    blog_desc_ucret_degerlendirme: 'نهج منهجي يجمع بيانات السوق ونتائج الأداء والتوازن الداخلي لهيكلة عملية تقييم رواتب عادلة ومستدامة.',
    blog_meta_ucret_degerlendirme: '02 يونيو 2026 • مقال الموارد البشرية',

    blog_title_izin_hatalari: 'أكثر 10 أخطاء شيوعاً في إدارة الإجازات',
    blog_desc_izin_hatalari: 'أكثر 10 أخطاء شيوعاً في إدارة الإجازات وكيفية تجنبها.',
    blog_meta_izin_hatalari: '03 يونيو 2026 • إدارة الإجازات',

    blog_title_puantaj: 'تحسين الدوام والورديات: 5 سيناريوهات عملية',
    blog_desc_puantaj: '5 سيناريوهات تحسين عملية وأمثلة تطبيقية لزيادة دقة تتبع الدوام ومنع تسرب العمل الإضافي في فرق العمل بنظام الورديات.',
    blog_meta_puantaj: '04 يونيو 2026 • مقال الموارد البشرية',

    blog_title_kobi: 'برنامج الموارد البشرية للشركات الصغيرة والمتوسطة: من أين تبدأ؟',
    blog_desc_kobi: 'من أين تبدأ برنامج الموارد البشرية للشركات الصغيرة والمتوسطة؟',
    blog_meta_kobi: '05 يونيو 2026 • دليل الشركات الصغيرة',

    blog_title_kpi_ise_alim: 'إدارة مؤشرات الأداء في عملية التوظيف: من وقت التوظيف إلى معدل العروض',
    blog_desc_kpi_ise_alim: 'مقاييس مهمة مثل وقت التوظيف ومعدل العروض ومعدل القبول لإدارة عملية التوظيف.',
    blog_meta_kpi_ise_alim: '06 يونيو 2026 • التوظيف وATS',

    blog_title_performans_okr: 'استخدام إدارة الأداء ونموذج OKR معاً',
    blog_desc_performans_okr: 'كيف توائم المساهمة الفردية مع أهداف الشركة باستخدام إدارة الأداء ونموذج OKR معاً؟ تصميم نموذج هجين متوافق.',
    blog_meta_performans_okr: '07 يونيو 2026 • مقال الموارد البشرية',

    blog_title_ozluk_donus: 'كيفية حساب مدة العائد عند الانتقال إلى نظام الملف الرقمي؟',
    blog_desc_ozluk_donus: 'كيف يجب حساب مدة العائد (ROI) عند الانتقال إلى نظام الملف الوظيفي الرقمي؟',
    blog_meta_ozluk_donus: '08 يونيو 2026 • التحول الرقمي',

    blog_title_fiyatlama: 'نماذج تسعير برامج الموارد البشرية',
    blog_desc_fiyatlama: 'نماذج تسعير برامج الموارد البشرية: مقارنة شاملة لنماذج التسعير لكل مستخدم ولكل وحدة والمتدرجة والثابتة مع المزايا والعيوب.',
    blog_meta_fiyatlama: '09 يونيو 2026 • مقال الموارد البشرية',

    blog_title_global_lokal: 'قرار الحل العالمي مقابل المحلي في اختيار برنامج الموارد البشرية',
    blog_desc_global_lokal: 'برنامج موارد بشرية عالمي أم حل محلي؟ دليل القرار على محاور التوافق التشريعي والدعم اللغوي وسهولة التكامل والتكلفة الإجمالية للملكية.',
    blog_meta_global_lokal: '10 يونيو 2026 • مقال الموارد البشرية',

    blog_title_personel_kurulum: 'دليل تثبيت برنامج تتبع الموظفين (خطوة بخطوة)',
    blog_desc_personel_kurulum: 'دليل عملي خطوة بخطوة لتثبيت برنامج تتبع الموظفين من الصفر إلى التشغيل يمكن لفرق تقنية المعلومات والموارد البشرية متابعته معاً.',
    blog_meta_personel_kurulum: '11 يونيو 2026 • مقال الموارد البشرية',

    blog_title_dashboard: 'تصميم لوحة تقارير الموارد البشرية: ما البيانات التي يجب تقديمها للمدير؟',
    blog_desc_dashboard: 'كيف يجب تصميم لوحة تقارير الموارد البشرية الفعالة؟',
    blog_meta_dashboard: '12 يونيو 2026 • تحليلات الموارد البشرية',

    blog_title_ucret_adalet: 'عدالة الرواتب والتحليلات: من أين تبدأ؟',
    blog_desc_ucret_adalet: 'نهج تحليلي لتحقيق عدالة الرواتب: إنشاء سياسة رواتب شفافة بدمج التوازن الداخلي ومعايير السوق وبيانات الأداء.',
    blog_meta_ucret_adalet: '13 يونيو 2026 • مقال الموارد البشرية',

    blog_title_roi_senaryo: 'حساب عائد استثمار الموارد البشرية: 5 سيناريوهات نموذجية',
    blog_desc_roi_senaryo: 'احسب عائد استثمار الموارد البشرية من 5 قطاعات مختلفة بسيناريوهات حقيقية: التجزئة والتصنيع والتكنولوجيا والصحة والخدمات اللوجستية.',
    blog_meta_roi_senaryo: '14 يونيو 2026 • مقال الموارد البشرية',

    blog_title_pdks_bordro: 'تكامل PDKS مع الرواتب: تقليل التسرب في التكاليف',
    blog_desc_pdks_bordro: 'كيف يجب إنشاء التكامل بين برنامج تتبع الموظفين وبرنامج الرواتب؟',
    blog_meta_pdks_bordro: '15 يونيو 2026 • تكامل الأنظمة',

    blog_title_aday_deneyim: 'كيفية تحسين تجربة المرشح في برنامج التوظيف',
    blog_desc_aday_deneyim: 'أفضل الممارسات الواجب اتباعها في برنامج ATS لتحسين تجربة المرشح.',
    blog_meta_aday_deneyim: '16 يونيو 2026 • التوظيف وATS',

    blog_title_kvkk_kontrol: 'قائمة مراجعة KVKK لبرامج الموارد البشرية',
    blog_desc_kvkk_kontrol: 'قائمة مراجعة التوافق مع KVKK لبرامج الموارد البشرية: دليل كامل يشمل جرد البيانات وإدارة الموافقة الصريحة ومدد الاحتفاظ وتسجيل VERBİS.',
    blog_meta_kvkk_kontrol: '17 يونيو 2026 • مقال الموارد البشرية',

    blog_title_90_gun: 'تقويم تطبيق برنامج الموارد البشرية: الانتقال للتشغيل في 90 يوماً',
    blog_desc_90_gun: 'خارطة طريق مرحلية لتشغيل برنامج الموارد البشرية في 90 يوماً: التقويم الكامل لخطوات الاستكشاف والتثبيت ونقل البيانات والاختبار والتدريب والتشغيل.',
    blog_meta_90_gun: '18 يونيو 2026 • مقال الموارد البشرية',

    blog_title_tco: 'حساب تكلفة برنامج الموارد البشرية: نهج التكلفة الإجمالية للملكية',
    blog_desc_tco: 'احسب التكلفة الإجمالية للملكية (TCO) لبرنامج الموارد البشرية: نموذج تخطيط الميزانية الذي يشمل بنود الترخيص والتنفيذ والتدريب والصيانة والتكاليف الخفية.',
    blog_meta_tco: '19 يونيو 2026 • مقال الموارد البشرية',

    blog_title_performans_prim: 'مواءمة إدارة الأداء مع نموذج المكافآت',
    blog_desc_performans_prim: 'نموذج مكافآت شفاف قائم على التسجيل والترجيح والأهداف لربط نتائج تقييم الأداء بنظام المكافآت بشكل عادل.',
    blog_meta_performans_prim: '20 يونيو 2026 • مقال الموارد البشرية',

    blog_title_piyasa: 'تقييم الرواتب والمقارنة بالسوق',
    blog_desc_piyasa: 'الخطوات الأساسية ومصادر البيانات لإنشاء سلم رواتب تنافسي وعادل من خلال المقارنة بمتوسطات القطاع في عملية تقييم الرواتب.',
    blog_meta_piyasa: '21 يونيو 2026 • مقال الموارد البشرية',

    blog_title_raporlama_hata: 'الأخطاء الشائعة في تقارير تحليلات الموارد البشرية',
    blog_desc_raporlama_hata: 'أكثر الأخطاء شيوعاً في تقارير الموارد البشرية: اختيار خاطئ لمؤشرات الأداء وبيانات غير محدثة وتجزئة ناقصة ولوحات لا تتحول إلى إجراءات.',
    blog_meta_raporlama_hata: '22 يونيو 2026 • مقال الموارد البشرية',

    blog_title_pdks_uzaktan: 'PDKS وإدارة العمل عن بعد',
    blog_desc_pdks_uzaktan: 'الإدارة المتكاملة لتتبع الدخول والخروج والتحقق من الدوام عبر الإنترنت واستراتيجيات تتبع الدوام المبنية على الموقع الجغرافي في فرق العمل عن بعد باستخدام PDKS.',
    blog_meta_pdks_uzaktan: '23 يونيو 2026 • مقال الموارد البشرية',

    blog_title_trendler: 'اتجاهات برامج الموارد البشرية 2026: ما الذي يتغير؟',
    blog_desc_trendler: 'الاتجاهات التي تشكل عالم برامج الموارد البشرية في 2026: الذكاء الاصطناعي التوليدي ومنصات تجربة الموظف والتنظيم القائم على المهارات ولوائح خصوصية البيانات.',
    blog_meta_trendler: '24 يونيو 2026 • مقال الموارد البشرية',
  };
