window.CADRO_TR_tr = {
    // GENEL SEO METİNLERİ
    meta_title_index: 'CADRO | Modern İnsan Kaynakları Yazılımı ve Yönetim Sistemi',
    meta_desc_index: 'Kağıt işlerine veda edin. CADRO; işe alım, performans, izin ve özlük yönetimini tek bir bulut platformunda toplayan modern İK yazılımıdır.',
    meta_keywords_index: 'insan kaynakları yazılımı, ik yazılımı, bulut ik sistemi, insan kaynakları otomasyonu, hrm, hrms',
    // ARAÇLAR SAYFASI
    meta_title_araclar: 'Ücretsiz İK Hesaplama Araçları | CADRO',
    meta_desc_araclar: 'CADRO\'nun ücretsiz İK hesaplama araçları: Asgari ücret, bordro maliyeti, kıdem tazminatı, SGK primi ve daha fazlası. İK profesyonelleri için tasarlandı.',
    meta_keywords_araclar: 'ik hesaplama araçları, bordro hesaplama, asgari ücret hesaplama, kıdem tazminatı, sgk primi hesaplama, ücretsiz ik araçları',
    tools_eyebrow: 'ÜCRETSİZ ARAÇLAR',
    tools_title: 'İK Profesyonelleri İçin Hesaplama Araçları',
    tools_text: 'Asgari ücret, bordro maliyeti, kıdem tazminatı ve daha fazlası için ücretsiz hesaplama araçları. İK operasyonlarınızı hızlandırın.',
    tools_calc_title: 'Hesaplama Araçları',
    tools_calc_text: 'İK ve bordro süreçlerinizde ihtiyaç duyduğunuz tüm hesaplamaları ücretsiz yapın.',
    tools_analytic_title: 'Analitik Araçlar',
    tools_analytic_text: 'İK verilerinizi analiz edin, ücret yapınızı optimize edin ve operasyonel görünürlüğü artırın.',
    tool_badge_popular: 'En Popüler',
    tool_badge_new: 'Yeni',
    tool_1_title: 'Asgari Ücret Hesaplama',
    tool_1_text: '2026 asgari ücret net ve brüt tutarını, işveren maliyetini ve SGK primlerini anında hesaplayın.',
    tool_2_title: 'Bordro Maliyet Hesaplama',
    tool_2_text: 'Çalışan başına toplam bordro maliyetini, SGK işveren payı ve tüm yasal kesintilerle birlikte görün.',
    tool_3_title: 'Kıdem Tazminatı Hesaplama',
    tool_3_text: 'Çalışanın kıdem süresine göre hak ettiği kıdem ve ihbar tazminatı tutarını hesaplayın.',
    tool_4_title: 'SGK Prim Hesaplama',
    tool_4_text: 'SGK işveren primini, tavan ve taban limitleriyle birlikte güncel oranlar üzerinden hesaplayın.',
    tool_5_title: 'Net-Brüt Maaş Hesaplama',
    tool_5_text: 'Netten brüte veya brütten nete maaş dönüşümünü tüm vergi ve SGK kesintileriyle hesaplayın.',
    tool_6_title: 'İK ROI Hesaplama',
    tool_6_text: 'İK yazılımı yatırımınızın geri dönüş süresini örnek senaryolarla anında görün.',
    tool_7_title: 'İK Analitiği',
    tool_7_text: 'Turnover, işe alım KPI ve iş gücü maliyetlerini tek ekranda izleyin.',
    tool_8_title: 'Ücret Değerlendirme',
    tool_8_text: 'Maaş bantları, piyasa kıyasları ve ücret adaleti analizlerini yönetin.',
    tool_9_title: 'PDKS',
    tool_9_text: 'Puantaj, devam ve vardiya akışlarını bordroya hazır biçimde yönetin.',
    tool_cta_calc: 'Hesapla →',
    tool_cta_open: 'Aç →',
    tool_cta_view_all: 'Tüm Araçları Gör →',
    // FAQ SORU-CEVAPLARI (JSON-LD FAQPage için)
    faq_question_1: 'CADRO hangi İK süreçlerini kapsar?',
    faq_answer_1: 'CADRO; e-özlük, puantaj, izin yönetimi, masraf ve satın alma talepleri, aday takip sistemi (ATS), performans yönetimi (OKR) süreçlerini kapsayan bulut tabanlı bir İK platformudur.',
    faq_question_2: 'Mevcut personel verilerimi sisteme aktarabilir miyim?',
    faq_answer_2: 'Evet. Gelişmiş Excel içe aktarma araçlarımız sayesinde mevcut çalışan listelerinizi ve geçmiş izin bakiyelerinizi dakikalar içinde CADRO\'ya aktarabilirsiniz.',
    faq_question_3: 'CADRO KVKK uyumlu mu?',
    faq_answer_3: 'Kesinlikle. Platformumuz üst düzey şifreleme ve gelişmiş yetkilendirme altyapısı ile tam KVKK uyumlu dijital arşivleme sağlar.',
    faq_question_4: 'CADRO KOBİ\'ler için uygun mu?',
    faq_answer_4: 'Evet. CADRO 10 kişilik startup\'lardan 1.000+ çalışanlı kurumsal firmalara kadar ölçeklenen modüler yapıdadır. Basic planla başlayıp ihtiyaç büyüdükçe Pro veya Enterprise\'a geçebilirsiniz.',
    faq_question_5: 'CADRO Excel ile nasıl karşılaştırılır?',
    faq_answer_5: 'Excel; manuel güncelleme, hata riski ve erişim kısıtlamaları nedeniyle büyüyen ekiplerde yetersiz kalır. CADRO; otomatik onay akışları, gerçek zamanlı raporlama ve mobil erişim sunar. Detaylı karşılaştırma için Excel vs CADRO sayfamızı inceleyebilirsiniz.',
    faq_question_6: 'CADRO\'nun ücretsiz deneme süreci nasıl işliyor?',
    faq_answer_6: 'Kredi kartı gerektirmeden CADRO\'yu denemeye başlayabilirsiniz. Deneme süresince tüm Pro modüllere erişebilir, ekibinizi davet edebilir ve verilerinizi sisteme aktarabilirsiniz.',
    // OFFER AÇIKLAMALARI (JSON-LD SoftwareApplication için)
    offer_basic_desc: 'Temel İK modülleri: özlük, izin, puantaj',
    offer_pro_desc: 'Tüm modüller: ATS, performans, OKR, masraf ve tam entegrasyon',
    meta_title_pay: 'CADRO | Güvenli Ödeme',
    home_quicklinks_eyebrow: 'Hızlı Erişim',
    home_quicklinks_title: 'CADRO modüllerini ihtiyaç alanına göre keşfedin',
    home_quicklinks_text: 'Ana sayfadan kritik ürün sayfalarına daha hızlı geçin ve her modülün kullanım alanını net biçimde inceleyin.',
    home_quicklink_1_title: 'Aday Takip Sistemi',
    home_quicklink_1_text: 'Başvuru havuzu, ilan yönetimi ve işe alım akışını tek yapı içinde yönetin.',
    home_quicklink_1_cta: 'ATS sayfasını incele',
    home_quicklink_2_title: 'Dijital Özlük ve İzin',
    home_quicklink_2_text: 'Çalışan belgeleri, izin onayları ve özlük takibini merkezi hale getirin.',
    home_quicklink_2_cta: 'Özlük ve izin sayfasını incele',
    home_quicklink_3_title: 'Puantaj ve Vardiya',
    home_quicklink_3_text: 'Mesai, puantaj ve vardiya planlamasını bordroya hazır hale getirin.',
    home_quicklink_3_cta: 'Puantaj sayfasını incele',
    home_quicklink_4_title: 'Performans ve OKR',
    home_quicklink_4_text: 'Hedefler, geri bildirim ve performans takibini stratejik görünürlükle yönetin.',
    home_quicklink_4_cta: 'Performans sayfasını incele',
    home_quicklink_5_title: 'Masraf ve Satın Alma',
    home_quicklink_5_text: 'Masraf, satın alma ve onay akışlarını finans disipliniyle yönetin.',
    home_quicklink_5_cta: 'Finans operasyonları sayfasını incele',
    home_quicklink_6_title: 'Bilgi Bankası ve İşe Giriş',
    home_quicklink_6_text: 'Kurumsal hafıza, politika yönetimi ve işe giriş akışlarını yapılandırın.',
    home_quicklink_6_cta: 'Bilgi bankası sayfasını incele',
    meta_desc_pay: 'CADRO güvenli ödeme ve abonelik sayfası.',
    meta_title_security: 'İK Verisi ve Erişim Güvenliği | CADRO',
    meta_desc_security: 'Rol bazlı erişim, parola ve oturum güvenliği, denetim izi ve yönetsel kontrol katmanları ile İK verisini daha güvenli yönetin.',
    meta_title_architecture: 'CADRO | Mimari',
    meta_desc_architecture: 'Bulut tabanlı, ölçeklenebilir CADRO mimarisi ve performans katmanları.',
    meta_title_compliance: 'İK Uyumluluk ve KVKK Süreç Yönetimi | CADRO',
    meta_desc_compliance: 'Çalışan doküman uyumu, politika onay akışları ve dijital özlük görünürlüğünü tek merkezde yönetin. CADRO ile İK uyumluluk süreçlerini daha kontrollü hale getirin.',
    meta_title_privacy: 'CADRO | Gizlilik Politikası',
    meta_title_terms: 'CADRO | Kullanım Şartları',
    meta_title_refund: 'CADRO | İade Politikası',
    'meta_title_ats-ise-alim-yazilimi': 'Aday Takip Sistemi (ATS) ve İşe Alım Yazılımı | CADRO İKYS',
    'meta_desc_ats-ise-alim-yazilimi': 'Aday takip sistemi ile başvuruları tek ekranda yönetin, CV havuzu oluşturun, mülakat süreçlerini hızlandırın ve işe alım operasyonunu dijitalleştirin.',
    meta_title_blog: 'CADRO Blog | İnsan Kaynakları, Yapay Zeka ve Liderlik Trendleri',
    meta_title_faq: 'CADRO Sıkça Sorulan Sorular | İK Yazılımı Hakkında Merak Edilenler',
    meta_desc_faq: 'CADRO fiyatlandırma, modüller, güvenlik, destek ve entegrasyon süreçleri hakkında en çok sorulan sorular.',
    'meta_title_vaka-calismalari': 'CADRO Vaka Çalışmaları | Müşteri Başarı Hikayeleri',
    'meta_desc_vaka-calismalari': 'Gerçek sektör örnekleriyle CADRO kullanım sonuçlarını ve operasyonel kazanımları inceleyin.',
    'meta_title_vaka-calismasi-tech-startup': 'Teknoloji Girişimi Vaka Çalışması | 50’den 250’ye Kontrollü Büyüme | CADRO',
    'meta_desc_vaka-calismasi-tech-startup': 'Hızlı büyüyen ekiplerde işe alım standardı, aday görünürlüğü ve işe giriş temposunun nasıl güçlendiğini inceleyin.',
    'meta_title_vaka-calismasi-perakende': 'Perakende Vaka Çalışması | 2000+ Çalışanda Puantaj Standartlaşması | CADRO',
    'meta_desc_vaka-calismasi-perakende': 'Çok lokasyonlu perakende yapılarında puantaj, vardiya ve izin görünürlüğünün nasıl merkezileştiğini görün.',
    'meta_title_vaka-calismasi-uretim-devi': 'Üretim Vaka Çalışması | Çok Katmanlı Operasyonda Tasarruf ve Kontrol | CADRO',
    'meta_desc_vaka-calismasi-uretim-devi': 'Üretim tesislerinde çok katmanlı çalışan yapısında doküman, vardiya ve iç talep süreçlerinin nasıl sadeleştiğini görün.',
    'meta_title_vaka-calismasi-saglik': 'Sağlık Vaka Çalışması | Doküman Uyumu ve Performans Görünürlüğü | CADRO',
    'meta_desc_vaka-calismasi-saglik': 'Sağlık operasyonlarında belge uyumu, eğitim takibi ve performans görünürlüğünün nasıl güçlendiğini inceleyin.',
    'meta_title_vaka-calismasi-egitim': 'Eğitim Vaka Çalışması | Öğretmen Performansı ve Gelişim Takibi | CADRO',
    'meta_desc_vaka-calismasi-egitim': 'Eğitim kurumlarında performans, gelişim ve kurumsal öğrenme takibinin nasıl daha görünür hale geldiğini inceleyin.',
    'meta_title_vaka-calismasi-lojistik': 'Lojistik Vaka Çalışması | Vardiya ve Saha Görünürlüğü | CADRO',
    'meta_desc_vaka-calismasi-lojistik': 'Saha ekipleri yoğun olan lojistik yapılarda vardiya, lokasyon ve devam görünürlüğünün nasıl merkezileştiğini görün.',
    'meta_title_vaka-calismasi-danismanlik': 'Danışmanlık Vaka Çalışması | Uzman Yönetimi ve Operasyon Standardı | CADRO',
    'meta_desc_vaka-calismasi-danismanlik': 'Uzman kapasitesi hızla artan danışmanlık yapılarında görünürlük, süreç standardı ve operasyonel disiplinin nasıl güçlendiğini görün.',

    meta_desc_privacy: 'CADRO gizlilik politikası, veri işleme ilkeleri ve kullanıcı verilerinin korunması hakkında temel bilgiler.',
    meta_desc_terms: 'CADRO hizmet kullanım şartları ve erişim kurallarına ilişkin temel sözleşmesel çerçeve.',
    meta_desc_refund: 'CADRO abonelik iptali, iade ve faturalama incelemeleri için geçerli politika çerçevesi.',
    meta_desc_blog: 'CHRO ve İK profesyonelleri için en güncel yönetim trendleri, Yapay Zeka (AI) stratejileri ve takım yönetimi makaleleri.',
    'meta_title_dijital-ozluk-ve-izin': 'Dijital Özlük Dosyası ve İzin Yönetimi Yazılımı | CADRO',
    'meta_desc_dijital-ozluk-ve-izin': 'Dijital özlük dosyası, çalışan belge yönetimi ve izin onay süreçlerini tek platformda yönetin. Eksik evrak ve uyum takibini kolaylaştırın.',
    'meta_title_excel-vs-cadro': 'İK Süreçlerinde Excel vs CADRO | Neden Excel Kullanmamalısınız?',
    'meta_desc_excel-vs-cadro': 'İnsan kaynakları yönetiminde Excel tablolarının riskleri nelerdir? CADRO İK yazılımının otomasyon avantajları ile zaman ve maliyet tasarrufu sağlayın.',
    'meta_title_ik-sozlugu': 'İnsan Kaynakları (İK) Sözlüğü ve Terimleri | CADRO',
    'meta_desc_ik-sozlugu': 'İK dünyasındaki karmaşık kavramların en net ve güncel tanımları. Puantaj, OKR, Turnover, eNPS ve daha fazlası CADRO İK Sözlüğü\'nde.',
    'meta_title_ik-yazilimi': 'İnsan Kaynakları (İK) Yazılımı Nedir? | CADRO',
    'meta_desc_ik-yazilimi': 'İK yazılımı nedir ve hangi modülleri kapsar? CADRO ile işe alım, özlük, izin, performans ve bordroyu tek platformda yönetin.',
    'meta_title_kurumsal-bilgi-bankasi-ve-onboarding': 'Kurumsal Bilgi Bankası ve İşe Giriş Yazılımı | CADRO',
    'meta_desc_kurumsal-bilgi-bankasi-ve-onboarding': 'Politika yönetimi, çalışan okundu onayı ve işe giriş görev akışlarını tek merkezde yönetin. CADRO ile kurumsal bilgi dağıtımını ve uyum sürecini standartlaştırın.',
    'meta_title_masraf-ve-satin-alma': 'Masraf ve Satın Alma Talep Yönetimi | CADRO',
    'meta_desc_masraf-ve-satin-alma': 'Kontrolsüz harcamaları ve gizli bütçe sapmalarını durdurun. CFO\'lar için tasarlanmış dijital onay akışları ve şeffaf satın alma yönetim sistemi.',
    'meta_title_performans-degerlendirme-okr': 'Performans Yönetimi ve OKR Yazılımı | 360 Değerlendirme | CADRO',
    'meta_desc_performans-degerlendirme-okr': 'Performans yönetimi, 360 derece değerlendirme ve OKR takibini tek platformda yönetin. Hedef, geri bildirim ve yetenek gelişimini dijitalleştirin.',
    'meta_title_puantaj-ve-vardiya-yazilimi': 'Akıllı Puantaj, Mesai ve Vardiya Yönetim Yazılımı | CADRO',
    'meta_desc_puantaj-ve-vardiya-yazilimi': 'Bordro sızıntılarını ve yasal riskleri sıfırlayın. CFO ve CHRO\'lar için tasarlanmış, sıfır hatalı akıllı puantaj ve dinamik vardiya yönetim sistemi.',
    'meta_title_ucretsiz-sablonlar': 'Ücretsiz İK Şablonları, Excel ve Formlar | CADRO',
    'meta_desc_ucretsiz-sablonlar': 'İnsan kaynakları süreçlerinizi hızlandıracak ücretsiz işe giriş şablonları, performans değerlendirme formları ve Excel tablolarını hemen indirin.',
    'meta_title_makale-yapay-zeka-genai': 'Üretken Yapay Zeka (GenAI) ile İK Operasyonlarında Haftalık 15 Saat Tasarruf | CADRO Blog',
    'meta_desc_makale-yapay-zeka-genai': 'İnsan kaynakları departmanlarında üretken yapay zeka kullanarak işe alım, performans değerlendirme ve işe giriş süreçlerinde nasıl haftalık 15 saat tasarruf edilir?',
    'meta_title_makale-prediktif-ik': 'Prediktif İK: Kimin İstifa Edeceğini Önceden Bilmek | CADRO',
    'meta_desc_makale-prediktif-ik': 'Prediktif analitikle istifa riskini erken tespit edin ve veri odaklı önlemler alın.',
    'meta_title_makale-ise-alimda-ai-etik': 'İşe Alımda Yapay Zeka: Önyargıları Yok Etmek | CADRO',
    'meta_desc_makale-ise-alimda-ai-etik': 'İşe alımda yapay zekanın etik riskleri, bias ve sorumlu kullanım ilkeleri.',
    'meta_title_makale-ai-ve-kvkk-uyumu': 'AI vs KVKK İkilemi | CADRO',
    'meta_desc_makale-ai-ve-kvkk-uyumu': 'Yapay zeka ile çalışan verilerini işlerken KVKK uyumu ve hukuki risk yönetimi.',
    'meta_title_makale-sessiz-istifa-maliyeti': 'Sessiz İstifa Şirketinize Ne Kadar Mal Oluyor? | CADRO',
    'meta_desc_makale-sessiz-istifa-maliyeti': 'Sessiz istifanın bağlılık, verimlilik ve OPEX üzerindeki gizli maliyeti.',
    'meta_title_makale-ik-dijital-donusum-2026': '2026 İK Dijital Dönüşüm Rehberi | CADRO',
    'meta_desc_makale-ik-dijital-donusum-2026': '2026 için İK dijital dönüşüm yol haritası, ROI ve liderlik öncelikleri.',
    'meta_title_makale-turnover-dusurme-yollari': 'Turnover Oranını Düşürmenin Veri Odaklı Yolları | CADRO',
    'meta_desc_makale-turnover-dusurme-yollari': 'Turnover oranını düşürmek için veri odaklı 5 strateji.',
    'meta_title_makale-yillik-performans-degerlendirme': 'Yıllık Performans Görüşmelerinin Sonu Geldi mi? | CADRO',
    'meta_desc_makale-yillik-performans-degerlendirme': 'Yıllık performans görüşmelerinin neden yetersiz kaldığı ve modern alternatifler.',
    'meta_title_makale-dijital-ozluk-ve-kvkk': 'Dijital Özlük Dosyası ve KVKK Denetimleri | CADRO',
    'meta_desc_makale-dijital-ozluk-ve-kvkk': 'Dijital özlük dosyasında KVKK denetimleri ve elektronik arşivin hukuki geçerliliği.',
    'meta_title_makale-excel-bordro-sizintilari': 'Bordro Sızıntıları: Excel ile Puantajın Acı Bedeli | CADRO',
    'meta_desc_makale-excel-bordro-sizintilari': 'Excel ile puantajın neden bordro sızıntılarına yol açtığı ve maliyet etkileri.',
    
    // META KEYWORDS (TÜM SAYFALAR)
    meta_keywords_pay: 'cadro ödeme, ik yazılımı abonelik, hrm ödeme',
    meta_keywords_security: 'ik yazılımı güvenlik, veri güvenliği, bulut güvenlik, iso 27001, kvkk uyum',
    meta_keywords_architecture: 'ik yazılımı mimari, bulut mimari, microservice, hrm altyapısı',
    meta_keywords_compliance: 'kvkk uyumu, veri gizliliği, ik yazılımı yasal uyum, kişisel veri koruma',
    meta_keywords_privacy: 'cadro gizlilik politikası, kvkk, veri koruma',
    meta_keywords_terms: 'cadro kullanım şartları, hizmet koşulları',
    meta_keywords_refund: 'cadro iade, abonelik iptal, para iadesi',
    'meta_keywords_ats-ise-alim-yazilimi': 'ats yazılımı, işe alım sistemi, aday takip sistemi, recruitment software, applicant tracking',
    'meta_keywords_blog': 'ik blog, insan kaynakları blog, hrm makaleleri, ik yazılımı rehberi',
    'meta_keywords_faq': 'ik yazılımı sss, hrm sık sorulan sorular, cadro yardım, sıkça sorulan sorular',
    'meta_keywords_vaka-calismalari': 'ik yazılımı vaka çalışmaları, başarı hikayeleri, hrm referans, cadro müşteri',
    'meta_keywords_dijital-ozluk-ve-izin': 'dijital özlük, izin yönetimi, personel dosyası, e-özlük, digital personnel file',
    'meta_keywords_excel-vs-cadro': 'excel vs ik yazılımı, excelden hrm geçiş, ik yazılımı karşılaştırma',
    'meta_keywords_ik-sozlugu': 'ik sözlüğü, insan kaynakları terimleri, hr glossary, ik kavramları',
    'meta_keywords_ik-yazilimi': 'ik yazılımı, insan kaynakları yazılımı, hrm yazılımı, hrms sistemi, ik otomasyonu',
    'meta_keywords_kurumsal-bilgi-bankasi-ve-onboarding': 'kurumsal bilgi bankası, onboarding, işe alıştırma, oryantasyon, knowledge base',
    'meta_keywords_masraf-ve-satin-alma': 'masraf yönetimi, satın alma süreci, gider takibi, expense management',
    'meta_keywords_performans-degerlendirme-okr': 'performans yönetimi, okr hedef yönetimi, çalışan değerlendirme, performance management',
    'meta_keywords_puantaj-ve-vardiya-yazilimi': 'puantaj yazılımı, vardiya takip, zaman yönetimi, personel devam takip, time tracking',
    'meta_keywords_ucretsiz-sablonlar': 'ücretsiz ik şablonları, hrm şablon, excel şablon, ik dokümanları',
    'meta_keywords_mobil-uygulama': 'mobil ik uygulaması, mobil hrm, mobil personel yönetimi, mobile hr app',
    'meta_keywords_pricing': 'ik yazılımı fiyatları, hrms fiyatlandırma, insan kaynakları yazılımı ücretleri, cadro fiyat',
    'meta_keywords_ik-analitigi': 'ik analitiği, hr analytics, insan kaynakları raporlama, personel veri analizi',
    'meta_keywords_bordro-yazilimi': 'bordro yazılımı, maaş programı, ücret hesaplama, bordro otomasyonu, payroll software',
    'meta_keywords_ik-roi-hesaplama': 'ik roi hesaplama, hr roi, insan kaynakları yatırım getirisi, ik maliyet hesabı',
    'meta_keywords_pdks': 'pdks, personel devam kontrol, parmak izi okuyucu, geçiş kontrol, biometric attendance',
    'meta_keywords_ucret-degerlendirme': 'ücret değerlendirme, maaş belirleme, ücret skalası, compensation evaluation',
    'meta_keywords_ik-arastirma-raporu-2026': 'ik araştırma raporu, insan kaynakları trendleri, hrm rapor 2026',
    'meta_keywords_asgari-ucret-hesaplama': 'asgari ücret hesaplama, net brüt maaş, 2026 asgari ücret, asgari ücret hesabı',
    'meta_keywords_kidem-tazminati-hesaplama': 'kıdem tazminatı hesaplama, ihbar tazminatı, kıdem hesabı 2026, severance',
    'meta_keywords_bordro-maliyet-hesaplama': 'bordro maliyeti hesaplama, işveren maliyet hesabı, bordro gider, payroll cost',
    'meta_keywords_sgk-prim-hesaplama': 'sgk primi hesaplama, işveren maliyeti, sgk tavan taban, sigorta primi',
    'meta_keywords_net-brut-maas-hesaplama': 'net brüt maaş hesaplama, maaş hesaplama, ücret hesaplama aracı, bordro hesaplama',
    'meta_keywords_watch': 'cadro tanıtım, ik yazılımı demo, hrm videosu, ürün turu',
    'meta_keywords_webinar': 'ik webinar, insan kaynakları seminer, hrm eğitim, online seminer',
    'meta_keywords_tesekkur-sablon-indirme': 'şablon indirme, ik şablon, teşekkür, indirme sayfası',
    'meta_keywords_performans-degerlendirme-formu-sablonu': 'performans değerlendirme formu, performans şablonu, değerlendirme formu',
    'meta_keywords_onboarding-kontrol-listesi-sablonu': 'onboarding kontrol listesi, işe alıştırma şablonu, onboarding template',
    // SEKTÖR SAYFALARI META
    'meta_keywords_ik-yazilimi-restoran': 'restoran ik programı, cafe personel yönetimi, lokanta puantaj sistemi, restoran vardiya',
    'meta_keywords_ik-yazilimi-otel': 'otel ik yazılımı, otel personel takip, konaklama sektörü ik, turizm personel yönetimi',
    'meta_keywords_ik-yazilimi-tekstil': 'tekstil ik programı, hazır giyim personel takip, tekstil puantaj, fabrika vardiya sistemi',
    'meta_keywords_ik-yazilimi-cagri-merkezi': 'çağrı merkezi ik yazılımı, call center personel yönetimi, çağrı merkezi vardiya',
    'meta_keywords_ik-yazilimi-bilisim': 'yazılım şirketi ik programı, teknoloji startup ik, bilişim sektörü insan kaynakları',
    'meta_keywords_ik-yazilimi-egitim': 'okul ik programı, eğitim kurumu personel yönetimi, öğretmen performans takip sistemi',
    'meta_keywords_ik-yazilimi-uretim': 'üretim tesisi ik yazılımı, fabrika personel takip, üretim puantaj sistemi, iş güvenliği takibi',
    'meta_keywords_ik-yazilimi-gida': 'gıda sektörü ik programı, gıda üretimi personel takip, hijyen eğitim sistemi, gıda güvenliği ik',

    // MENÜ VE NAVİGASYON
    nav_software: 'İK Yazılımı',
    nav_solutions: 'Çözümler',
    nav_compare: 'Neden Cadro?',
    nav_pricing: 'Fiyatlar',
    nav_tools: 'Araçlar',
    nav_resources: 'Kaynaklar',
    cta_ats_module: 'ATS Modülünü İncele →',
    cta_performance_module: 'Performans Modülünü İncele →',
    cta_dossier_module: 'Özlük ve İzin Modülünü İncele →',
    cta_timekeeping_module: 'Puantaj Çözümümüzü İnceleyin →',
    cta_excel_compare: 'Detaylı Karşılaştırmayı Oku →',
    cta_hr_glossary: 'İK Sözlüğünü İncele →',
    cta_free_templates: 'Şablonları İndir →',
    cta_blog: 'Blogu Oku →',
    cta_case_studies: 'Vaka Çalışmalarını Gör →',
    nav_home: 'Ana Sayfa',
    nav_all_features: 'Tüm Özellikler',
    nav_blog: 'Blog',
    nav_contact: 'İletişim',
    nav_menu: 'Menü',
    btn_login: 'Giriş Yap',
    btn_payment_page: 'Ödeme Sayfası',
    btn_start_selling: 'Hemen Başla',
    btn_view_plans: 'Planları İncele',
    btn_back_home: 'Ana sayfaya dön',

    // 1. HERO ALANI
    hero_eyebrow: '',
    hero_title: 'Bulut Tabanlı İnsan Kaynakları Yazılımı',
    hero_text: 'İşe alımdan performansa, izinlerden puantaja kadar tüm İK süreçlerinizi tek bulut platformunda yönetin.',
    hero_subtext: 'CADRO, bulut tabanlı insan kaynakları yazılımı ile şirketinizin tüm İK operasyonlarını tek çatı altında toplar.',
    btn_start_subscription: 'Aboneliğinizi Başlatın',
    btn_view_demo: 'Özellikleri Keşfet',
    point_multi_tenant: 'Bulut Tabanlı Mimari',
    point_role_based: 'Gelişmiş Yetkilendirme',
    point_kvkk: 'Tam KVKK Uyumluluğu',
    video_eyebrow: 'Ürün Filmi',
    video_title: 'CADRO\'yu 90 saniyede izleyin',
    video_text: 'Yönetim, operasyon ve çalışan deneyimini tek platformda nasıl birleştirdiğimizi kısa ürün filminde görün.',
    video_point_1_title: 'Tek merkez',
    video_point_1_text: 'İK, operasyon ve finans akışlarını tek görünümde izleyin.',
    video_point_2_title: 'Gerçek akışlar',
    video_point_2_text: 'ATS, puantaj, özlük ve onay süreçlerini aynı anlatıda görün.',
    video_point_3_title: 'Demo öncesi hızlı bakış',
    video_point_3_text: 'Planlara geçmeden önce ürünün ritmini ve kapsamını netleştirin.',

    // HERO METRİKLER (İSTATİSTİKLER)
    metric_modules_label: 'Aktif Modüller',
    metric_modules_text: 'Çekirdek İK, aday takibi, puantaj, e-özlük ve performans.',
    metric_ops_label: 'Hızlı Kurulum',
    metric_ops_value: 'Anında Aktif',
    metric_ops_text: 'Dakikalar içinde kurumunuza özel yapıyı kurun.',
    screen_dashboard_badge_1: 'Akıllı Kokpit',
    screen_dashboard_badge_2: 'Detaylı Analitik',

    // 2. ÇÖZÜMLER (KİME HİTAP EDİYORUZ)
    strip_product_label: 'Startuplar İçin',
    strip_product_text: 'Hızlı büyüyen ekipler için ölçeklenebilir ve modern kültür inşası.',
    strip_who_label: 'KOBİ\'ler İçin',
    strip_who_text: 'Karmaşık yasal süreçleri ve operasyonel yükleri otomatikleştiren yapı.',
    strip_delivery_label: 'Uzaktan Ekipler İçin',
    strip_delivery_text: 'Fiziksel sınırlar olmadan, dijital onaylar ve kesintisiz iletişim.',

    // 3. SHOWCASE (DERİNLEMESİNE ÖZELLİKLER)
    modules_eyebrow: 'ÖZELLİKLERİMİZ',
    showcase_title: 'Her İhtiyacınız İçin Tek Bir Platform',
    showcase_text: 'Farklı araçlar arasında kaybolmayın. CADRO, modern bir İK departmanının ihtiyaç duyduğu tüm modülleri birbiriyle entegre sunar.',
    showcase_1_eyebrow: 'İşe Alım ve ATS',
    showcase_1_title: 'Doğru yeteneği hızla keşfedin.',
    showcase_1_text: 'Kariyer portallarından gelen başvuruları tek ekranda toplayın. Mülakat aşamalarını sürükle-bırak ile yönetin ve adaya otomatik teklif gönderin.',
    showcase_2_eyebrow: 'Performans Yönetimi (OKR)',
    showcase_2_title: 'Sıkıcı yıllık değerlendirmeleri unutun.',
    showcase_2_text: '360 derece geri bildirimler, şeffaf hedef takibi ve yetkinlik matrisi ile çalışanlarınızın gelişimini anlık olarak destekleyin.',
    showcase_3_eyebrow: 'Özlük ve İzin Yönetimi',
    showcase_3_title: 'Kağıt işlerine ve Excel\'e veda edin.',
    showcase_3_text: 'Dijital özlük dosyaları ile KVKK uyumlu arşivleme yapın. Çalışanlar mobilden izin talep etsin, yöneticiler tek tıkla onaylasın.',
    how_it_works_label: 'Nasıl Çalışır?',
    showcase_1_step_1: 'Pozisyon oluştur ve kariyer sayfana yayınla',
    showcase_1_step_2: 'Başvurular otomatik toplanır, aday havuzu oluşur',
    showcase_1_step_3: 'Kanban tahtasında adayı aşama aşama ilerlet',
    showcase_1_step_4: 'Kabul eden aday, tek tıkla personel kartına dönüşür',
    showcase_2_step_1: 'OKR hedefleri şirket, takım ve bireysel düzeyde tanımla',
    showcase_2_step_2: 'Çalışan dönem boyunca hedeflerini günceller',
    showcase_2_step_3: '360° geri bildirim ve AI yetenek analizi tamamlanır',
    showcase_2_step_4: 'Sonuçlar raporlanır, kariyer planlaması şekillenir',
    showcase_3_step_1: 'Her çalışan için dijital özlük kartı oluşturulur',
    showcase_3_step_2: 'Belgeler sisteme yüklenir, eksik evrak otomatik uyarı verir',
    showcase_3_step_3: 'Çalışan mobilden izin talebi gönderir, yönetici bildirim alır',
    showcase_3_step_4: 'Onay sonrası bakiye güncellenir, bordroyla senkronize çalışır',

    // 4. KARŞILAŞTIRMA (EXCEL VS CADRO)
    compare_eyebrow: 'NEDEN CADRO?',
    compare_title: 'Manuel tablolardan kurtulma vakti gelmedi mi?',
    compare_1_title: 'Zaman Kaybı Önlenir',
    compare_1_text: 'Excel\'de uzun süren puantaj hesaplamaları ve formül yükü, CADRO\'nun otomasyonu ile daha hızlı ve daha kontrollü hale gelir.',
    compare_2_title: 'Daha Az Manuel Hata',
    compare_2_text: 'Veriler birbiriyle entegre çalışır. Bir personelin izne ayrılması, ilgili süreçlere daha tutarlı şekilde yansır.',
    compare_3_title: 'Veri Güvenliği Sağlanır',
    compare_3_text: 'Yerel dosyalar yerine, rol bazlı erişim ve güvenli bulut arşiv yapısıyla daha kontrollü bir çalışma modeli kurarsınız.',

    // 5. İK KAYNAKLARI
    resources_eyebrow: 'ÜCRETSİZ KAYNAKLAR',
    resources_title: 'İK Uzmanlarının Bilgi Merkezi',
    resources_text: 'Sadece yazılım sunmuyoruz, işinizi daha iyi yapmanız için size rehberlik ediyoruz.',
    resource_1_title: 'İK Sözlüğü (Glossary)',
    resource_1_text: 'Puantajdan, eNPS ve OKR\'ye kadar tüm İK terimlerinin detaylı açıklamaları.',
    resource_2_title: 'Ücretsiz Şablonlar',
    resource_2_text: 'İşe giriş kontrol listeleri, mülakat soru formları ve örnek sözleşmeler.',
    resource_3_title: 'Cadro Akademi Blog',
    resource_3_text: 'İK dünyasındaki son trendler, makaleler ve uzman görüşleri.',
    resource_4_title: 'Vaka Çalışmaları',
    resource_4_text: 'Gerçek şirketlerin hangi süreçleri nasıl dönüştürdüğünü ve ne sonuç aldığını görün.',

    // 6. FİYATLANDIRMA
    pricing_eyebrow: 'Fiyatlandırma',
    pricing_title: 'İhtiyacınıza uygun, sürpriz maliyeti olmayan planlar.',
    pricing_text: 'Küçük ekiplerden büyük operasyonlara kadar her ölçeğe uygun esnek paketler.',
    billing_monthly: 'Aylık',
    billing_yearly: 'Yıllık',
    
    sticky_plan_start: 'Basic',
    plan_start_title: 'Dijital İK\'ya ilk adım',
    plan_start_desc: 'Temel insan kaynakları düzenini kurar. İzin, puantaj ve belge arşivi.',
    plan_start_price_monthly: '$99<span>/ay</span>',
    plan_start_price_yearly: '$950<span>/yıl</span>',
    plan_start_note_monthly: 'Sabit Fiyat',
    plan_start_note_yearly: 'Yıllık ödemede avantajlı',
    plan_start_li1: 'Personel Yönetimi',
    plan_start_li2: 'İzin Yönetimi',
    plan_start_li3: 'E-Özlük Arşivi',
    plan_start_li4: 'Temel Puantaj',
    plan_start_btn: 'Basic Planla Başla',
    
    sticky_plan_growth: 'Pro',
    plan_growth_popular: 'En Popüler',
    plan_growth_title: 'Operasyonu sistemleştirenler',
    plan_growth_desc: 'Talep, ATS, işe giriş ve bilgi bankası aynı yapıda birleşir.',
    plan_growth_price_monthly: '$249<span>/ay</span>',
    plan_growth_price_yearly: '$2.390<span>/yıl</span>',
    plan_growth_note_monthly: 'Sabit Fiyat',
    plan_growth_note_yearly: 'Yıllık ödemede avantajlı',
    plan_growth_li1: 'Basic plandaki her şey',
    plan_growth_li2: 'Satın Alma Talepleri',
    plan_growth_li3: 'İşe Alım (ATS)',
    plan_growth_li4: 'Bilgi Bankası',
    plan_growth_btn: 'Pro Planla Başla',

    sticky_plan_scale: 'Enterprise',
    plan_scale_title: 'Gelişmiş yönetim arayanlar',
    plan_scale_desc: 'Büyük ekipler için tasarlanmış tam kapsamlı performans paketi.',
    plan_scale_price_monthly: '$699<span>/ay</span>',
    plan_scale_price_yearly: '$6.799<span>/yıl</span>',
    plan_scale_note_monthly: 'Sabit Fiyat',
    plan_scale_note_yearly: 'Yıllık ödemede avantajlı',
    plan_scale_li1: 'Pro plandaki her şey',
    plan_scale_li2: 'Performans (OKR)',
    plan_scale_li3: 'Detaylı Analitik',
    plan_scale_li4: 'Öncelikli SLA Destek',
    plan_scale_btn: 'Enterprise ile Başla',

    // 7. TRUST (GÜVENLİK) & FOOTER CTA
    trust_eyebrow: 'Güvenilirlik ve Şeffaflık',
    trust_title: 'Uluslararası Standartlarda Altyapı',
    trust_1_title: 'Kesintisiz Hizmet',
    trust_1_text: 'Sistemimiz %99.9 çalışma süresi (uptime) garantisiyle yüksek performansta hizmet verir.',
    trust_2_title: '7/24 Teknik Destek',
    trust_2_text: 'Her türlü teknik ihtiyacınız için info@cadro.io üzerinden bize ulaşabilirsiniz.',
    contact_eyebrow: 'İletişim',
    final_cta_title: 'İK operasyonlarınızı dönüştürmeye bugün başlayın.',
    final_cta_text: 'Hesabınızı oluşturun, çalışanlarınızı davet edin ve süreçlerinizi dijitalleştirin.',
    btn_request_demo: 'Bizimle İletişime Geçin',
    footer_text: 'Şirketlerin insan kaynakları operasyonlarını hızlandıran ve kolaylaştıran modern bulut platformu.',
    footer_copy: '© 2026 CADRO. Tüm hakları saklıdır.',
    footer_phone: '+90 542 884 21 06',
    footer_address: 'Ankara, Türkiye',
    footer_review_label: 'Bizi değerlendirin:',
    footer_yerli: '🇹🇷 Yerli Üretim',
    metric_rating: 'G2 / Capterra Puanı',
    metric_customers: 'Aktif Şirket',
    metric_time_saved: 'Bordro Zaman Tasarrufu',
    metric_uptime: 'Çalışma Süresi',
    meta_title_pricing: 'CADRO Fiyatlandırma | Basic, Pro ve Enterprise Planları',
    meta_desc_pricing: 'CADRO Basic, Pro ve Enterprise planlarını karşılaştırın. İK süreçlerinize uygun fiyatlandırmayı tek sayfada inceleyin.',
    contact_text: 'İhtiyaçlarınıza göre şekillenen bir demo için bizimle iletişime geçin.',
    cf_title: 'Bizimle İletişime Geçin',
    cf_desc: 'Aşağıdaki formu doldurun, en kısa sürede size dönüş yapalım.',
    cf_name: 'Ad Soyad',
    cf_email: 'E-posta Adresi',
    cf_phone: 'Telefon Numarası',
    cf_company: 'Firma Adı',
    cf_message: 'Mesajınız',
    cf_submit: 'Gönder',
    cf_sending: 'Gönderiliyor…',
    cf_success_title: 'Mesajınız İletildi!',
    cf_success_text: 'En kısa sürede sizinle iletişime geçeceğiz.',
    cf_error: 'Gönderim sırasında bir hata oluştu. Lütfen tekrar deneyin.',
    lightbox_close: 'Kapat',
    security_eyebrow: 'Güvenlik Yaklaşımı',
    security_title: 'Kurumsal veriler için güvenli altyapı',
    security_text: 'CADRO, erişim yönetimi, şifreleme ve denetim izleriyle güvenliği ürünün merkezine alır.',
    security_point_1_title: 'Rol Bazlı Erişim',
    security_point_1_text: 'Her kullanıcı yalnızca yetkili olduğu modül ve kayıtlara erişir.',
    security_point_2_title: 'Şifreleme ve Yedekleme',
    security_point_2_text: 'Veriler güvenli protokollerle şifrelenir ve düzenli yedeklenir.',
    security_point_3_title: 'Denetim İzleri',
    security_point_3_text: 'Tüm kritik işlemler kayıt altına alınır ve izlenebilir.',
    security_cta_eyebrow: 'Güvenlik Dokümantasyonu',
    security_cta_title: 'Güvenlik detaylarını paylaşalım.',
    security_cta_contact: 'Güvenlik dokümanı iste',
    architecture_eyebrow: 'Mimari',
    architecture_title: 'Bulut tabanlı, ölçeklenebilir mimari',
    architecture_text: 'CADRO, modüler servisleri ve esnek altyapısı ile büyüyen ekipler için tasarlandı.',
    architecture_point_1_title: 'Modüler Servisler',
    architecture_point_1_text: 'Her modül bağımsız çalışır ve güvenli şekilde entegre olur.',
    architecture_point_2_title: 'Yüksek Performans',
    architecture_point_2_text: 'Yoğun dönemlerde dahi hızlı ve kararlı kullanım deneyimi sunar.',
    architecture_point_3_title: 'Süreklilik ve İzlenebilirlik',
    architecture_point_3_text: 'Servis sağlığı, hatalar ve kullanım metrikleri sürekli izlenir.',
    architecture_cta_eyebrow: 'Teknik İnceleme',
    architecture_cta_title: 'Mimarimizi birlikte değerlendirelim.',
    architecture_cta_contact: 'Teknik görüşme talep et',
    compliance_eyebrow: 'Uyumluluk',
    compliance_title: 'KVKK ve GDPR ile uyumlu süreçler',
    compliance_text: 'Veri minimizasyonu, saklama süreleri ve erişim kontrolleriyle uyumluluk yaklaşımımız net.',
    compliance_point_1_title: 'Veri İşleme İlkeleri',
    compliance_point_1_text: 'Yalnızca gerekli veriler işlenir ve amaç sınırları korunur.',
    compliance_point_2_title: 'Şeffaflık ve Aydınlatma',
    compliance_point_2_text: 'Çalışanlara aydınlatma metinleri ve süreç bilgilendirmeleri sunulur.',
    compliance_point_3_title: 'Silme ve Anonimleştirme',
    compliance_point_3_text: 'Talep üzerine silme ve anonimleştirme süreçleri yönetilir.',
    compliance_cta_eyebrow: 'Uyumluluk Desteği',
    compliance_cta_title: 'KVKK/GDPR uyum sürecinizi hızlandıralım.',
    compliance_cta_contact: 'Uyumluluk danışmanlığı iste',
    security_diagram_eyebrow: 'Teknik Şema',
    security_diagram_title: 'Güvenlik katmanları nasıl çalışır?',
    security_diagram_text: 'Erişim yönetimi, şifreleme ve denetim katmanları birlikte çalışır.',
    security_diagram_node_1: 'Kimlik & Erişim',
    security_diagram_node_2: 'Şifreleme Katmanı',
    security_diagram_node_3: 'Denetim Kayıtları',
    security_standards_eyebrow: 'Standartlar',
    security_standards_title: 'Güvenlik uygulamaları',
    security_standards_item_1: 'ISO 27001 uyumlu süreçler',
    security_standards_item_2: 'Anahtar yönetimi ve şifreleme politikaları',
    security_standards_item_3: 'Düzenli sızma testi',
    security_integrations_eyebrow: 'Entegrasyonlar',
    security_integrations_title: 'Kurumsal kimlik hazır',
    security_integrations_item_1: 'SSO',
    security_integrations_item_2: 'SAML',
    security_integrations_item_3: 'SCIM',
    security_integrations_text: 'Kurumsal dizinlere hızlı ve güvenli bağlantı.',
    architecture_diagram_eyebrow: 'Mimari Şema',
    architecture_diagram_title: 'CADRO mimarisi sade bir görünüm',
    architecture_diagram_text: 'Modüler servisler, veri katmanı ve gözlemlenebilirlik birlikte çalışır.',
    architecture_diagram_node_1: 'Deneyim Katmanı',
    architecture_diagram_node_2: 'Servis Katmanı',
    architecture_diagram_node_3: 'Veri & Depolama',
    architecture_standards_eyebrow: 'Operasyon',
    architecture_standards_title: 'Dayanıklılık pratikleri',
    architecture_standards_item_1: 'Yüksek erişilebilirlik tasarımı',
    architecture_standards_item_2: 'Yedekli altyapı',
    architecture_standards_item_3: 'Sürekli izleme',
    architecture_integrations_eyebrow: 'Entegrasyonlar',
    architecture_integrations_title: 'Kimlik entegrasyonları',
    architecture_integrations_item_1: 'SSO',
    architecture_integrations_item_2: 'SAML',
    architecture_integrations_item_3: 'SCIM',
    architecture_integrations_text: 'Kurumsal kimlik sağlayıcılarına hazır.',
    compliance_diagram_eyebrow: 'Uyumluluk Akışı',
    compliance_diagram_title: 'Veri yaşam döngüsü görünümü',
    compliance_diagram_text: 'Veri envanteri, saklama ve silme süreçleri net şekilde izlenir.',
    compliance_diagram_node_1: 'Veri Envanteri',
    compliance_diagram_node_2: 'Saklama Politikası',
    compliance_diagram_node_3: 'Silme Talepleri',
    compliance_standards_eyebrow: 'Standartlar',
    compliance_standards_title: 'Uyumluluk önlemleri',
    compliance_standards_item_1: 'KVKK/GDPR aydınlatma metinleri',
    compliance_standards_item_2: 'Veri işleme kayıtları',
    compliance_standards_item_3: 'Silme ve anonimleştirme süreçleri',
    compliance_integrations_eyebrow: 'Entegrasyonlar',
    compliance_integrations_title: 'Güvenli erişim',
    compliance_integrations_item_1: 'SSO',
    compliance_integrations_item_2: 'SAML',
    compliance_integrations_item_3: 'SCIM',
    compliance_integrations_text: 'Mevcut kimlik altyapınızla uyumlu.',

    // ÖDEME VE SİPARİŞ SAYFASI (pay.html)
    pay_eyebrow: 'Ödeme Adımı',
    pay_title: 'Aboneliğinizi Başlatın',
    pay_text: 'Şirketiniz için en uygun planı seçtiniz. Şimdi güvenli ödeme adımıyla CADRO dünyasına katılın.',
    pay_plan_1_title: 'Basic Plan',
    pay_plan_1_text: 'Temel İK düzenini kurmak ve dijitalleşmek isteyen ekipler için.',
    pay_plan_2_title: 'Pro Plan',
    pay_plan_2_text: 'Talep, onay, bilgi bankası ve operasyon omurgasını eksiksiz yönetmek için.',
    pay_plan_3_title: 'Enterprise Plan',
    pay_plan_3_text: 'Gelişmiş yönetim, performans ve öncelikli desteğe ihtiyaç duyan büyük yapılar için.',
    pay_billing_note: 'Seçtiğiniz faturalama periyodu ödeme adımına otomatik yansıtılır.',
    pay_status_success_eyebrow: 'İşlem Başarılı',
    pay_status_success_title: 'Aramıza hoş geldiniz!',
    pay_status_success_text: 'Aboneliğiniz başarıyla başlatıldı. Hesap kurulum bilgileriniz kısa süre içinde e-posta adresinize gönderilecektir.',
    pay_status_cancel_eyebrow: 'İşlem İptal Edildi',
    pay_status_cancel_title: 'Ödeme tamamlanamadı.',
    pay_status_cancel_text: 'Ödeme işlemi yarıda kesildi. İsterseniz planınızı tekrar seçip güvenle yeniden deneyebilirsiniz.',
    pay_status_error_eyebrow: 'Sistem Uyarısı',
    pay_status_error_title: 'Ödeme sistemine ulaşılamıyor.',
    pay_status_error_text: 'Geçici bir bağlantı sorunu oluştu. Lütfen birazdan tekrar deneyin veya destek ekibimizle iletişime geçin.',
    pay_cta_start: 'Basic ile Başla',
    pay_cta_growth: 'Pro ile Başla',
    pay_cta_scale: 'Enterprise ile Başla',
    pay_checkout_ready_eyebrow: 'Güvenli Ödeme',
    pay_checkout_ready_title: 'İşleminizi Güvenle Tamamlayın',
    pay_checkout_ready_text: 'Seçtiğiniz plan üzerinden global ödeme sağlayıcımız güvencesiyle işleminizi anında ve güvenle tamamlayabilirsiniz.',
    pay_note_eyebrow: 'Ödemeleriniz Güvence Altında',
    pay_note_title: '256-bit Güvenli Şifreleme',
    pay_note_text: 'Tüm abonelik ve faturalandırma işlemleriniz global ödeme altyapısı sağlayıcımız Paddle aracılığıyla yüksek güvenlik standartlarıyla korunmaktadır.',

    // YASAL SAYFALAR (privacy, terms, refund)
    legal_eyebrow: 'Yasal Belgeler',
    privacy_title: 'Gizlilik Politikası',
    privacy_intro: 'Bu gizlilik politikası, CADRO platformunu kullanırken verilerinizin nasıl korunduğunu açıklar.',
    privacy_p1: 'CADRO, hizmetin sorunsuz sunulabilmesi için yalnızca gerekli asgari bilgileri işler. Verileriniz; rol bazlı erişim protokolleri, izlenebilir denetim kayıtları ve şifrelenmiş depolama ilkeleriyle sıkı koruma altındadır.',
    privacy_p2: 'Abonelik ve faturalama işlemleri, global ve sertifikalı ödeme iş ortağımız Paddle tarafından gerçekleştirilir. Finansal verileriniz doğrudan bu altyapıda güvence altındadır.',
    privacy_p3: 'Kişisel veri haklarınız ve tüm destek talepleriniz için dilediğiniz zaman info@cadro.io adresi üzerinden bize ulaşabilirsiniz.',
    privacy_p4: 'Platform hizmet sağlayıcısı: Turgay Bozkuş.',
    terms_title: 'Kullanım Şartları',
    terms_intro: 'Hizmetimizi kullanırken tabi olduğunuz genel kullanım şartları aşağıda belirtilmiştir.',
    terms_p1: 'CADRO, kurumların kullanımına sunulan bulut tabanlı (SaaS) bir yazılım hizmetidir. Platform, seçtiğiniz plan kapsamındaki özelliklerle kullanıma açılır.',
    terms_p2: 'Abonelik sınırları, faturalandırma periyotları ve paket değişiklikleri, sitemizde beyan edilen güncel fiyatlandırma şartlarına tabidir.',
    terms_p3: 'Hizmetin kesintisiz ve güvenli kullanımı esastır. Sistem bütünlüğünü riske atacak kullanımlar hizmet koşullarının ihlali sayılır.',
    terms_p4: 'Sorularınız ve sözleşme detayları için hizmet yöneticisi Turgay Bozkuş ile iletişime geçebilirsiniz.',
    refund_title: 'İade Politikası',
    refund_intro: 'Abonelik iptali ve iade süreçleriyle ilgili politikalarımız aşağıda detaylandırılmıştır.',
    refund_p1: 'Aylık veya yıllık aboneliklerde, iptal talebinizden sonra hesabınız mevcut fatura döneminin sonuna kadar aktif kalmaya devam eder.',
    refund_p2: 'Kısmi iade uygulaması bulunmamaktadır. Ancak teknik sorunlar, faturalama hataları veya mükerrer çekim durumlarında iade işlemleri anında gerçekleştirilir.',
    refund_p3: 'İptal, iade ve fatura inceleme talepleriniz için lütfen info@cadro.io adresi üzerinden destek ekibimize yazın.',
    refund_p4: 'Hizmet memnuniyetiniz bizim için önemlidir. Sistem hatalarından kaynaklanan durumlarda müşteri lehine hareket edilir.',
    legal_terms_link: 'Kullanım Şartları',
    legal_privacy_link: 'Gizlilik Politikası',
    legal_refund_link: 'İade Politikası',
  };
