window.CADRO_TR_de = {
    meta_title_index: 'CADRO | HR-Plattform der nächsten Generation',
    meta_desc_index: 'CADRO vereint Recruiting, E-Akte, Zeiterfassung, Urlaub, Einkauf und interne Workflows auf einer Plattform.',
    meta_title_pay: 'CADRO | Sicherer Checkout',
    meta_desc_pay: 'CADRO sichere Zahlungs- und Abonnementseite.',
    meta_title_security: 'Sicherheit für HR-Daten und Zugriffe | CADRO',
    meta_desc_security: 'Schützen Sie HR-Daten mit rollenbasiertem Zugriff, Passwort- und Sitzungskontrollen, Audit-Trails und administrativer Governance.',
    meta_title_architecture: 'CADRO | Architektur',
    meta_desc_architecture: 'Cloud-native, skalierbare CADRO-Architektur und Performance-Ebenen.',
    meta_title_compliance: 'HR-Compliance und KVKK-Prozessmanagement | CADRO',
    meta_desc_compliance: 'Verwalten Sie Dokumenten-Compliance, Richtlinienbestätigungen und digitale Personalakten in einem kontrollierten Workflow.',
    meta_title_privacy: 'CADRO | Datenschutzerklärung',
    meta_title_terms: 'CADRO | Nutzungsbedingungen',
    meta_title_refund: 'CADRO | Rückerstattungsrichtlinie',
    'meta_title_ats-ise-alim-yazilimi': 'Bewerbermanagement (ATS) & Recruiting-Software | CADRO HR-Management-System',
    'meta_desc_ats-ise-alim-yazilimi': 'Bewerbungen in einer Pipeline verwalten, Talentpools aufbauen und Interviews mit CADRO ATS strukturierter steuern.',
    meta_title_blog: 'CADRO Blog | HR-, KI- und Leadership-Trends',
    meta_title_faq: 'CADRO FAQ | Häufige Fragen zu HR-Software',
    meta_desc_faq: 'Antworten zu Preisen, Modulen, Sicherheit, Support und Integrationen von CADRO.',
    'meta_title_vaka-calismalari': 'CADRO Fallstudien | Kundenerfolge',
    'meta_desc_vaka-calismalari': 'Sehen Sie reale operative Ergebnisse und Kundenerfolge aus verschiedenen Branchen.',
    meta_desc_privacy: 'Grundlegende Informationen zu Datenschutzprinzipien und Datenverarbeitung bei CADRO.',
    meta_desc_terms: 'Vertraglicher Rahmen für Zugriff und Nutzung der CADRO-Dienste.',
    meta_desc_refund: 'Richtlinie zu Kündigung, Erstattungen und Rechnungsprüfungen.',
    meta_desc_blog: 'Aktuelle Management-Trends, KI-Strategien und Teamführung für CHROs und HR-Leads.',
    'meta_title_dijital-ozluk-ve-izin': 'Digitale Personalakte & Urlaubsmanagement | CADRO',
    'meta_desc_dijital-ozluk-ve-izin': 'Digitale Personalakten, Dokumenten-Compliance und Urlaubsfreigaben in einer HR-Plattform verwalten.',
    'meta_title_excel-vs-cadro': 'Excel vs. CADRO im HR | Warum Excel nicht reicht',
    'meta_desc_excel-vs-cadro': 'Risiken von Excel im HR? Zeit- und Kostenvorteile durch CADRO-Automatisierung.',
    'meta_title_ik-sozlugu': 'HR-Glossar & Begriffe | CADRO',
    'meta_desc_ik-sozlugu': 'Klare, aktuelle Definitionen: Zeiterfassung, OKR, Turnover, eNPS und mehr.',
    'meta_title_ik-yazilimi': 'Was ist HR-Software? | CADRO',
    'meta_desc_ik-yazilimi': 'Erfahren Sie, welche Module HR-Software umfasst und steuern Sie Recruiting, Akte, Urlaub, Performance und Payroll auf einer Plattform.',
    'meta_title_kurumsal-bilgi-bankasi-ve-onboarding': 'Wissensdatenbank und Einarbeitungssoftware | CADRO',
    'meta_desc_kurumsal-bilgi-bankasi-ve-onboarding': 'Verwalten Sie Richtlinien, SOPs, Bestätigungen und Einarbeitungsaufgaben in einer zentralen Wissensstruktur.',
    'meta_title_masraf-ve-satin-alma': 'Spesen- & Einkaufsanfragen | CADRO',
    'meta_desc_masraf-ve-satin-alma': 'Stoppen Sie unkontrollierte Ausgaben. Digitale Freigaben und transparentes Purchasing.',
    'meta_title_performans-degerlendirme-okr': 'Performance Management & OKR-Software | 360° Reviews | CADRO',
    'meta_desc_performans-degerlendirme-okr': 'Performance Reviews, 360-Grad-Feedback und OKR-Tracking in einer Plattform steuern.',
    'meta_title_puantaj-ve-vardiya-yazilimi': 'Intelligente Zeiterfassung, Überstunden & Schichtplanung | CADRO',
    'meta_desc_puantaj-ve-vardiya-yazilimi': 'Vermeiden Sie Payroll-Lecks und rechtliche Risiken mit fehlerfreier Zeiterfassung.',
    'meta_title_ucretsiz-sablonlar': 'Kostenlose HR-Vorlagen, Excel & Formulare | CADRO',
    'meta_desc_ucretsiz-sablonlar': 'Laden Sie Einarbeitungsvorlagen, Performance-Formulare und Excel-Sheets herunter.',
    'meta_title_makale-yapay-zeka-genai': '15 Stunden pro Woche sparen mit Generativer KI (GenAI) im HR | CADRO Blog',
    'meta_desc_makale-yapay-zeka-genai': 'Wie Sie 15 Stunden pro Woche in Recruiting, Performance und Einarbeitung mit GenAI sparen.',
    'meta_title_makale-prediktif-ik': 'Predictive HR: Wer kündigt als Nächstes? | CADRO',
    'meta_desc_makale-prediktif-ik': 'Mit Predictive Analytics Abwanderungsrisiken früh erkennen.',
    'meta_title_makale-ise-alimda-ai-etik': 'KI im Recruiting: Bias reduzieren oder verstärken? | CADRO',
    'meta_desc_makale-ise-alimda-ai-etik': 'Ethische Risiken und verantwortungsvolle KI-Nutzung im Hiring.',
    'meta_title_makale-ai-ve-kvkk-uyumu': 'KI vs. KVKK: Rechtsrisiken bei Mitarbeiterdaten | CADRO',
    'meta_desc_makale-ai-ve-kvkk-uyumu': 'So bleiben Sie konform beim Einsatz von KI mit Mitarbeiterdaten.',
    'meta_title_makale-sessiz-istifa-maliyeti': 'Was kostet Quiet Quitting Ihr Unternehmen? | CADRO',
    'meta_desc_makale-sessiz-istifa-maliyeti': 'Die versteckten OPEX-Kosten geringer Bindung.',
    'meta_title_makale-ik-dijital-donusum-2026': 'Leitfaden HR-Digitalisierung 2026 | CADRO',
    'meta_desc_makale-ik-dijital-donusum-2026': 'ROI-Erwartungen, Prioritäten und Roadmap.',
    'meta_title_makale-turnover-dusurme-yollari': '5 datenbasierte Wege, Fluktuation zu senken | CADRO',
    'meta_desc_makale-turnover-dusurme-yollari': 'So reduzieren Sie Fluktuation mit messbaren Maßnahmen.',
    'meta_title_makale-yillik-performans-degerlendirme': 'Sind jährliche Performance-Reviews vorbei? | CADRO',
    'meta_desc_makale-yillik-performans-degerlendirme': 'Warum jährliche Reviews nicht reichen und Alternativen.',
    'meta_title_makale-dijital-ozluk-ve-kvkk': 'Digitale Personalakte & KVKK-Audits | CADRO',
    'meta_desc_makale-dijital-ozluk-ve-kvkk': 'Compliance und rechtliche Gültigkeit digitaler Archive.',
    'meta_title_makale-excel-bordro-sizintilari': 'Payroll-Leckagen: Die Kosten von Excel-Stundenzetteln | CADRO',
    'meta_desc_makale-excel-bordro-sizintilari': 'Wie manuelle Tabellen zu Leckagen führen.',
    nav_modules: 'Module',
    nav_platform: 'Plattform',
    nav_pricing: 'Preise',
    nav_demo: 'Produkt-Tour',
    nav_trust: 'Sicherheit',
    nav_contact: 'Kontakt',
    nav_case_studies: 'Fallstudien',
    nav_software: 'HR‑Software',
    nav_solutions: 'Lösungen',
    nav_compare: 'Warum Cadro?',
    nav_resources: 'Ressourcen',
    cta_ats_module: 'ATS‑Modul ansehen →',
    cta_performance_module: 'Performance‑Modul ansehen →',
    cta_dossier_module: 'Akte & Urlaub‑Modul ansehen →',
    cta_timekeeping_module: 'Zeiterfassungs‑Lösung ansehen →',
    cta_excel_compare: 'Vollständigen Vergleich lesen →',
    cta_hr_glossary: 'HR‑Glossar ansehen →',
    cta_free_templates: 'Vorlagen herunterladen →',
    cta_blog: 'Blog lesen →',
    cta_case_studies: 'Fallstudien ansehen →',
    resources_eyebrow: 'KOSTENLOSE RESSOURCEN',
    resources_title: 'Wissenszentrum für HR‑Leads',
    resources_text: 'Wir liefern nicht nur Software – wir helfen, HR besser zu machen.',
    resource_1_title: 'HR‑Glossar',
    resource_1_text: 'Klare Definitionen von HR‑Begriffen – von Zeiterfassung bis eNPS und OKRs.',
    resource_2_title: 'Kostenlose Vorlagen',
    resource_2_text: 'Einarbeitungs-Checklisten, Interviewleitfäden und Musterverträge.',
    resource_3_title: 'Cadro Academy Blog',
    resource_3_text: 'Aktuelle HR‑Trends, Artikel und Experteneinblicke.',
    resource_4_title: 'Fallstudien',
    resource_4_text: 'Sehen Sie, wie reale Unternehmen HR-Abläufe transformiert und messbare Ergebnisse erzielt haben.',
    nav_home: 'Startseite',
    nav_all_features: 'Alle Funktionen',
    nav_blog: 'Blog',
    btn_login: 'Anmelden',
    btn_payment_page: 'Zur Kasse',
    btn_start_selling: 'Loslegen',
    btn_view_plans: 'Pläne ansehen',
    btn_back_home: 'Zur Startseite',
    sticky_plan_start: 'Basic',
    sticky_plan_growth: 'Pro',
    sticky_plan_scale: 'Enterprise',
    sticky_plan_start_meta: '$99 / Monat',
    sticky_plan_growth_meta: '$249 / Monat',
    sticky_plan_scale_meta: '$699 / Monat',
    sticky_plan_cta: 'Pläne ansehen',
    hero_eyebrow: '',
    hero_title: 'Cloudbasierte HR-Software',
    hero_text: 'Recruiting, Performance, Urlaub und Zeiterfassung in einer einzigen Cloud‑Plattform steuern.',
    hero_subtext: 'CADRO bündelt alle HR-Prozesse Ihres Unternehmens in einer cloudbasierten HR-Software.',
    btn_start_subscription: 'Abonnement starten',
    btn_view_demo: 'Produkt ansehen',
    point_multi_tenant: 'Cloud-Architektur',
    point_role_based: 'Erweiterte Berechtigungen',
    point_kvkk: 'Volle Datenkonformität',
    video_eyebrow: 'Produktfilm',
    video_title: 'Sehen Sie CADRO in 90 Sekunden',
    video_text: 'Ein kurzer Produktfilm zeigt, wie CADRO Management, Betrieb und Mitarbeitererlebnis auf einer Plattform verbindet.',
    video_point_1_title: 'Ein Steuerungszentrum',
    video_point_1_text: 'Behalten Sie HR-, Operations- und Finanzabläufe in einer Ansicht im Blick.',
    video_point_2_title: 'Echte Produktabläufe',
    video_point_2_text: 'Verfolgen Sie ATS, Zeiterfassung, E-Akte und Genehmigungen in einer zusammenhängenden Geschichte.',
    video_point_3_title: 'Schneller Überblick vor der Demo',
    video_point_3_text: 'Verstehen Sie Tempo und Umfang des Produkts, bevor Sie die Pläne prüfen.',
    metric_modules_label: 'Aktive Module',
    metric_modules_text: 'HR-Kern, ATS, Zeiterfassung, E-Akte, Leistung und interne Anfragen',
    metric_ops_label: 'Betriebskraft',
    metric_ops_value: 'Flexibel & Dynamisch',
    metric_ops_text: 'Individuelle Dashboards für Mitarbeiter, Manager, HR und Administratoren',
    metric_ready_label: 'Schnelle Einrichtung',
    metric_ready_value: 'Sofortige Aktivierung',
    metric_ready_text: 'Richten Sie Ihre Struktur ein und starten Sie in wenigen Minuten',
    metric_ui_label: 'Benutzererfahrung',
    metric_ui_value: 'Sauber & Modern',
    metric_ui_text: 'Keine Schulung erforderlich, funktioniert reibungslos auf jedem Gerät',
    strip_product_label: 'Alles in einem',
    strip_product_text: 'HR-Management-System + ATS + Mitarbeiterportal + Interner Workflow',
    strip_who_label: 'Für wen ist es?',
    strip_who_text: 'Moderne Teams, die ihre HR-Prozesse digitalisieren möchten',
    strip_delivery_label: 'Servicemodell',
    strip_delivery_text: 'SaaS der nächsten Generation auf hochsicherer Cloud-Infrastruktur',
    proof_title: 'Warum CADRO wählen?',
    compare_eyebrow: 'WARUM CADRO?',
    compare_title: 'Zeit, Excel hinter sich zu lassen.',
    compare_1_title: 'Zeitgewinn',
    compare_1_text: 'Automatisierte Workflows sparen Stunden pro Woche.',
    compare_2_title: 'Weniger Fehler',
    compare_2_text: 'Integrierte Prozesse verhindern Doppelpflege.',
    compare_3_title: 'Sicher & DSGVO‑konform',
    compare_3_text: 'Verschlüsselte Daten, rollenbasierte Zugriffe.',
    proof_line_1: 'Alle Daten werden in einem sicheren Hub gesammelt.',
    proof_line_2: 'Bietet transparente Prozesse mit rollenbasiertem Zugriff.',
    proof_line_3: 'Arbeitet mit einer intelligenten Logik, die Datenkopien eliminiert.',
    proof_metric_1_label: 'Zentrales Management',
    proof_metric_1_text: 'Akte, Zeiterfassung und Workflows sind vollständig integriert.',
    proof_metric_2_label: 'Unterbrechungsfreier Fluss',
    proof_metric_2_text: 'Prozesse hinterlassen einen klaren digitalen Fußabdruck.',
    proof_metric_3_label: 'Moderne Erfahrung',
    proof_metric_3_text: 'Ein sauberes Design, das Mitarbeiter ohne Verwirrung gerne nutzen.',
    modules_eyebrow: 'Lösungen',
    modules_title: 'Module zur Stärkung Ihrer Abläufe.',
    modules_text: 'Alle benötigten HR-Tools, integriert und frei von Unordnung.',
    module_1_title: 'Recruiting & ATS',
    module_1_text: 'Verwalten Sie Stellenanzeigen, Bewerber und Interviews professionell.',
    module_2_title: 'Digitale E-Akte',
    module_2_text: 'Speichern Sie Dokumente sicher und lassen Sie das System fehlende Papiere verfolgen.',
    module_3_title: 'Smarte Zeiterfassung',
    module_3_text: 'Bereiten Sie Schichten, Überstunden und Fehlzeiten für die Gehaltsabrechnung vor.',
    module_4_title: 'Urlaub & Flexible Arbeit',
    module_4_text: 'Verwalten Sie Urlaubsarten, Workflows und Jahressalden ganz einfach.',
    module_5_title: 'Ausgaben & Einkauf',
    module_5_text: 'Verbinden Sie Personalausgaben und Bestellanfragen mit digitalen Freigaben.',
    module_6_title: 'Wissensdatenbank',
    module_6_text: 'Veröffentlichen Sie Richtlinien zentral und überwachen Sie die Lesequoten.',
    module_7_title: 'Einarbeitung / Austritt',
    module_7_text: 'Gestalten Sie ein fehlerfreies Erlebnis für Neueinsteiger.',
    module_8_title: 'Leistung & Ziele',
    module_8_text: 'Messen Sie die Leistung und verfolgen Sie KPIs.',
    showcase_title: 'Effizienz neu definieren',
    showcase_text: 'CADRO automatisiert Ihre Prozesse, damit Sie sich auf Ihre Mitarbeiter konzentrieren können.',
    showcase_1_eyebrow: 'Ein Datensatz, volle Integration',
    showcase_1_title: 'Keine verstreuten Daten mehr.',
    showcase_1_text: 'Bewerbungen in einem Board sammeln; sobald ein Lebenslauf hochgeladen wird, bewertet die KI automatisch Kommunikation, Fachkompetenz, kulturelle Passung und Motivation in 4 Dimensionen. Interview, Angebotsschreiben und Onboarding – alles auf einem Bildschirm.',
    showcase_1_ph: 'Leerer Bereich für Produkt-Screenshot',
    showcase_2_eyebrow: 'Smarte Workflows',
    showcase_2_title: 'Ausgaben und interne Anfragen sofort abschließen.',
    showcase_2_text: 'OKR-Ziele auf Unternehmens-, Team- und Mitarbeiterebene definieren; Fortschritt laufend verfolgen. 360°-Feedback von Vorgesetzten, Kollegen und per Selbsteinschätzung sammeln. KI-gestützte Talentanalyse stärkt Ihre Entscheidungen.',
    showcase_2_ph: 'Leerer Bereich für Visualisierung',
    showcase_3_eyebrow: 'Automatisierte Alarme',
    showcase_3_title: 'Verpassen Sie nie ein ablaufendes Dokument.',
    showcase_3_text: 'Vollständige digitale Personalakte: Identität, Bankdaten, Arbeitserlaubnis und NDA – alles an einem Ort. Urlaubsanträge (Jahres-, Krankheits-, Entschuldigungs- und Elternzeit) mit Überschneidungsprüfung verwalten; Genehmigungsworkflows laufen automatisch.',
    showcase_3_ph: 'Leerer Bereich für Compliance',
    how_it_works_label: 'So funktioniert\'s',
    showcase_1_step_1: 'Stelle erstellen und auf der Karriereseite veröffentlichen',
    showcase_1_step_2: 'Bewerbungen werden automatisch gesammelt, der Kandidatenpool entsteht',
    showcase_1_step_3: 'Kandidaten auf dem Kanban-Board von Phase zu Phase verschieben',
    showcase_1_step_4: 'Angenommene Kandidaten werden mit einem Klick zum Mitarbeiterdatensatz',
    showcase_2_step_1: 'OKR-Ziele auf Unternehmens-, Team- und Mitarbeiterebene definieren',
    showcase_2_step_2: 'Mitarbeiter aktualisieren ihren Fortschritt laufend',
    showcase_2_step_3: '360°-Feedback und KI-Talentanalyse werden abgeschlossen',
    showcase_2_step_4: 'Ergebnisse werden berichtet und Karrierepläne gestaltet',
    showcase_3_step_1: 'Für jeden Mitarbeiter wird eine digitale Personalakte erstellt',
    showcase_3_step_2: 'Dokumente werden hochgeladen; fehlende lösen automatische Warnungen aus',
    showcase_3_step_3: 'Mitarbeiter beantragen Urlaub mobil; Manager werden sofort benachrichtigt',
    showcase_3_step_4: 'Genehmigter Urlaub aktualisiert das Guthaben und synchronisiert mit der Lohnbuchhaltung',
    screen_dashboard_badge_1: 'Smart Cockpit',
    screen_dashboard_badge_2: 'Detaillierte Analysen',
    screen_dossier_badge_1: 'Cloud-Archiv',
    screen_dossier_badge_2: 'Fehlende Dokumente',
    screen_request_badge_1: 'Dynamische Formulare',
    screen_request_badge_2: 'Transparente Freigaben',
    screen_knowledge_badge_1: 'Versionskontrolle',
    screen_knowledge_badge_2: 'Leseverfolgung',
    results_eyebrow: 'Vorteile',
    results_title: 'Was bringt CADRO Ihrem Unternehmen?',
    results_1_title: 'Zeitersparnis',
    results_1_text: 'Excel-Tabellen und manuelle Nachverfolgung werden durch automatisierte Systeme ersetzt.',
    results_2_title: 'Fehlerfreie Prozesse',
    results_2_text: 'Fehler bei der Berechnung von Anwesenheit und Urlaub sinken auf Null.',
    results_3_title: 'Hohe Mitarbeiterzufriedenheit',
    results_3_text: 'Mitarbeiter können jederzeit transparent auf ihre Daten zugreifen.',
    testimonial_eyebrow: 'KUNDENERFAHRUNGEN',
    testimonial_title: 'Sehen Sie, wie Teams ihre HR-Prozesse beschleunigen.',
    testimonial_1_quote: '"Dank CADRO ist das Chaos in unseren Akten vollständig verschwunden."',
    testimonial_1_name: 'HR-Manager',
    testimonial_2_quote: '"Die Verwaltung aller Freigaben auf einem Bildschirm hat uns extrem viel Zeit gespart."',
    testimonial_2_name: 'Operations Director',
    testimonial_3_quote: '"Die rollenbasierte Autorisierung funktioniert reibungslos."',
    testimonial_3_name: 'Unternehmensgründer',
    faq_eyebrow: 'FAQ',
    faq_title: 'Häufig gestellte Fragen zum System',
    faq_q1: 'Welche Prozesse deckt CADRO genau ab?',
    faq_a1: 'CADRO ist eine End-to-End HR-Plattform, die E-Akte, Zeiterfassung, Urlaub, Ausgaben, ATS und mehr abdeckt.',
    faq_q2: 'Wie kann ich meine bestehenden Daten importieren?',
    faq_a2: 'Mit unseren fortschrittlichen Excel-Import-Tools können Sie Ihre Daten in wenigen Minuten übertragen.',
    faq_q3: 'Wie funktionieren Abrechnung und Zahlung?',
    faq_a3: 'Zahlungen werden über unseren globalen Anbieter Paddle abgewickelt. Rechnungen werden automatisch generiert.',
    faq_q4: 'Benötigen wir eine technische Schulung?',
    faq_a4: 'Nein, CADRO hat eine benutzerfreundliche Oberfläche. Sie können sofort loslegen.',
    faq_q5: 'Sind unsere Daten sicher?',
    faq_a5: 'Absolut. Ihre Daten werden auf globalen Servern mit den neuesten Sicherheitsstandards gehostet.',
    final_cta_title: 'Beginnen Sie noch heute mit der Transformation.',
    final_cta_text: 'Richten Sie Ihr Konto in Sekundenschnelle ein und digitalisieren Sie Ihre Prozesse.',
    platform_eyebrow: 'Plattform-Architektur',
    platform_title: 'Robuste Infrastruktur, nahtlose Erfahrung.',
    flow_1_title: 'Zentrales Identitätsmanagement',
    flow_1_text: 'Der gesamte Organigramm wird flexibel von einem Zentrum aus verwaltet.',
    flow_2_title: 'Dynamische Workflows',
    flow_2_text: 'Mehrstufige Genehmigungs- und Benachrichtigungsflüsse.',
    flow_3_title: 'Proaktive Alarme',
    flow_3_text: 'Das System warnt Sie im Voraus bei fehlenden Dokumenten.',
    flow_4_title: 'Umfassende Analysen',
    flow_4_text: 'Verwandelt Daten in aussagekräftige Berichte.',
    pricing_eyebrow: 'Preise',
    pricing_title: 'Pläne ohne versteckte Kosten.',
    pricing_text: 'Arbeiten Sie grenzenlos mit unseren flexiblen Festpreispaketen für jede Unternehmensgröße.',
    billing_monthly: 'Monatlich',
    billing_yearly: 'Jährlich',
    billing_discount_badge: '20% jährlich sparen',
    pricing_toggle_note: 'Jahrespläne werden mit 10 statt 12 Monaten berechnet.',
    plan_start_title: 'Ideal für Teams beim ersten Schritt in digitale HR.',
    plan_start_desc: 'Baut die HR-Grundlage auf. Mitarbeiterdaten, Urlaub und Dokumente an einem Ort.',
    plan_start_price_monthly: '$99<span>/Monat</span>',
    plan_start_price_yearly: '$950<span>/Jahr</span>',
    plan_start_note_monthly: 'Festpreis, alle Basisfunktionen inklusive',
    plan_start_note_yearly: 'Durchschnittlich $79 / Monat',
    plan_start_li1: 'Personal- und Abteilungsverwaltung',
    plan_start_li2: 'Umfassendes Urlaubsmanagement',
    plan_start_li3: 'E-Akte und Cloud-Archiv',
    plan_start_li4: 'Grundlegende Berichte',
    plan_start_btn: 'Mit Basic starten',
    plan_growth_title: 'Für Unternehmen, die Abläufe systematisieren möchten.',
    plan_growth_desc: 'Anfragen, Freigaben, Lohnvorbereitung und Wissensdatenbank vereint.',
    plan_growth_popular: 'Am beliebtesten',
    plan_growth_price_monthly: '$249<span>/Monat</span>',
    plan_growth_price_yearly: '$2.390<span>/Jahr</span>',
    plan_growth_note_monthly: 'Festpreis, alle Funktionen inklusive',
    plan_growth_note_yearly: 'Durchschnittlich $199 / Monat',
    plan_growth_li1: 'Alles in Basic',
    plan_growth_li2: 'Ausgaben- und Bestellanfragen',
    plan_growth_li3: 'Recruiting und Einarbeitung',
    plan_growth_li4: 'Wissensdatenbank und Ankündigungen',
    plan_growth_btn: 'Mit Pro starten',
    plan_scale_title: 'Für Organisationen, die erweiterte Governance suchen.',
    plan_scale_desc: 'Ein vollständiges Festpreispaket für größere Teams ohne Limits.',
    plan_scale_price_monthly: '$699<span>/Monat</span>',
    plan_scale_price_yearly: '$6.799<span>/Jahr</span>',
    plan_scale_note_monthly: 'Festpreis ohne Limits',
    plan_scale_note_yearly: 'Durchschnittlich $566 / Monat',
    plan_scale_li1: 'Alles in Pro',
    plan_scale_li2: 'Erweitertes Leistungsmanagement',
    plan_scale_li3: 'Detaillierte Metriken',
    plan_scale_li4: 'Priorisierter Support (SLA)',
    plan_scale_btn: 'Mit Enterprise starten',
    demo_eyebrow: 'Produkt-Tour',
    demo_title: 'Erleben Sie CADRO in Aktion',
    demo_text: 'Entdecken Sie in einer kurzen Produkttour, wie unsere Oberfläche Ihre HR-Prozesse vereinfacht.',
    video_placeholder_title: 'Systemoberfläche',
    video_placeholder_text: 'Sehen Sie sich das Video unten an, um CADRO im Detail kennenzulernen.',
    video_note_1_title: 'Schnelle Einrichtung',
    video_note_1_text: 'Passen Sie das System in Minuten an Ihre Unternehmensstruktur an.',
    video_note_2_title: 'Benutzerfreundlich',
    video_note_2_text: 'Eine moderne Oberfläche, die Ihr Team ohne Schulung lieben wird.',
    video_note_3_title: 'Sichere Infrastruktur',
    video_note_3_text: 'Ihre Daten werden mit den höchsten Standards verschlüsselt und gesichert.',
    trust_eyebrow: 'Zuverlässigkeit & Transparenz',
    trust_title: 'Internationale Standards',
    trust_1_title: 'Cloud-basierte Software (SaaS)',
    trust_1_text: 'CADRO erfordert keine Installations- oder Hardwarekosten.',
    trust_2_title: 'Unterbrechungsfreier Service',
    trust_2_text: 'Unser System garantiert 99,9 % Betriebszeit.',
    trust_3_title: '24/7 Support',
    trust_3_text: 'Sie erreichen unser Expertenteam jederzeit: ',
    trust_4_title: 'Transparente Preise',
    trust_4_text: 'Sie arbeiten mit Festpreisen ohne versteckte Kosten.',
    trust_5_title: 'Datenkonformität & Sicherheit',
    legal_terms_link: 'Nutzungsbedingungen',
    legal_privacy_link: 'Datenschutzerklärung',
    legal_refund_link: 'Rückerstattung',
    contact_eyebrow: 'Kontakt',
    contact_title: 'Wir sind hier, um Ihre Prozesse zu verbessern.',
    contact_text: 'Kontaktieren Sie uns für Unternehmensanfragen oder individuelle Lösungen.',
    btn_request_demo: 'Live-Demo anfordern',
    btn_request_info: 'Vertrieb kontaktieren',
    cf_title: 'Kontaktieren Sie uns',
    cf_desc: 'Füllen Sie das Formular aus und wir melden uns in Kürze bei Ihnen.',
    cf_name: 'Vollständiger Name',
    cf_email: 'E-Mail-Adresse',
    cf_phone: 'Telefonnummer',
    cf_company: 'Firmenname',
    cf_message: 'Ihre Nachricht',
    cf_submit: 'Senden',
    cf_sending: 'Wird gesendet…',
    cf_success_title: 'Nachricht gesendet!',
    cf_success_text: 'Wir werden uns in Kürze bei Ihnen melden.',
    cf_error: 'Beim Senden ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    footer_tagline: 'Lokale cloudbasierte HR-Software aus der Türkei.',
    footer_product_title: 'Produkt',
    footer_product_link: 'HR-Software',
    footer_pricing_link: 'Preise',
    footer_company_title: 'Unternehmen',
    footer_blog_link: 'Blog',
    footer_cases_link: 'Fallstudien',
    footer_faq_link: 'FAQ',
    footer_legal_title: 'Rechtliches',
    footer_privacy_link: 'Datenschutz',
    footer_terms_link: 'Nutzungsbedingungen',
    footer_refund_link: 'Widerrufsrecht',
    footer_text: 'Die moderne Cloud-Plattform zur Vereinfachung von HR-Prozessen.',
    footer_copy: '© 2026 CADRO. Alle Rechte vorbehalten.',
    footer_phone: '+90 542 884 21 06',
    footer_address: 'Ankara, Türkei',
    metric_rating: 'G2 / Capterra Bewertung',
    metric_customers: 'Aktive Unternehmen',
    metric_time_saved: 'Lohnabrechnungs-Zeitersparnis',
    metric_uptime: 'Betriebszeit',
    footer_review_label: 'Bewerten Sie uns:',
    footer_yerli: '🇹🇷 Made in Turkey',
    meta_title_pricing: 'CADRO Preise | Basic-, Pro- und Enterprise-Pläne',
    meta_desc_pricing: 'Vergleichen Sie die CADRO Pläne Basic, Pro und Enterprise. Prüfen Sie die Preisstruktur für Ihre HR-Prozesse an einem Ort.',
    lightbox_close: 'Schließen',
    pay_eyebrow: 'Zahlung',
    pay_title: 'Starten Sie Ihr Abonnement',
    pay_text: 'Treten Sie der CADRO-Welt über unseren sicheren Checkout bei.',
    pay_plan_1_title: 'Basic Plan',
    pay_plan_1_text: 'Für Teams, die ihre HR-Grundlage digitalisieren möchten.',
    pay_plan_2_title: 'Pro Plan',
    pay_plan_2_text: 'Um Freigaben und HR-Wissen nahtlos zu verwalten.',
    pay_plan_3_title: 'Enterprise Plan',
    pay_plan_3_text: 'Für große Organisationen mit erweitertem Support-Bedarf.',
    pay_billing_note: 'Ihr Abrechnungszyklus wird automatisch angewendet.',
    pay_status_success_eyebrow: 'Transaktion erfolgreich',
    pay_status_success_title: 'Willkommen an Bord!',
    pay_status_success_text: 'Ihr Abonnement wurde erfolgreich gestartet.',
    pay_status_cancel_eyebrow: 'Transaktion abgebrochen',
    pay_status_cancel_title: 'Checkout nicht abgeschlossen.',
    pay_status_cancel_text: 'Sie können Ihren Plan erneut auswählen.',
    pay_status_error_eyebrow: 'Systemhinweis',
    pay_status_error_title: 'Zahlungssystem nicht erreichbar.',
    pay_status_error_text: 'Bitte versuchen Sie es in Kürze erneut.',
    pay_cta_start: 'Mit Basic starten',
    pay_cta_growth: 'Mit Pro starten',
    pay_cta_scale: 'Mit Enterprise starten',
    pay_checkout_ready_eyebrow: 'Sicherer Checkout',
    pay_checkout_ready_title: 'Schließen Sie Ihre Transaktion sicher ab',
    pay_checkout_ready_text: 'Schließen Sie Ihre Transaktion sicher über unseren globalen Zahlungsanbieter ab.',
    pay_note_eyebrow: 'Ihre Zahlungen sind sicher',
    pay_note_title: '256-Bit-Verschlüsselung',
    pay_note_text: 'Alle Transaktionen werden mit hoher Sicherheit über Paddle geschützt.',
    legal_eyebrow: 'Rechtliche Dokumente',
    privacy_title: 'Datenschutzerklärung',
    privacy_intro: 'Diese Datenschutzerklärung erläutert den Schutz Ihrer Daten bei CADRO.',
    privacy_p1: 'Wir verarbeiten nur die minimal erforderlichen Daten für einen reibungslosen Service.',
    privacy_p2: 'Abonnements werden von unserem globalen Zahlungspartner Paddle abgewickelt.',
    privacy_p3: 'Für Anfragen kontaktieren Sie info@cadro.io.',
    privacy_p4: 'Plattform-Anbieter: Turgay Bozkus.',
    terms_title: 'Nutzungsbedingungen',
    terms_intro: 'Die allgemeinen Nutzungsbedingungen für unseren Service.',
    terms_p1: 'CADRO ist ein Cloud-basierter Software-Service (SaaS).',
    terms_p2: 'Abo-Limits und Abrechnungszeiträume unterliegen den aktuellen Preisen.',
    terms_p3: 'Maßnahmen, die die Systemintegrität gefährden, gelten als Verstoß.',
    terms_p4: 'Für Fragen kontaktieren Sie den Service-Inhaber Turgay Bozkus.',
    refund_title: 'Rückerstattungsrichtlinie',
    refund_intro: 'Unsere Richtlinien zu Stornierungen und Rückerstattungen.',
    refund_p1: 'Ihr Konto bleibt nach Kündigung bis zum Ende des Abrechnungszyklus aktiv.',
    refund_p2: 'Teilrückerstattungen werden nicht gewährt, es sei denn bei technischen Fehlern.',
    refund_p3: 'Für Stornierungen schreiben Sie an info@cadro.io.',
    refund_p4: 'Ihre Zufriedenheit ist uns wichtig.',
    nav_menu: 'Menü',
    security_eyebrow: 'Sicherheitsansatz',
    security_title: 'Sichere Infrastruktur für Unternehmensdaten',
    security_text: 'CADRO stellt Sicherheit in den Mittelpunkt – mit Zugriffskontrollen, Verschlüsselung und Audits.',
    security_point_1_title: 'Rollenbasierter Zugriff',
    security_point_1_text: 'Nutzer sehen nur die Module und Datensätze, für die sie berechtigt sind.',
    security_point_2_title: 'Verschlüsselung & Backups',
    security_point_2_text: 'Daten werden verschlüsselt übertragen und regelmäßig gesichert.',
    security_point_3_title: 'Audit-Protokolle',
    security_point_3_text: 'Alle kritischen Aktionen werden nachvollziehbar protokolliert.',
    security_cta_eyebrow: 'Sicherheitsdokumente',
    security_cta_title: 'Gerne teilen wir die Sicherheitsdetails.',
    security_cta_contact: 'Sicherheitsdokumente anfordern',
    architecture_eyebrow: 'Architektur',
    architecture_title: 'Cloud-native, skalierbare Architektur',
    architecture_text: 'CADRO ist für wachsende Teams mit modularen Services und flexibler Infrastruktur gebaut.',
    architecture_point_1_title: 'Modulare Services',
    architecture_point_1_text: 'Jedes Modul arbeitet eigenständig und integriert sich sicher.',
    architecture_point_2_title: 'Hohe Performance',
    architecture_point_2_text: 'Stabile Nutzung auch bei Spitzenlast.',
    architecture_point_3_title: 'Stabilität & Observability',
    architecture_point_3_text: 'Service-Health, Fehler und Nutzung werden laufend überwacht.',
    architecture_cta_eyebrow: 'Technischer Austausch',
    architecture_cta_title: 'Lassen Sie uns die Architektur gemeinsam bewerten.',
    architecture_cta_contact: 'Technisches Gespräch anfragen',
    compliance_eyebrow: 'Konformität',
    compliance_title: 'KVKK- und DSGVO-konforme Prozesse',
    compliance_text: 'Datenminimierung, Aufbewahrung und Zugriffskontrollen sichern die Compliance.',
    compliance_point_1_title: 'Datenverarbeitungsprinzipien',
    compliance_point_1_text: 'Nur notwendige Daten werden mit Zweckbindung verarbeitet.',
    compliance_point_2_title: 'Transparenz & Hinweise',
    compliance_point_2_text: 'Mitarbeiter erhalten klare Informationen und Hinweise.',
    compliance_point_3_title: 'Löschung & Anonymisierung',
    compliance_point_3_text: 'Lösch- und Anonymisierungsprozesse auf Anfrage.',
    compliance_cta_eyebrow: 'Compliance Support',
    compliance_cta_title: 'Beschleunigen Sie Ihre KVKK/DSGVO-Compliance.',
    compliance_cta_contact: 'Compliance-Beratung anfragen',
    security_diagram_eyebrow: 'Technisches Diagramm',
    security_diagram_title: 'So greifen die Sicherheitslayer ineinander',
    security_diagram_text: 'Zugriffskontrolle, Verschlüsselung und Audits arbeiten zusammen.',
    security_diagram_node_1: 'Identität & Zugriff',
    security_diagram_node_2: 'Verschlüsselungsebene',
    security_diagram_node_3: 'Audit-Logs',
    security_standards_eyebrow: 'Standards',
    security_standards_title: 'Sicherheitspraktiken',
    security_standards_item_1: 'ISO-27001-nahe Prozesse',
    security_standards_item_2: 'Schlüsselmanagement und Verschlüsselungsrichtlinien',
    security_standards_item_3: 'Regelmäßige Penetrationstests',
    security_integrations_eyebrow: 'Integrationen',
    security_integrations_title: 'Enterprise-Identität',
    security_integrations_item_1: 'SSO',
    security_integrations_item_2: 'SAML',
    security_integrations_item_3: 'SCIM',
    security_integrations_text: 'Anbindung an Ihren IdP in Minuten.',
    architecture_diagram_eyebrow: 'Architekturdiagramm',
    architecture_diagram_title: 'Ein klarer Blick auf den CADRO-Stack',
    architecture_diagram_text: 'Modulare Services, Datenschicht und Observability sorgen für Stabilität.',
    architecture_diagram_node_1: 'Experience-Layer',
    architecture_diagram_node_2: 'Service-Layer',
    architecture_diagram_node_3: 'Daten & Storage',
    architecture_standards_eyebrow: 'Betrieb',
    architecture_standards_title: 'Betriebssicherheit',
    architecture_standards_item_1: 'High-Availability-Design',
    architecture_standards_item_2: 'Redundante Infrastruktur',
    architecture_standards_item_3: 'Kontinuierliches Monitoring',
    architecture_integrations_eyebrow: 'Integrationen',
    architecture_integrations_title: 'Identitätsintegrationen',
    architecture_integrations_item_1: 'SSO',
    architecture_integrations_item_2: 'SAML',
    architecture_integrations_item_3: 'SCIM',
    architecture_integrations_text: 'Kompatibel mit Enterprise-IdPs.',
    compliance_diagram_eyebrow: 'Compliance-Flow',
    compliance_diagram_title: 'Von Datenerfassung bis Löschung',
    compliance_diagram_text: 'Daten werden dokumentiert, gespeichert und regelkonform gelöscht.',
    compliance_diagram_node_1: 'Dateninventar',
    compliance_diagram_node_2: 'Aufbewahrung',
    compliance_diagram_node_3: 'Löschanfragen',
    compliance_standards_eyebrow: 'Standards',
    compliance_standards_title: 'Compliance-Schutz',
    compliance_standards_item_1: 'KVKK/DSGVO-Hinweise',
    compliance_standards_item_2: 'Verzeichnis der Verarbeitungstätigkeiten',
    compliance_standards_item_3: 'Löschung und Anonymisierung',
    compliance_integrations_eyebrow: 'Integrationen',
    compliance_integrations_title: 'Sicherer Zugriff',
    compliance_integrations_item_1: 'SSO',
    compliance_integrations_item_2: 'SAML',
    compliance_integrations_item_3: 'SCIM',
    compliance_integrations_text: 'Zugriffe über bestehende Identitätssysteme steuern.',
  };
