import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('tr'),
    Locale('en'),
    Locale('de'),
    Locale('ar'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_title': 'KOKPİT',
      'good_morning': 'Günaydın',
      'good_afternoon': 'İyi günler',
      'good_evening': 'İyi akşamlar',
      'login_title': 'Giriş',
      'email': 'E-posta',
      'password': 'Şifre',
      'continue': 'Devam Et',
      'loading': 'Yükleniyor...',
      'mfa_title': 'MFA',
      'verification_code': 'Doğrulama Kodu',
      'verifying': 'Doğrulanıyor...',
      'verify': 'Doğrula',
      'logout': 'Çıkış',
      'language': 'Dil',
      'today': 'Bugün',
      'overview': 'Genel Durum',
      'quick_access': 'Hızlı Erişim',
      'open_module': 'Modülü Aç',
      'upcoming_trainings': 'Yaklaşan Eğitimler',
      'security': 'Güvenlik',
      'pending_leaves': 'Bekleyen İzinler',
      'pending_expenses': 'Bekleyen Masraflar',
      'open_tickets': 'Açık Talepler',
      'assets': 'Zimmetler',
      'pending_docs': 'Bekleyen Evraklar',
      'trainings': 'Eğitimler',
      'registered_devices': 'Kayıtlı Cihazlar',
      'company_device_sessions': 'Şirket Cihaz Oturumları',
      'company_device_sessions_desc': 'Bu ekran şirket genelindeki aktif cihaz oturumlarını gösterir. Personel ve yönetim oturumları birlikte listelenir.',
      'admin_devices_empty': 'Şirket için henüz aktif cihaz oturumu bulunmuyor.',
      'admin_lite_title': 'Admin Lite',
      'approvals_overview': 'Onay Özeti',
      'admin_pending_queue': 'Bekleyen işler ve operasyon yoğunluğu',
      'admin_quick_actions': 'Hızlı Yönetim',
      'admin_quick_actions_desc': 'Sık kullanılan yönetim ekranlarına tek dokunuşla gidin.',
      'admin_activity': 'Canlı Yoğunluk',
      'admin_activity_desc': 'Şu an yönetim tarafında bekleyen temel iş yükü.',
      'admin_dashboard_load_failed': 'Admin paneli yüklenemedi.',
      'pending_total': 'Toplam Bekleyen',
      'admin_leave_queue_title': 'Bekleyen İzinler',
      'admin_expense_queue_title': 'Bekleyen Masraflar',
      'admin_document_queue_title': 'Bekleyen Evraklar',
      'admin_helpdesk_queue_title': 'Açık Talepler',
      'admin_no_pending_leaves': 'Bekleyen izin kaydı bulunmuyor.',
      'admin_no_pending_expenses': 'Bekleyen masraf kaydı bulunmuyor.',
      'admin_no_pending_documents': 'Bekleyen evrak bulunmuyor.',
      'admin_no_open_tickets': 'Açık helpdesk talebi bulunmuyor.',
      'review_leave_requests': 'İzin taleplerini gözden geçir',
      'review_leave_requests_desc': 'Bekleyen izin kayıtlarını aç ve değerlendir.',
      'review_expense_claims': 'Masraf beyanlarını gözden geçir',
      'review_expense_claims_desc': 'Masraf taleplerini ve fişleri incele.',
      'review_dossier_docs': 'E-Özlük evraklarını gözden geçir',
      'review_dossier_docs_desc': 'Bekleyen evrakları aç, kontrol et ve karara bağla.',
      'review_helpdesk_tickets': 'Helpdesk taleplerini gözden geçir',
      'review_helpdesk_tickets_desc': 'Açık destek kayıtlarını ve mesajları yönet.',
      'review_device_sessions_desc': 'Aktif cihaz oturumlarını ve güvenliği gözden geçir.',
      'could_not_load_devices': 'Cihazlar yüklenemedi',
      'notifications_center': 'Bildirim Merkezi',
      'notifications_summary': 'Bekleyen mobil işlemler özeti',
      'reports_web_only_title': 'Raporlar Web Uygulamada',
      'reports_web_only_desc': 'Detaylı rapor ve dışa aktarma işlemleri için web tarafını kullan.',
      'notifications_summary_unavailable': 'Bildirim özeti şu anda yüklenemiyor.',
      'tap_to_open_module': 'Modülü açmak için dokun',
      'enable_notifications': 'Bildirimleri Aç',
      'disable_notifications': 'Bildirimleri Kapat',
      'notifications_enabled': 'Bildirimler bu cihaz için açıldı.',
      'notifications_disabled': 'Bildirimler bu cihaz için kapatıldı.',
      'push_setup_ready': 'Push altyapısı hazır. Bu cihaz için bildirimleri etkinleştirebilirsin.',
      'push_setup_active': 'Bu cihaz için push bildirimi hazırlığı aktif.',
      'leave_title': 'İzin',
      'new_request': 'Yeni Talep',
      'my_leave_requests': 'İzin Taleplerim',
      'all_records': 'Tümü',
      'no_leave_records': 'Henüz izin kaydı yok.',
      'no_leave_for_filter': 'Bu filtre için izin kaydı bulunmuyor.',
      'annual': 'Yıllık',
      'annual_leave': 'Yıllık İzin',
      'sick': 'Hastalık',
      'sick_leave': 'Hastalık İzni',
      'unpaid': 'Ücretsiz',
      'unpaid_leave': 'Ücretsiz İzin',
      'maternity': 'Doğum İzni',
      'other': 'Diğer',
      'other_leave': 'Diğer İzin',
      'start_date': 'Başlangıç Tarihi',
      'end_date': 'Bitiş Tarihi',
      'total_days': 'Toplam Gün',
      'reason': 'Gerekçe',
      'submit': 'Gönder',
      'submitting': 'Gönderiliyor...',
      'expense_title': 'Masraflar',
      'new_expense': 'Yeni Masraf',
      'my_expense_claims': 'Masraf Beyanlarım',
      'expense_overview': 'Masraf Özeti',
      'pending': 'Bekliyor',
      'approved': 'Onaylandı',
      'paid': 'Ödendi',
      'total_claims': 'Toplam Kayıt',
      'total_amount': 'Toplam Tutar',
      'meal': 'Yemek',
      'transport': 'Ulaşım',
      'office': 'Ofis',
      'fuel': 'Yakıt',
      'accommodation': 'Konaklama',
      'choose_file': 'Dosya Seç',
      'take_photo': 'Fotoğraf Çek',
      'receipt_invoice': 'Fiş / Fatura',
      'open_receipt': 'Fişi Aç',
      'no_file_selected': 'Henüz dosya seçilmedi.',
      'helpdesk_title': 'Helpdesk',
      'new_ticket': 'Yeni Talep',
      'open_ticket': 'Talebi Aç',
      'my_tickets': 'Taleplerim',
      'all_tickets': 'Tümü',
      'ticket_detail': 'Talep Detayı',
      'write_message': 'Mesaj yaz...',
      'send': 'Gönder',
      'attach_file': 'Dosya Ekle',
      'open_attachment': 'Eki Aç',
      'category': 'Kategori',
      'priority': 'Öncelik',
      'subject': 'Konu',
      'message': 'Mesaj',
      'low': 'Düşük',
      'normal': 'Normal',
      'urgent': 'Acil',
      'it_support': 'IT Destek',
      'hr_request': 'İK Talebi',
      'administrative': 'İdari',
      'payroll': 'Bordro',
      'dossier_title': 'E-Özlük',
      'upload_document': 'Belge Yükle',
      'my_documents': 'Belgelerim',
      'upload_new_files': 'Yeni dosya yükleyin, durumları izleyin ve bekleyenleri silin.',
      'open': 'Aç',
      'delete': 'Sil',
      'document_type': 'Belge Türü',
      'leave_type': 'İzin Türü',
      'attendance_title': 'Zaman & Devamlılık',
      'last_30_records': 'Son 30 Kayıt',
      'clock_in': 'İşe Başla',
      'clock_out': 'Paydos Et',
      'torch': 'Flaş',
      'cancel': 'Vazgeç',
      'close': 'Kapat',
      'use_qr_text': 'QR Metnini Kullan',
      'web_fallback': 'Web yedeği',
      'status': 'Durum',
      'work_hours': 'Çalışma Saati',
      'check_in': 'Giriş',
      'check_out': 'Çıkış',
      'open_attendance': 'Puantajı Aç',
      'devices_empty': 'Bu hesap için henüz kayıtlı cihaz bulunmuyor.',
      'platform': 'Platform',
      'push_registered': 'Push Kayıtlı',
      'last_login': 'Son Giriş',
      'device_id': 'Cihaz ID',
      'current_device': 'Mevcut Cihaz',
      'this_session': 'Bu Oturum',
      'single_active_device': 'Tek Aktif Cihaz',
      'single_device_policy_title': 'Tek mobil cihaz politikası',
      'single_device_policy_desc': 'Bir kullanıcı aynı anda yalnızca tek mobil cihazda aktif kalır. Yeni bir cihazdan giriş yapılınca önceki aktif cihaz otomatik olarak listeden kaldırılır.',
      'single_device_policy_active_state': 'Bu cihaz hesabın aktif mobil oturumudur.',
      'device_switch_notice_single': 'Bu girişle önceki mobil cihaz oturumu kapatıldı.',
      'device_switch_notice_multi': 'Bu girişle önceki mobil cihaz oturumları kapatıldı.',
      'platform_web': 'Web',
      'platform_android': 'Android',
      'platform_ios': 'iPhone',
      'platform_macos': 'macOS',
      'year_label': 'Yıl',
      'used_days': 'Kullanılan Gün',
      'leave_types': 'İzin Türleri',
      'currency': 'Para Birimi',
      'description': 'Açıklama',
      'date': 'Tarih',
      'status_pending': 'Bekliyor',
      'status_approved': 'Onaylandı',
      'status_rejected': 'Reddedildi',
      'status_paid': 'Ödendi',
      'status_open': 'Açık',
      'status_in_progress': 'İşlemde',
      'status_resolved': 'Çözüldü',
      'status_present': 'Mevcut',
      'status_not_started': 'Başlamadı',
      'status_early_out': 'Erken Çıkış',
      'status_late_early_out': 'Geç Giriş / Erken Çıkış',
      'identity_copy': 'Kimlik Kopyası',
      'passport_copy': 'Pasaport Kopyası',
      'contract': 'Sözleşme',
      'certificate': 'Sertifika',
      'payroll_document': 'Bordro Belgesi',
      'upload_document_title': 'Belge Yükle',
      'uploaded_on': 'Yüklenme',
      'choose_document': 'Belge Seç',
      'uploading': 'Yükleniyor...',
      'choose_document_first': 'Lütfen önce bir belge seçin.',
      'document_upload_failed': 'Belge yüklenemedi.',
      'document_delete_failed': 'Belge silinemedi.',
      'no_documents_found': 'Henüz belge bulunmuyor.',
      'no_documents_for_filter': 'Bu filtre için belge bulunmuyor.',
      'no_support_tickets': 'Henüz destek talebi oluşturulmadı.',
      'no_tickets_for_filter': 'Bu filtre için talep bulunmuyor.',
      'ticket_detail_load_failed': 'Talep detayı yüklenemedi.',
      'ticket_message_failed': 'Mesaj gönderilemedi.',
      'ticket_create_failed': 'Talep oluşturulamadı.',
      'new_ticket_title': 'Yeni Talep',
      'add_file': 'Dosya Ekle',
      'submit_required_fields': 'Lütfen gerekli alanları doldurun.',
      'message_with_attachment': 'Ekli dosyayı inceleyin.',
      'camera_black_help': 'Chrome’da kamera siyah kalırsa QR metnini buraya yapıştırarak teste devam edin.',
      'camera_not_ready': 'Kamera henüz hazır değil.',
      'attendance_scan_validating': 'QR algılandı. Konum doğrulanıyor...',
      'attendance_action_failed': 'Puantaj işlemi başarısız oldu.',
      'attendance_paste_qr_first': 'Lütfen önce QR içeriğini yapıştırın.',
      'attendance_location_disabled': 'Konum servisleri kapalı.',
      'attendance_location_required': 'Puantaj için konum izni gerekli.',
      'secure_attendance': 'Güvenli Puantaj',
      'secure_attendance_desc': 'İşe giriş ve çıkıştan önce işyeri QR kodunu kamera ve GPS ile doğrulayın.',
      'no_attendance_records': 'Henüz puantaj kaydı bulunmuyor.',
      'form_validation_error': 'Lütfen tüm alanları doğru şekilde doldurun.',
      'leave_submit_failed': 'İzin talebi gönderilemedi.',
      'expense_submit_failed': 'Masraf gönderilemedi.',
      'no_expense_records': 'Henüz masraf kaydı bulunmuyor.',
      'no_expenses_for_filter': 'Bu filtre için masraf kaydı bulunmuyor.',
      'employee_role': 'Personel',
      'manager_role': 'Yönetici',
      'admin_role': 'Yönetici',
      'superadmin_role': 'Süperadmin',
      'status_on_time': 'Zamanında',
      'status_late': 'Geç',
      'status_absent': 'Yok',
      'attendance_record_details': 'Puantaj Detayı',
      'tap_to_view_details': 'Detayı görmek için dokun',
      'leave_request_details': 'İzin Detayı',
      'expense_details': 'Masraf Detayı',
      'document_details': 'Belge Detayı',
      'date_range': 'Tarih Aralığı',
      'file_name': 'Dosya Adı',
      'schedule_name': 'Mesai Planı',
      'schedule_type': 'Plan Türü',
      'scheduled_hours': 'Plan Saatleri',
      'late_minutes': 'Geç Kalma',
      'early_leave_minutes': 'Erken Çıkış',
      'overtime_minutes': 'Fazla Mesai',
      'violation': 'İhlal',
      'approval_status': 'Onay Durumu',
      'none': 'Yok',
      'minutes_short': 'dk',
      'schedule_type_fixed': 'Sabit',
      'schedule_type_flex': 'Esnek',
      'violation_none': 'İhlal yok',
      'violation_late_in': 'Geç giriş',
      'violation_early_out': 'Erken çıkış',
      'violation_late_in_early_out': 'Geç giriş / erken çıkış',
      'violation_missing_clock_in': 'İşe giriş kaydı eksik',
      'violation_missing_clock_out': 'İşten çıkış kaydı eksik',
      'not_available': 'Mevcut değil',
      'to_be_announced': 'Duyurulacak',
      'quick_profile': 'Hızlı Profil',
      'phone': 'Telefon',
      'department': 'Departman',
      'position': 'Pozisyon',
      'home_load_failed': 'Ana ekran verisi yüklenemedi.',
      'no_upcoming_training': 'Yaklaşan eğitim yok',
      'assigned_sessions_here': 'Atanan oturumlar burada otomatik görünür.',
      'selected_file': 'Seçilen dosya',
      'captured_photo': 'Çekilen fotoğraf',
      'optimized_file': 'optimize edildi',
      'yes': 'Evet',
      'no': 'Hayır',
    },
    'en': {
      'app_title': 'COCKPIT',
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'login_title': 'Login',
      'email': 'Email',
      'password': 'Password',
      'continue': 'Continue',
      'loading': 'Loading...',
      'mfa_title': 'MFA',
      'verification_code': 'Verification Code',
      'verifying': 'Verifying...',
      'verify': 'Verify',
      'logout': 'Logout',
      'language': 'Language',
      'today': 'Today',
      'overview': 'Overview',
      'quick_access': 'Quick Access',
      'open_module': 'Open Module',
      'upcoming_trainings': 'Upcoming Trainings',
      'security': 'Security',
      'pending_leaves': 'Pending Leaves',
      'pending_expenses': 'Pending Expenses',
      'open_tickets': 'Open Tickets',
      'assets': 'Assets',
      'pending_docs': 'Pending Docs',
      'trainings': 'Trainings',
      'registered_devices': 'Registered Devices',
      'company_device_sessions': 'Company Device Sessions',
      'company_device_sessions_desc': 'This screen shows active device sessions across the company. Employee and admin sessions are listed together.',
      'admin_devices_empty': 'No active device sessions were found for the company.',
      'admin_lite_title': 'Admin Lite',
      'approvals_overview': 'Approvals Overview',
      'admin_pending_queue': 'Pending work and operational workload',
      'admin_quick_actions': 'Quick Admin Actions',
      'admin_quick_actions_desc': 'Open the most used admin screens with one tap.',
      'admin_activity': 'Live Workload',
      'admin_activity_desc': 'Current management-side pending workload.',
      'admin_dashboard_load_failed': 'Admin dashboard could not be loaded.',
      'pending_total': 'Total Pending',
      'admin_leave_queue_title': 'Pending Leaves',
      'admin_expense_queue_title': 'Pending Expenses',
      'admin_document_queue_title': 'Pending Documents',
      'admin_helpdesk_queue_title': 'Open Tickets',
      'admin_no_pending_leaves': 'No pending leave requests found.',
      'admin_no_pending_expenses': 'No pending expense claims found.',
      'admin_no_pending_documents': 'No pending documents found.',
      'admin_no_open_tickets': 'No open helpdesk tickets found.',
      'review_leave_requests': 'Review leave requests',
      'review_leave_requests_desc': 'Open and evaluate pending leave records.',
      'review_expense_claims': 'Review expense claims',
      'review_expense_claims_desc': 'Inspect submitted expenses and receipts.',
      'review_dossier_docs': 'Review dossier documents',
      'review_dossier_docs_desc': 'Open pending documents, inspect and decide.',
      'review_helpdesk_tickets': 'Review helpdesk tickets',
      'review_helpdesk_tickets_desc': 'Manage open support items and messages.',
      'review_device_sessions_desc': 'Review active device sessions and security.',
      'could_not_load_devices': 'Could not load devices',
      'notifications_center': 'Notifications',
      'notifications_summary': 'Summary of pending mobile actions',
      'reports_web_only_title': 'Reports Are on Web',
      'reports_web_only_desc': 'Use the web app for detailed reports and export actions.',
      'notifications_summary_unavailable': 'Notification summary is unavailable right now.',
      'tap_to_open_module': 'Tap to open the module',
      'enable_notifications': 'Enable Notifications',
      'disable_notifications': 'Disable Notifications',
      'notifications_enabled': 'Notifications were enabled for this device.',
      'notifications_disabled': 'Notifications were disabled for this device.',
      'push_setup_ready': 'Push infrastructure is ready. You can enable notifications for this device.',
      'push_setup_active': 'Push notification preparation is active for this device.',
      'leave_title': 'Leave',
      'new_request': 'New Request',
      'my_leave_requests': 'My Leave Requests',
      'all_records': 'All',
      'no_leave_records': 'No leave records found yet.',
      'no_leave_for_filter': 'No leave records found for this filter.',
      'annual': 'Annual',
      'annual_leave': 'Annual Leave',
      'sick': 'Sick',
      'sick_leave': 'Sick Leave',
      'unpaid': 'Unpaid',
      'unpaid_leave': 'Unpaid Leave',
      'maternity': 'Maternity Leave',
      'other': 'Other',
      'other_leave': 'Other Leave',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'total_days': 'Total Days',
      'reason': 'Reason',
      'submit': 'Submit',
      'submitting': 'Submitting...',
      'expense_title': 'Expenses',
      'new_expense': 'New Expense',
      'my_expense_claims': 'My Expense Claims',
      'expense_overview': 'Expense Overview',
      'pending': 'Pending',
      'approved': 'Approved',
      'paid': 'Paid',
      'total_claims': 'Total Claims',
      'total_amount': 'Total Amount',
      'meal': 'Meal',
      'transport': 'Transport',
      'office': 'Office',
      'fuel': 'Fuel',
      'accommodation': 'Accommodation',
      'choose_file': 'Choose File',
      'take_photo': 'Take Photo',
      'receipt_invoice': 'Receipt / Invoice',
      'open_receipt': 'Open Receipt',
      'no_file_selected': 'No file selected yet.',
      'helpdesk_title': 'Helpdesk',
      'new_ticket': 'New Ticket',
      'open_ticket': 'Open Ticket',
      'my_tickets': 'My Tickets',
      'all_tickets': 'All',
      'ticket_detail': 'Ticket Detail',
      'write_message': 'Write a message...',
      'send': 'Send',
      'attach_file': 'Attach File',
      'open_attachment': 'Open Attachment',
      'category': 'Category',
      'priority': 'Priority',
      'subject': 'Subject',
      'message': 'Message',
      'low': 'Low',
      'normal': 'Normal',
      'urgent': 'Urgent',
      'it_support': 'IT Support',
      'hr_request': 'HR Request',
      'administrative': 'Administrative',
      'payroll': 'Payroll',
      'dossier_title': 'E-Dossier',
      'upload_document': 'Upload Document',
      'my_documents': 'My Documents',
      'upload_new_files': 'Upload new files, review statuses and remove pending ones.',
      'open': 'Open',
      'delete': 'Delete',
      'document_type': 'Document Type',
      'leave_type': 'Leave Type',
      'attendance_title': 'Time & Attendance',
      'last_30_records': 'Last 30 Records',
      'clock_in': 'Clock In',
      'clock_out': 'Clock Out',
      'torch': 'Torch',
      'cancel': 'Cancel',
      'close': 'Close',
      'use_qr_text': 'Use QR Text',
      'web_fallback': 'Web fallback',
      'status': 'Status',
      'work_hours': 'Work Hours',
      'check_in': 'Check-in',
      'check_out': 'Check-out',
      'open_attendance': 'Open attendance',
      'devices_empty': 'No registered devices found for this account yet.',
      'platform': 'Platform',
      'push_registered': 'Push Registered',
      'last_login': 'Last Login',
      'device_id': 'Device ID',
      'current_device': 'Current Device',
      'this_session': 'This Session',
      'single_active_device': 'Single Active Device',
      'single_device_policy_title': 'Single mobile device policy',
      'single_device_policy_desc': 'A user can stay active on only one mobile device at a time. Signing in on a new device automatically removes the previous active device from the list.',
      'single_device_policy_active_state': 'This device is the active mobile session for your account.',
      'device_switch_notice_single': 'The previous mobile device session was closed during this sign-in.',
      'device_switch_notice_multi': 'Previous mobile device sessions were closed during this sign-in.',
      'platform_web': 'Web',
      'platform_android': 'Android',
      'platform_ios': 'iPhone',
      'platform_macos': 'macOS',
      'year_label': 'Year',
      'used_days': 'Used Days',
      'leave_types': 'Leave Types',
      'currency': 'Currency',
      'description': 'Description',
      'date': 'Date',
      'status_pending': 'Pending',
      'status_approved': 'Approved',
      'status_rejected': 'Rejected',
      'status_paid': 'Paid',
      'status_open': 'Open',
      'status_in_progress': 'In Progress',
      'status_resolved': 'Resolved',
      'status_present': 'Present',
      'status_not_started': 'Not Started',
      'status_early_out': 'Early Out',
      'status_late_early_out': 'Late In / Early Out',
      'identity_copy': 'Identity Copy',
      'passport_copy': 'Passport Copy',
      'contract': 'Contract',
      'certificate': 'Certificate',
      'payroll_document': 'Payroll Document',
      'upload_document_title': 'Upload Document',
      'uploaded_on': 'Uploaded',
      'choose_document': 'Choose Document',
      'uploading': 'Uploading...',
      'choose_document_first': 'Please choose a document first.',
      'document_upload_failed': 'Document could not be uploaded.',
      'document_delete_failed': 'Document could not be deleted.',
      'no_documents_found': 'No documents found yet.',
      'no_documents_for_filter': 'No documents found for this filter.',
      'no_support_tickets': 'No support ticket has been created yet.',
      'no_tickets_for_filter': 'No tickets found for this filter.',
      'ticket_detail_load_failed': 'Ticket detail could not be loaded.',
      'ticket_message_failed': 'Message could not be sent.',
      'ticket_create_failed': 'Ticket could not be created.',
      'new_ticket_title': 'New Ticket',
      'add_file': 'Add File',
      'submit_required_fields': 'Please complete all required fields.',
      'message_with_attachment': 'Please see the attached file.',
      'camera_black_help': 'If the camera preview stays black in Chrome, paste the QR payload here to continue testing.',
      'camera_not_ready': 'Camera is not ready yet.',
      'attendance_scan_validating': 'QR detected. Validating location...',
      'attendance_action_failed': 'Attendance action failed.',
      'attendance_paste_qr_first': 'Please paste the QR payload first.',
      'attendance_location_disabled': 'Location services are disabled.',
      'attendance_location_required': 'Location permission is required for attendance.',
      'secure_attendance': 'Secure Attendance',
      'secure_attendance_desc': 'Use camera and GPS to validate the workplace QR code before clocking in or out.',
      'no_attendance_records': 'No attendance records found yet.',
      'form_validation_error': 'Please complete all fields correctly.',
      'leave_submit_failed': 'Leave request could not be submitted.',
      'expense_submit_failed': 'Expense could not be submitted.',
      'no_expense_records': 'No expense records found yet.',
      'no_expenses_for_filter': 'No expense records found for this filter.',
      'employee_role': 'Employee',
      'manager_role': 'Manager',
      'admin_role': 'Admin',
      'superadmin_role': 'Superadmin',
      'status_on_time': 'On Time',
      'status_late': 'Late',
      'status_absent': 'Absent',
      'attendance_record_details': 'Attendance Details',
      'tap_to_view_details': 'Tap to view details',
      'leave_request_details': 'Leave Details',
      'expense_details': 'Expense Details',
      'document_details': 'Document Details',
      'date_range': 'Date Range',
      'file_name': 'File Name',
      'schedule_name': 'Work Schedule',
      'schedule_type': 'Schedule Type',
      'scheduled_hours': 'Scheduled Hours',
      'late_minutes': 'Late Minutes',
      'early_leave_minutes': 'Early Leave',
      'overtime_minutes': 'Overtime',
      'violation': 'Violation',
      'approval_status': 'Approval Status',
      'none': 'None',
      'minutes_short': 'min',
      'schedule_type_fixed': 'Fixed',
      'schedule_type_flex': 'Flex',
      'violation_none': 'No violation',
      'violation_late_in': 'Late in',
      'violation_early_out': 'Early out',
      'violation_late_in_early_out': 'Late in / early out',
      'violation_missing_clock_in': 'Missing clock-in',
      'violation_missing_clock_out': 'Missing clock-out',
      'not_available': 'Not available',
      'to_be_announced': 'TBA',
      'quick_profile': 'Quick Profile',
      'phone': 'Phone',
      'department': 'Department',
      'position': 'Position',
      'home_load_failed': 'Home data could not be loaded.',
      'no_upcoming_training': 'No upcoming training scheduled',
      'assigned_sessions_here': 'Assigned sessions will appear here automatically.',
      'selected_file': 'Selected file',
      'captured_photo': 'Captured photo',
      'optimized_file': 'optimized',
      'yes': 'Yes',
      'no': 'No',
    },
    'de': {
      'app_title': 'COCKPIT',
      'good_morning': 'Guten Morgen',
      'good_afternoon': 'Guten Tag',
      'good_evening': 'Guten Abend',
      'login_title': 'Anmeldung',
      'email': 'E-Mail',
      'password': 'Passwort',
      'continue': 'Weiter',
      'loading': 'Wird geladen...',
      'mfa_title': 'MFA',
      'verification_code': 'Bestätigungscode',
      'verifying': 'Wird geprüft...',
      'verify': 'Bestätigen',
      'logout': 'Abmelden',
      'language': 'Sprache',
      'today': 'Heute',
      'overview': 'Übersicht',
      'quick_access': 'Schnellzugriff',
      'open_module': 'Modul öffnen',
      'upcoming_trainings': 'Bevorstehende Schulungen',
      'security': 'Sicherheit',
      'pending_leaves': 'Offene Urlaube',
      'pending_expenses': 'Offene Spesen',
      'open_tickets': 'Offene Tickets',
      'assets': 'Inventar',
      'pending_docs': 'Offene Dokumente',
      'trainings': 'Schulungen',
      'registered_devices': 'Registrierte Geräte',
      'company_device_sessions': 'Gerätesitzungen des Unternehmens',
      'company_device_sessions_desc': 'Dieser Bildschirm zeigt aktive Gerätesitzungen im gesamten Unternehmen. Mitarbeiter- und Admin-Sitzungen werden gemeinsam gelistet.',
      'admin_devices_empty': 'Für das Unternehmen wurden noch keine aktiven Gerätesitzungen gefunden.',
      'admin_lite_title': 'Admin Lite',
      'approvals_overview': 'Freigabeübersicht',
      'admin_pending_queue': 'Offene Aufgaben und operative Auslastung',
      'admin_quick_actions': 'Schnellaktionen',
      'admin_quick_actions_desc': 'Öffnen Sie häufig genutzte Verwaltungsbereiche mit einem Tipp.',
      'admin_activity': 'Live-Auslastung',
      'admin_activity_desc': 'Aktuell ausstehende Arbeitslast auf Management-Seite.',
      'admin_dashboard_load_failed': 'Admin-Dashboard konnte nicht geladen werden.',
      'pending_total': 'Gesamt offen',
      'admin_leave_queue_title': 'Offene Urlaubsanträge',
      'admin_expense_queue_title': 'Offene Spesen',
      'admin_document_queue_title': 'Offene Dokumente',
      'admin_helpdesk_queue_title': 'Offene Tickets',
      'admin_no_pending_leaves': 'Keine offenen Urlaubsanträge gefunden.',
      'admin_no_pending_expenses': 'Keine offenen Spesen gefunden.',
      'admin_no_pending_documents': 'Keine offenen Dokumente gefunden.',
      'admin_no_open_tickets': 'Keine offenen Helpdesk-Tickets gefunden.',
      'review_leave_requests': 'Urlaubsanträge prüfen',
      'review_leave_requests_desc': 'Offene Urlaubsanträge öffnen und bewerten.',
      'review_expense_claims': 'Spesenanträge prüfen',
      'review_expense_claims_desc': 'Spesen und Belege prüfen.',
      'review_dossier_docs': 'E-Akte Dokumente prüfen',
      'review_dossier_docs_desc': 'Offene Dokumente öffnen, prüfen und entscheiden.',
      'review_helpdesk_tickets': 'Helpdesk-Tickets prüfen',
      'review_helpdesk_tickets_desc': 'Offene Supportfälle und Nachrichten verwalten.',
      'review_device_sessions_desc': 'Aktive Gerätesitzungen und Sicherheit prüfen.',
      'could_not_load_devices': 'Geräte konnten nicht geladen werden',
      'notifications_center': 'Benachrichtigungen',
      'notifications_summary': 'Zusammenfassung offener mobiler Aufgaben',
      'reports_web_only_title': 'Berichte im Web',
      'reports_web_only_desc': 'Nutzen Sie die Web-App für detaillierte Berichte und Exporte.',
      'notifications_summary_unavailable': 'Die Benachrichtigungsübersicht ist derzeit nicht verfügbar.',
      'tap_to_open_module': 'Tippen, um das Modul zu öffnen',
      'enable_notifications': 'Benachrichtigungen aktivieren',
      'disable_notifications': 'Benachrichtigungen deaktivieren',
      'notifications_enabled': 'Benachrichtigungen wurden für dieses Gerät aktiviert.',
      'notifications_disabled': 'Benachrichtigungen wurden für dieses Gerät deaktiviert.',
      'push_setup_ready': 'Die Push-Infrastruktur ist bereit. Sie können Benachrichtigungen für dieses Gerät aktivieren.',
      'push_setup_active': 'Die Push-Vorbereitung ist für dieses Gerät aktiv.',
      'leave_title': 'Urlaub',
      'new_request': 'Neue Anfrage',
      'my_leave_requests': 'Meine Urlaubsanträge',
      'all_records': 'Alle',
      'no_leave_records': 'Noch keine Urlaubsanträge vorhanden.',
      'no_leave_for_filter': 'Für diesen Filter wurden keine Urlaubsanträge gefunden.',
      'annual': 'Jahresurlaub',
      'annual_leave': 'Jahresurlaub',
      'sick': 'Krankheit',
      'sick_leave': 'Krankheitsurlaub',
      'unpaid': 'Unbezahlt',
      'unpaid_leave': 'Unbezahlter Urlaub',
      'maternity': 'Mutterschaftsurlaub',
      'other': 'Sonstiges',
      'other_leave': 'Sonstiger Urlaub',
      'start_date': 'Startdatum',
      'end_date': 'Enddatum',
      'total_days': 'Gesamttage',
      'reason': 'Grund',
      'submit': 'Senden',
      'submitting': 'Wird gesendet...',
      'expense_title': 'Spesen',
      'new_expense': 'Neue Spese',
      'my_expense_claims': 'Meine Spesenanträge',
      'expense_overview': 'Spesenübersicht',
      'pending': 'Ausstehend',
      'approved': 'Genehmigt',
      'paid': 'Bezahlt',
      'total_claims': 'Gesamtanzahl',
      'total_amount': 'Gesamtsumme',
      'meal': 'Verpflegung',
      'transport': 'Transport',
      'office': 'Büro',
      'fuel': 'Kraftstoff',
      'accommodation': 'Unterkunft',
      'choose_file': 'Datei wählen',
      'take_photo': 'Foto aufnehmen',
      'receipt_invoice': 'Beleg / Rechnung',
      'open_receipt': 'Beleg öffnen',
      'no_file_selected': 'Noch keine Datei ausgewählt.',
      'helpdesk_title': 'Helpdesk',
      'new_ticket': 'Neues Ticket',
      'open_ticket': 'Ticket öffnen',
      'my_tickets': 'Meine Tickets',
      'all_tickets': 'Alle',
      'ticket_detail': 'Ticketdetails',
      'write_message': 'Nachricht schreiben...',
      'send': 'Senden',
      'attach_file': 'Datei anhängen',
      'open_attachment': 'Anhang öffnen',
      'category': 'Kategorie',
      'priority': 'Priorität',
      'subject': 'Betreff',
      'message': 'Nachricht',
      'low': 'Niedrig',
      'normal': 'Normal',
      'urgent': 'Dringend',
      'it_support': 'IT-Support',
      'hr_request': 'HR-Anfrage',
      'administrative': 'Verwaltung',
      'payroll': 'Lohnabrechnung',
      'dossier_title': 'E-Akte',
      'upload_document': 'Dokument hochladen',
      'my_documents': 'Meine Dokumente',
      'upload_new_files': 'Neue Dateien hochladen, Status prüfen und offene löschen.',
      'open': 'Öffnen',
      'delete': 'Löschen',
      'document_type': 'Dokumenttyp',
      'leave_type': 'Urlaubsart',
      'attendance_title': 'Zeit & Anwesenheit',
      'last_30_records': 'Letzte 30 Einträge',
      'clock_in': 'Arbeitsbeginn',
      'clock_out': 'Feierabend',
      'torch': 'Licht',
      'cancel': 'Abbrechen',
      'close': 'Schließen',
      'use_qr_text': 'QR-Text verwenden',
      'web_fallback': 'Web-Fallback',
      'status': 'Status',
      'work_hours': 'Arbeitsstunden',
      'check_in': 'Kommen',
      'check_out': 'Gehen',
      'open_attendance': 'Anwesenheit öffnen',
      'devices_empty': 'Für dieses Konto wurden noch keine Geräte registriert.',
      'platform': 'Plattform',
      'push_registered': 'Push registriert',
      'last_login': 'Letzte Anmeldung',
      'device_id': 'Geräte-ID',
      'current_device': 'Aktuelles Gerät',
      'this_session': 'Diese Sitzung',
      'single_active_device': 'Einzig aktives Gerät',
      'single_device_policy_title': 'Richtlinie für ein mobiles Gerät',
      'single_device_policy_desc': 'Ein Benutzer kann jeweils nur auf einem mobilen Gerät aktiv sein. Bei einer Anmeldung auf einem neuen Gerät wird das zuvor aktive Gerät automatisch aus der Liste entfernt.',
      'single_device_policy_active_state': 'Dieses Gerät ist die aktive mobile Sitzung für dein Konto.',
      'device_switch_notice_single': 'Die vorherige mobile Gerätesitzung wurde bei dieser Anmeldung beendet.',
      'device_switch_notice_multi': 'Vorherige mobile Gerätesitzungen wurden bei dieser Anmeldung beendet.',
      'platform_web': 'Web',
      'platform_android': 'Android',
      'platform_ios': 'iPhone',
      'platform_macos': 'macOS',
      'year_label': 'Jahr',
      'used_days': 'Genutzte Tage',
      'leave_types': 'Urlaubsarten',
      'currency': 'Währung',
      'description': 'Beschreibung',
      'date': 'Datum',
      'status_pending': 'Ausstehend',
      'status_approved': 'Genehmigt',
      'status_rejected': 'Abgelehnt',
      'status_paid': 'Bezahlt',
      'status_open': 'Offen',
      'status_in_progress': 'In Bearbeitung',
      'status_resolved': 'Gelöst',
      'status_present': 'Anwesend',
      'status_not_started': 'Nicht gestartet',
      'status_early_out': 'Früher Ausstieg',
      'status_late_early_out': 'Spät / Früher Ausstieg',
      'identity_copy': 'Ausweiskopie',
      'passport_copy': 'Passkopie',
      'contract': 'Vertrag',
      'certificate': 'Zertifikat',
      'payroll_document': 'Lohnunterlage',
      'upload_document_title': 'Dokument hochladen',
      'uploaded_on': 'Hochgeladen',
      'choose_document': 'Dokument wählen',
      'uploading': 'Wird hochgeladen...',
      'choose_document_first': 'Bitte zuerst ein Dokument auswählen.',
      'document_upload_failed': 'Dokument konnte nicht hochgeladen werden.',
      'document_delete_failed': 'Dokument konnte nicht gelöscht werden.',
      'no_documents_found': 'Noch keine Dokumente vorhanden.',
      'no_documents_for_filter': 'Für diesen Filter wurden keine Dokumente gefunden.',
      'no_support_tickets': 'Es wurde noch kein Support-Ticket erstellt.',
      'no_tickets_for_filter': 'Für diesen Filter wurden keine Tickets gefunden.',
      'ticket_detail_load_failed': 'Ticketdetails konnten nicht geladen werden.',
      'ticket_message_failed': 'Nachricht konnte nicht gesendet werden.',
      'ticket_create_failed': 'Ticket konnte nicht erstellt werden.',
      'new_ticket_title': 'Neues Ticket',
      'add_file': 'Datei hinzufügen',
      'submit_required_fields': 'Bitte alle Pflichtfelder ausfüllen.',
      'message_with_attachment': 'Bitte den Anhang prüfen.',
      'camera_black_help': 'Wenn die Kameravorschau in Chrome schwarz bleibt, fügen Sie hier den QR-Inhalt ein und fahren Sie mit dem Test fort.',
      'camera_not_ready': 'Kamera ist noch nicht bereit.',
      'attendance_scan_validating': 'QR erkannt. Standort wird geprüft...',
      'attendance_action_failed': 'Zeiterfassungsaktion fehlgeschlagen.',
      'attendance_paste_qr_first': 'Bitte zuerst den QR-Inhalt einfügen.',
      'attendance_location_disabled': 'Ortungsdienste sind deaktiviert.',
      'attendance_location_required': 'Für die Zeiterfassung ist Standortzugriff erforderlich.',
      'secure_attendance': 'Sichere Zeiterfassung',
      'secure_attendance_desc': 'Prüfen Sie den QR-Code des Arbeitsplatzes vor dem Ein- oder Ausstempeln mit Kamera und GPS.',
      'no_attendance_records': 'Noch keine Zeiterfassungsdaten vorhanden.',
      'form_validation_error': 'Bitte alle Felder korrekt ausfüllen.',
      'leave_submit_failed': 'Urlaubsantrag konnte nicht gesendet werden.',
      'expense_submit_failed': 'Spesen konnten nicht gesendet werden.',
      'no_expense_records': 'Noch keine Spesen erfasst.',
      'no_expenses_for_filter': 'Für diesen Filter wurden keine Spesen gefunden.',
      'employee_role': 'Mitarbeiter',
      'manager_role': 'Manager',
      'admin_role': 'Admin',
      'superadmin_role': 'Superadmin',
      'status_on_time': 'Pünktlich',
      'status_late': 'Verspätet',
      'status_absent': 'Abwesend',
      'attendance_record_details': 'Anwesenheitsdetails',
      'tap_to_view_details': 'Zum Anzeigen antippen',
      'leave_request_details': 'Urlaubsdetails',
      'expense_details': 'Spesendetails',
      'document_details': 'Dokumentdetails',
      'date_range': 'Datumsbereich',
      'file_name': 'Dateiname',
      'schedule_name': 'Arbeitszeitplan',
      'schedule_type': 'Plantyp',
      'scheduled_hours': 'Geplante Stunden',
      'late_minutes': 'Verspätung',
      'early_leave_minutes': 'Früher Ausstieg',
      'overtime_minutes': 'Überstunden',
      'violation': 'Verstoß',
      'approval_status': 'Freigabestatus',
      'none': 'Keine',
      'minutes_short': 'Min',
      'schedule_type_fixed': 'Fest',
      'schedule_type_flex': 'Flex',
      'violation_none': 'Kein Verstoß',
      'violation_late_in': 'Verspäteter Einstieg',
      'violation_early_out': 'Früher Ausstieg',
      'violation_late_in_early_out': 'Verspätet / früher Ausstieg',
      'violation_missing_clock_in': 'Einstempeln fehlt',
      'violation_missing_clock_out': 'Ausstempeln fehlt',
      'not_available': 'Nicht verfügbar',
      'to_be_announced': 'Noch offen',
      'quick_profile': 'Kurzprofil',
      'phone': 'Telefon',
      'department': 'Abteilung',
      'position': 'Position',
      'home_load_failed': 'Startseitendaten konnten nicht geladen werden.',
      'no_upcoming_training': 'Keine geplanten Schulungen',
      'assigned_sessions_here': 'Zugewiesene Sitzungen erscheinen hier automatisch.',
      'selected_file': 'Ausgewählte Datei',
      'captured_photo': 'Aufgenommenes Foto',
      'optimized_file': 'optimiert',
      'yes': 'Ja',
      'no': 'Nein',
    },
    'ar': {
      'app_title': 'لوحة القيادة',
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',
      'login_title': 'تسجيل الدخول',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'continue': 'متابعة',
      'loading': 'جارٍ التحميل...',
      'mfa_title': 'التحقق المتعدد',
      'verification_code': 'رمز التحقق',
      'verifying': 'جارٍ التحقق...',
      'verify': 'تحقق',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'today': 'اليوم',
      'overview': 'نظرة عامة',
      'quick_access': 'وصول سريع',
      'open_module': 'فتح الوحدة',
      'upcoming_trainings': 'التدريبات القادمة',
      'security': 'الأمان',
      'pending_leaves': 'الإجازات المعلقة',
      'pending_expenses': 'المصاريف المعلقة',
      'open_tickets': 'الطلبات المفتوحة',
      'assets': 'العهد',
      'pending_docs': 'الوثائق المعلقة',
      'trainings': 'التدريبات',
      'registered_devices': 'الأجهزة المسجلة',
      'company_device_sessions': 'جلسات أجهزة الشركة',
      'company_device_sessions_desc': 'تعرض هذه الشاشة جلسات الأجهزة النشطة على مستوى الشركة. يتم عرض جلسات الموظفين والإدارة معًا.',
      'admin_devices_empty': 'لا توجد جلسات أجهزة نشطة للشركة حاليًا.',
      'admin_lite_title': 'إدارة خفيفة',
      'approvals_overview': 'ملخص الموافقات',
      'admin_pending_queue': 'الأعمال المعلقة والضغط التشغيلي',
      'admin_quick_actions': 'إجراءات سريعة',
      'admin_quick_actions_desc': 'افتح أكثر شاشات الإدارة استخدامًا بلمسة واحدة.',
      'admin_activity': 'عبء العمل الحالي',
      'admin_activity_desc': 'الأعمال الإدارية المعلقة حالياً.',
      'admin_dashboard_load_failed': 'تعذر تحميل لوحة الإدارة.',
      'pending_total': 'إجمالي المعلق',
      'admin_leave_queue_title': 'طلبات الإجازة المعلقة',
      'admin_expense_queue_title': 'المصروفات المعلقة',
      'admin_document_queue_title': 'المستندات المعلقة',
      'admin_helpdesk_queue_title': 'التذاكر المفتوحة',
      'admin_no_pending_leaves': 'لا توجد طلبات إجازة معلقة.',
      'admin_no_pending_expenses': 'لا توجد مطالبات مصروفات معلقة.',
      'admin_no_pending_documents': 'لا توجد مستندات معلقة.',
      'admin_no_open_tickets': 'لا توجد تذاكر دعم مفتوحة.',
      'review_leave_requests': 'مراجعة طلبات الإجازة',
      'review_leave_requests_desc': 'افتح طلبات الإجازة المعلقة وقيّمها.',
      'review_expense_claims': 'مراجعة المصروفات',
      'review_expense_claims_desc': 'راجع المصروفات والإيصالات المرسلة.',
      'review_dossier_docs': 'مراجعة مستندات الملف الوظيفي',
      'review_dossier_docs_desc': 'افتح المستندات المعلقة وافحصها واتخذ القرار.',
      'review_helpdesk_tickets': 'مراجعة تذاكر الدعم',
      'review_helpdesk_tickets_desc': 'أدر طلبات الدعم المفتوحة والرسائل.',
      'review_device_sessions_desc': 'راجع جلسات الأجهزة النشطة وحالة الأمان.',
      'could_not_load_devices': 'تعذر تحميل الأجهزة',
      'notifications_center': 'مركز الإشعارات',
      'notifications_summary': 'ملخص الإجراءات المعلقة على الجوال',
      'reports_web_only_title': 'التقارير عبر الويب',
      'reports_web_only_desc': 'استخدم تطبيق الويب للتقارير التفصيلية وعمليات التصدير.',
      'notifications_summary_unavailable': 'ملخص الإشعارات غير متاح حالياً.',
      'tap_to_open_module': 'اضغط لفتح الوحدة',
      'enable_notifications': 'تفعيل الإشعارات',
      'disable_notifications': 'إيقاف الإشعارات',
      'notifications_enabled': 'تم تفعيل الإشعارات لهذا الجهاز.',
      'notifications_disabled': 'تم إيقاف الإشعارات لهذا الجهاز.',
      'push_setup_ready': 'بنية الإشعارات جاهزة. يمكنك تفعيل الإشعارات لهذا الجهاز.',
      'push_setup_active': 'تجهيز الإشعارات لهذا الجهاز مفعل حالياً.',
      'leave_title': 'الإجازات',
      'new_request': 'طلب جديد',
      'my_leave_requests': 'طلباتي',
      'all_records': 'الكل',
      'no_leave_records': 'لا توجد طلبات إجازة بعد.',
      'no_leave_for_filter': 'لا توجد سجلات إجازة لهذا الفلتر.',
      'annual': 'سنوية',
      'annual_leave': 'إجازة سنوية',
      'sick': 'مرضية',
      'sick_leave': 'إجازة مرضية',
      'unpaid': 'غير مدفوعة',
      'unpaid_leave': 'إجازة غير مدفوعة',
      'maternity': 'إجازة أمومة',
      'other': 'أخرى',
      'other_leave': 'إجازة أخرى',
      'start_date': 'تاريخ البداية',
      'end_date': 'تاريخ النهاية',
      'total_days': 'إجمالي الأيام',
      'reason': 'السبب',
      'submit': 'إرسال',
      'submitting': 'جارٍ الإرسال...',
      'expense_title': 'المصاريف',
      'new_expense': 'مصروف جديد',
      'my_expense_claims': 'مطالبات المصاريف',
      'expense_overview': 'ملخص المصاريف',
      'pending': 'قيد الانتظار',
      'approved': 'تمت الموافقة',
      'paid': 'مدفوع',
      'total_claims': 'إجمالي السجلات',
      'total_amount': 'إجمالي المبلغ',
      'meal': 'وجبة',
      'transport': 'نقل',
      'office': 'مكتب',
      'fuel': 'وقود',
      'accommodation': 'إقامة',
      'choose_file': 'اختر ملفاً',
      'take_photo': 'التقاط صورة',
      'receipt_invoice': 'إيصال / فاتورة',
      'open_receipt': 'فتح الإيصال',
      'no_file_selected': 'لم يتم اختيار ملف بعد.',
      'helpdesk_title': 'مكتب الدعم',
      'new_ticket': 'طلب جديد',
      'open_ticket': 'فتح التذكرة',
      'my_tickets': 'طلباتي',
      'all_tickets': 'الكل',
      'ticket_detail': 'تفاصيل الطلب',
      'write_message': 'اكتب رسالة...',
      'send': 'إرسال',
      'attach_file': 'إرفاق ملف',
      'open_attachment': 'فتح المرفق',
      'category': 'الفئة',
      'priority': 'الأولوية',
      'subject': 'الموضوع',
      'message': 'الرسالة',
      'low': 'منخفض',
      'normal': 'عادي',
      'urgent': 'عاجل',
      'it_support': 'دعم تقنية المعلومات',
      'hr_request': 'طلب الموارد البشرية',
      'administrative': 'إداري',
      'payroll': 'الرواتب',
      'dossier_title': 'الملف الوظيفي',
      'upload_document': 'رفع مستند',
      'my_documents': 'مستنداتي',
      'upload_new_files': 'ارفع ملفات جديدة وتابع الحالات واحذف المعلّقة.',
      'open': 'فتح',
      'delete': 'حذف',
      'document_type': 'نوع المستند',
      'leave_type': 'نوع الإجازة',
      'attendance_title': 'الدوام والانصراف',
      'last_30_records': 'آخر 30 سجل',
      'clock_in': 'بدء العمل',
      'clock_out': 'إنهاء الدوام',
      'torch': 'الإضاءة',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'use_qr_text': 'استخدام نص QR',
      'web_fallback': 'بديل الويب',
      'status': 'الحالة',
      'work_hours': 'ساعات العمل',
      'check_in': 'دخول',
      'check_out': 'خروج',
      'open_attendance': 'فتح الدوام',
      'devices_empty': 'لا توجد أجهزة مسجلة لهذا الحساب بعد.',
      'platform': 'المنصة',
      'push_registered': 'تم تسجيل الإشعارات',
      'last_login': 'آخر دخول',
      'device_id': 'معرّف الجهاز',
      'current_device': 'الجهاز الحالي',
      'this_session': 'هذه الجلسة',
      'single_active_device': 'الجهاز النشط الوحيد',
      'single_device_policy_title': 'سياسة جهاز جوال واحد',
      'single_device_policy_desc': 'يمكن للمستخدم البقاء نشطًا على جهاز جوال واحد فقط في الوقت نفسه. عند تسجيل الدخول من جهاز جديد تتم إزالة الجهاز النشط السابق تلقائيًا من القائمة.',
      'single_device_policy_active_state': 'هذا الجهاز هو جلسة الجوال النشطة لحسابك.',
      'device_switch_notice_single': 'تم إغلاق جلسة جهاز الجوال السابقة أثناء تسجيل الدخول هذا.',
      'device_switch_notice_multi': 'تم إغلاق جلسات أجهزة الجوال السابقة أثناء تسجيل الدخول هذا.',
      'platform_web': 'ويب',
      'platform_android': 'أندرويد',
      'platform_ios': 'آيفون',
      'platform_macos': 'macOS',
      'year_label': 'السنة',
      'used_days': 'الأيام المستخدمة',
      'leave_types': 'أنواع الإجازات',
      'currency': 'العملة',
      'description': 'الوصف',
      'date': 'التاريخ',
      'status_pending': 'قيد الانتظار',
      'status_approved': 'تمت الموافقة',
      'status_rejected': 'مرفوض',
      'status_paid': 'مدفوع',
      'status_open': 'مفتوح',
      'status_in_progress': 'قيد المعالجة',
      'status_resolved': 'تم الحل',
      'status_present': 'حاضر',
      'status_not_started': 'لم يبدأ',
      'status_early_out': 'خروج مبكر',
      'status_late_early_out': 'دخول متأخر / خروج مبكر',
      'identity_copy': 'نسخة الهوية',
      'passport_copy': 'نسخة جواز السفر',
      'contract': 'العقد',
      'certificate': 'الشهادة',
      'payroll_document': 'مستند الرواتب',
      'upload_document_title': 'رفع مستند',
      'uploaded_on': 'تاريخ الرفع',
      'choose_document': 'اختر مستندًا',
      'uploading': 'جارٍ الرفع...',
      'choose_document_first': 'يرجى اختيار مستند أولاً.',
      'document_upload_failed': 'تعذر رفع المستند.',
      'document_delete_failed': 'تعذر حذف المستند.',
      'no_documents_found': 'لا توجد مستندات بعد.',
      'no_documents_for_filter': 'لا توجد مستندات لهذا الفلتر.',
      'no_support_tickets': 'لم يتم إنشاء أي تذكرة دعم بعد.',
      'no_tickets_for_filter': 'لا توجد تذاكر لهذا الفلتر.',
      'ticket_detail_load_failed': 'تعذر تحميل تفاصيل التذكرة.',
      'ticket_message_failed': 'تعذر إرسال الرسالة.',
      'ticket_create_failed': 'تعذر إنشاء التذكرة.',
      'new_ticket_title': 'تذكرة جديدة',
      'add_file': 'إضافة ملف',
      'submit_required_fields': 'يرجى إكمال جميع الحقول المطلوبة.',
      'message_with_attachment': 'يرجى مراجعة الملف المرفق.',
      'camera_black_help': 'إذا بقيت معاينة الكاميرا سوداء في Chrome، الصق محتوى QR هنا لمتابعة الاختبار.',
      'camera_not_ready': 'الكاميرا غير جاهزة بعد.',
      'attendance_scan_validating': 'تم اكتشاف QR. جارٍ التحقق من الموقع...',
      'attendance_action_failed': 'فشلت عملية الدوام.',
      'attendance_paste_qr_first': 'يرجى لصق محتوى QR أولاً.',
      'attendance_location_disabled': 'خدمات الموقع معطلة.',
      'attendance_location_required': 'إذن الموقع مطلوب للدوام.',
      'secure_attendance': 'دوام آمن',
      'secure_attendance_desc': 'استخدم الكاميرا وGPS للتحقق من رمز QR الخاص بموقع العمل قبل بدء أو إنهاء الدوام.',
      'no_attendance_records': 'لا توجد سجلات دوام بعد.',
      'form_validation_error': 'يرجى إكمال جميع الحقول بشكل صحيح.',
      'leave_submit_failed': 'تعذر إرسال طلب الإجازة.',
      'expense_submit_failed': 'تعذر إرسال المصروف.',
      'no_expense_records': 'لا توجد سجلات مصروفات بعد.',
      'no_expenses_for_filter': 'لا توجد سجلات مصروفات لهذا الفلتر.',
      'employee_role': 'موظف',
      'manager_role': 'مدير',
      'admin_role': 'مسؤول',
      'superadmin_role': 'مشرف عام',
      'status_on_time': 'في الوقت',
      'status_late': 'متأخر',
      'status_absent': 'غائب',
      'attendance_record_details': 'تفاصيل الدوام',
      'tap_to_view_details': 'اضغط لعرض التفاصيل',
      'leave_request_details': 'تفاصيل الإجازة',
      'expense_details': 'تفاصيل المصروف',
      'document_details': 'تفاصيل المستند',
      'date_range': 'نطاق التاريخ',
      'file_name': 'اسم الملف',
      'schedule_name': 'خطة الدوام',
      'schedule_type': 'نوع الخطة',
      'scheduled_hours': 'الساعات المجدولة',
      'late_minutes': 'دقائق التأخر',
      'early_leave_minutes': 'الخروج المبكر',
      'overtime_minutes': 'العمل الإضافي',
      'violation': 'المخالفة',
      'approval_status': 'حالة الموافقة',
      'none': 'لا يوجد',
      'minutes_short': 'د',
      'schedule_type_fixed': 'ثابت',
      'schedule_type_flex': 'مرن',
      'violation_none': 'لا توجد مخالفة',
      'violation_late_in': 'دخول متأخر',
      'violation_early_out': 'خروج مبكر',
      'violation_late_in_early_out': 'دخول متأخر / خروج مبكر',
      'violation_missing_clock_in': 'سجل بدء الدوام مفقود',
      'violation_missing_clock_out': 'سجل إنهاء الدوام مفقود',
      'not_available': 'غير متاح',
      'to_be_announced': 'سيُعلن لاحقًا',
      'quick_profile': 'الملف السريع',
      'phone': 'الهاتف',
      'department': 'القسم',
      'position': 'المنصب',
      'home_load_failed': 'تعذر تحميل بيانات الشاشة الرئيسية.',
      'no_upcoming_training': 'لا توجد تدريبات قادمة',
      'assigned_sessions_here': 'ستظهر الجلسات المعيّنة هنا تلقائيًا.',
      'selected_file': 'الملف المحدد',
      'captured_photo': 'الصورة الملتقطة',
      'optimized_file': 'تم تحسينه',
      'yes': 'نعم',
      'no': 'لا',
    },
  };

  String t(String key) {
    final lang = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any((item) => item.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}

extension AppLocalizationsContext on BuildContext {
  String tr(String key) => AppLocalizations.of(this).t(key);

  bool get isRtl => Localizations.localeOf(this).languageCode == 'ar';
}
